### PR TITLE
Added InsertionSort algorithm

### PR DESCRIPTION
**Pull request by Deepshikhayadav**
### Describe your change:

* [X] Add an algorithm?
* [X] Fix a bug or typo in an existing algorithm?
* [X] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by Deepshikhayadav — COMMENTED** [review]
please review my commit

**Review by Deepshikhayadav — COMMENTED** [review]
test cases, type hint and descriptive name added

**Review by Deepshikhayadav — COMMENTED** [review]
test cases, type hint and descriptive name added

**Review by tianyizheng02 — COMMENTED** [review]
[`insertion_sort.py`](https://github.com/TheAlgorithms/Python/blob/master/sorts/insertion_sort.py) already implements the insertion sort algorithm.

**Comment by tianyizheng02** [comment]
@cclauss Close as duplicate implementation?

**Pull request closed without merging**
