### PR TITLE
Add README.md files

### PR DESCRIPTION
**Pull request by Leoriem-code**
### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Leoriem-code** [comment]
I need to clean my fork of this repository, so I will close this push request, delete my fork, fork it again and continue where I lefted

**Comment by cclauss** [comment]
Please try to keep PRs reasonable to review.  39 files is too much for a single PR that is not software generated (black, isort, etc.).

**Comment by Leoriem-code** [comment]
Should I close the request and open a PR for each README file ?

**Comment by cclauss** [comment]
Before Hactoberfest we had 20 open PRs and today we have 194 so you understand our frustration...

5 files at a time seems to be reasonable.

**Comment by Leoriem-code** [comment]
No problem

**Pull request closed without merging**
