### PR TITLE
cycle_detection_undirected_graph

### PR DESCRIPTION
**Pull request by subahanii**
cycle_detection_undirected_graph using Disjoint set Data Structure in Python

### CODE REVIEW

**Comment by cclauss** [comment]
Please add doctests as discussed in CONTRIBUTING.md.

**Comment by subahanii** [comment]
> Please add doctests as discussed in CONTRIBUTING.md.

Hi Sir, Why are you not merging my pull requests.  I think all the info require to understand this algo have clearly mentioned by commenting in respective lines.

I fill very proud if Marge is done. Because this repo is one of the top repo for python repo.

Thank you!

**Comment by cclauss** [comment]
https://travis-ci.com/TheAlgorithms/Python/builds/132788969#L543

I have added three doctests, two of which fail.  With the new code, try the following:
```
python3 -m doctest cycle_detection_undirected_graph.py
python3 -m doctest -v cycle_detection_undirected_graph.py
```

As discussed in CONTRIBUTING.md:
* Single character variable names should be avoided especially as function parameters for readability reasons
* addEdge() --> add_edge()
* isCyclic() --> is_cyclic()
* parentA --> parent_a
* list(map(int, input().strip().split())) --> [int(node) for node in input().split()]
* Code should be formatted with psf/black
* Use of typehints are encouraged

Also, is_cyclic() should return True/False instead of 1/0.

**Comment by subahanii** [comment]
> https://travis-ci.com/TheAlgorithms/Python/builds/132788969#L543
> 
> I have added three doctests, two of which fail. With the new code, try the following:
> 
> ```
> python3 -m doctest cycle_detection_undirected_graph.py
> python3 -m doctest -v cycle_detection_undirected_graph.py
> ```
> 
> As discussed in CONTRIBUTING.md:
> 
> * Single character variable names should be avoided especially as function parameters for readability reasons
> * addEdge() --> add_edge()
> * isCyclic() --> is_cyclic()
> * parentA --> parent_a
> * list(map(int, input().strip().split())) --> [int(node) for node in input().split()]
> * Code should be formatted with psf/black
> * Use of typehints are encouraged
> 
> Also, is_cyclic() should return True/False instead of 1/0.

I tried my best for make docset.
I am new very contributer,so i think i am not getting where is mistake . Please help me to resolve this if you want.
This program is perfectly work in my local PC.

Now i am tired .
Thank You!

**Comment by cclauss** [comment]
My advise is that you take [this file](https://raw.githubusercontent.com/TheAlgorithms/Python/a0054415c37741c9f0aac836bc1ba246c37ae76d/graphs/cycle_detection_undirected_graph.py) and put it into a **separate** file on your local disk and then run `python3 -m doctest -v new_file.py` and make small changes until you get the second test to pass.  (The third test should raise an exception).

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/maths/greatest_common_divisor.py#L25-L30 should help you to see doctests that pass.

**Pull request closed without merging**
