### PR TITLE
Fix imports for all namespace packages

### PR DESCRIPTION
**Pull request by dhruvmanila**
As mentioned in #2503 

### **Describe your change:**

* [x] Fix a bug or typo in an existing algorithm?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Ok, some of the `doctest` are failing due to the change of paths. 
@cclauss Should I fix it?

**Comment by cclauss** [comment]
Yes, please

**Comment by dhruvmanila** [comment]
It seems like there's a `doctest` which is actually failing?
Can you take a look at it? https://travis-ci.com/github/TheAlgorithms/Python/jobs/392149978#L1300
@cclauss

**Comment by dhruvmanila** [comment]
Weird, it's passing when I run it locally.

**Comment by dhruvmanila** [comment]
Can you rerun the build? @cclauss

**Review by cclauss — APPROVED** [review]
THANKS!!

**Comment by cclauss** [comment]
Travis is being flakey lately.

**Pull request merged**
