### PR TITLE
HacktoberFest: Euler problem 85 solution

### PR DESCRIPTION
**Pull request by Heisenberg399**
### **Describe your change:**
Added Folder with python file of the solution to the Euler problem no. 85

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$2510}`.

### CODE REVIEW

**Comment by Heisenberg399** [comment]
can someone help me to fix this to errors

**Comment by spamegg1** [comment]
@Heisenberg399 Travis CI:
> E   ValueError: line 15 of the docstring for sol1 lacks blank after >>>: '>>>>>>> c4ecb74d98da02522cf42cc01e88301a58c61edb'

pre-commit:
> +        if diff < min_diff:
+            area = x * y
             min_diff = diff
 print(area)
Error: Process completed with exit code 1.

I'm not sure, but it could be line 20 which goes on for 112 columns, or the capitalized variable `Rec`.

These might be fixed by running `black` as explained in [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).

**Comment by Heisenberg399** [comment]
@spamegg1 thanks will do that..

**Review by dhruvmanila — COMMENTED** [review]
### Announcement:

@Heisenberg399

*This message is sent to all pull requests which are **OPEN, NOT MERGED, not containing 'wontfix' label and contains 'Project Euler' or 'Project' or 'Euler' (case doesn't matter) in their title**. If this message doesn't apply to your pull request, please ignore this.*

### Message:

This is to notify all the users submitting a pull request for the Project Euler solution that the [README.md](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) file has been updated with all the style requirements necessary for the directory and solution files. ***Please read through it and make all the necessary changes required to your submission.***

**Pull request closed without merging**
