### PR TITLE
Solution to Project Euler problem 073

### PR DESCRIPTION
**Pull request by anotherishi**
### **Describe your change:**

Add solution to Project Euler problem 73.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by rishio** [comment]
I just want to say that the execution might take 1-2 minutes!

**Comment by MaximSmolskiy** [comment]
> I just want to say that the execution might take 1-2 minutes!

@rishio 1-2 minutes is quite slow. But it can be easily sped up to ~10 seconds.

1. Just swap conditions `highest_common_factor(numerator, denominator) == 1` and `1 / 3 < numerator / denominator < 1 / 2`:
```
if (
    1 / 3 < numerator / denominator < 1 / 2
    and highest_common_factor(numerator, denominator) == 1
):
```
instead of:
```
if (
    highest_common_factor(numerator, denominator) == 1
    and 1 / 3 < numerator / denominator < 1 / 2
):
```

2. Replace `highest_common_factor` with standard function `gcd` from `math` module.

**Comment by rishio** [comment]
@MaximSmolskiy Oh yes! now it is much faster.
Thank you so much; but how should I make changes here?

**Comment by MaximSmolskiy** [comment]
@rishio `0.333333` is a weak lower estimation of `1 / 3`. So, now `1 / 3` is countered as good fraction and `solution() = 7295373`, not correct `7295372`

**Comment by cclauss** [comment]
In preparation for that denial-of-service attack that is [Hacktoberfest](https://hacktoberfest.com), I am closing all pull requests that do not have passing tests.

**Pull request closed without merging**
