### PR TITLE
New algorithm

### PR DESCRIPTION
**Pull request by erdum**
### **Describe your change:**
I made Ohm law algorithm which can perform full ohms law calculations, this is my first time contribution i read all guidelines but i don't know how to pull separate request so jus forked this repo clone it then add my file and in separate folder then and run flake8 then just push it up to forked repo and come here to open PR please help me because i am new thanks.
And here is the wiki link for ohms law https://en.wikipedia.org/wiki/Ohm%27s_law

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by erdum** [comment]
I just want to to add this algorithm, but i face lots of issue in PR , algorithm is not as complicated as PR😑

**Comment by DamirHanov** [comment]
Hey! I also a new guy here and recently created one pull request. 
Your build fails because the filename of your script has uppercase letter 'O'.

Also you should add some tests as it's shown [here](https://docs.python.org/3/library/doctest.html), and type hints for your input parameters.

**Comment by erdum** [comment]
DamirHanov what tests i should add?? I have no idea and what is type hints ?? Please explain me thanks

**Comment by erdum** [comment]
DamirHanov plz edit this file in my repo and make PR so i can see what you mean by type hints erdum/My_Python

**Pull request closed without merging**
