### PR TITLE
Update mypy workflow to include arithmetic_analysis

### PR DESCRIPTION
**Pull request by dhruvmanila**
I didn't receive any error when I ran `mypy` locally on the directory.

```console
❯ mypy --ignore-missing-imports arithmetic_analysis/
Success: no issues found in 11 source files
```

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
I had the same experience at https://github.com/TheAlgorithms/Python/pull/4276/commits/e578d9de772da72da27b11c1a394fc79278ff3df also with the `digital_image_processing` directory.

**Comment by cclauss** [comment]
@hauntsaninja Do you have any insight on why mypy is passing locally but failing in a GitHub Action job?

**Comment by cclauss** [comment]
Perhaps the local tests are passing because `numpy` is not installed locally and mypy is run with `--ignore-missing-imports` while `numpy` is installed in the GitHub Action.

**Comment by dhruvmanila** [comment]
I did install `numpy` in my local environment. Even after that it gives me the error. It's mainly because `numpy` is present that `mypy` is complaining, if you uninstall `numpy`, `mypy` stops complaining. I will investigate further as to why this is.

**Comment by cclauss** [comment]
My sense is that `numpy.typing` is key to making it pass everywhere.

**Comment by cclauss** [comment]
Closed by #4304 ?

**Pull request closed without merging**
