### PR TITLE
LGTM: Start testing on Python 3 instead of Python 2

### PR DESCRIPTION
**Pull request by cclauss**
Fixes: #492

Tests for the issues raised in #485, #486, and #500

Ready for review. @harshildarji @ParthS007 @AlexDvorak

### CODE REVIEW

**Comment by harshildarji** [comment]
@cclauss All checks failed! The LGTM extraction log says `undefined name 'raw_input'` in several files. I think we will have to update all those files. People imported `print_function` from `__future__` as:
```python
from __future__ import print_function
```
but did not bothered to write:
```python
try:
    raw_input             # Python 2
except NameError:
    raw_input = input     # Python 3
```

**Comment by AlexDvorak** [comment]
i’ll change the ‘.lgtm.yml’ in #500 so that all tests will pass then this can be closed or merged

**Comment by cclauss** [comment]
@harshildarji Yes...  Those issues were created in on merged pull request.  https://w3.ibm.com/help/#/article/slack/overview  @AlexDvorak is busy fixing them in #500

**Comment by harshildarji** [comment]
@cclauss I can revert the PR #483! But as you said @AlexDvorak is working on it, I won't revert it, otherwise it may cause conflicts (*I think*).

**Comment by AlexDvorak** [comment]
so is this PR going to get merged as #500 is already merged?

**Comment by cclauss** [comment]
We need #486 to land first.  Also a __raw_int__ fix.

**Comment by harshildarji** [comment]
@cclauss I've corrected **raw_int** and also that **get_ipython** thing! So I think this time there will be no errors!

**Pull request merged**
