### PR TITLE
Fix ruff errors

### LINKED ISSUE #8935: Why am i facing ruff failed on other files?
### What would you like to share?

I am trying to add a new algorithm for first time. While i submitting my file and bot is checking for `ruff` test, its failed on files except my file. 
If anyone can help me out of this, i will glad.

PR: [https://github.com/TheAlgorithms/Python/actions/runs/5805449154/job/15736567968?pr=8931](url)

Thanks in Advance.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tianyizheng02**
### Describe your change:

Fixes #8935 

Fixing ruff errors again due to the recent version update

Notably, I didn't fix the ruff error in [neural_network/input_data.py](https://github.com/TheAlgorithms/Python/blob/842d03fb2ab7d83e4d4081c248d71e89bb520809/neural_network/input_data.py) because it appears that the file was taken directly from TensorFlow's codebase, and I wanted to avoid modifying it _just_ yet. Instead, I renamed it to neural_network/input_data.py_tf because it should be left out of the directory for the following reasons:
1. Its sole purpose is to be used by [neural_network/gan.py_tf](https://github.com/TheAlgorithms/Python/blob/842d03fb2ab7d83e4d4081c248d71e89bb520809/neural_network/gan.py_tf), which is itself left out of the directory because of issues with TensorFlow.
2. All of it's actually deprecated—TensorFlow explicitly says so in the code and recommends getting the necessary input data using a different function. If/when neural_network/gan.py_tf is eventually added back to the directory, its implementation should be changed to not use neural_network/input_data.py anyway.

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by tianyizheng02** [comment]
How did neural_network/gan.py_tf make it past this bot then...

**Comment by cclauss** [comment]
Please add an issue to rehabilitate `neural_network/gan.py_tf`

**Comment by cclauss** [comment]
@dhruvmanila What is your take on ruff rule PYI024?  This seems like a lot of rework for minimal gain.  Do you believe we should ignore PYI024 or do you see sufficient value in paying attention to this rule?

**Comment by dhruvmanila** [comment]
The `typing.NamedTuple` is the typed version of the same in `collections` module. I think we should move to that because it provides a lot of benefits namely types for all fields, editor awareness of the fields and IMO it has a much better API.

**Review by dhruvmanila — APPROVED** [review]

**Comment by dhruvmanila** [comment]
@tianyizheng02 if possible, please open any enhancements or bugs related to algorithms-keeper in the repository :)

**Pull request merged**
