### PR TITLE
Update dictionary.txt

### PR DESCRIPTION
**Pull request by percy07**
Added a word 'AYUH' meaning 'Yes'.
This word is recently added in Oxford Dictionary.

### CODE REVIEW

**Comment by cclauss** [comment]
Why?  How does it help?

**Comment by poyea** [comment]
Please make the changes for this file in one single PR. 

Related: #1510 #1507

**Comment by cclauss** [comment]
@poyea Is it really helpful to keep changing this file?

**Comment by poyea** [comment]
@cclauss This file is just a supplement to the directory (or the file is not an algorithm itself).  Opening multiple PRs to change it is obvious not necessary.

**Pull request closed without merging**
