### PR TITLE
Fix `iter_merge_sort` bug

### LINKED ISSUE #6152: Function iter_merge_sort has bug where array with length 2 is not sorted
[Test Report - Iter merge sort function.pdf](https://github.com/TheAlgorithms/Python/files/8698882/Test.Report.-.Iter.merge.sort.function.pdf)
Here all the report.

### PR DESCRIPTION
**Pull request by dangbb**
### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$6152}`.

Fixes #6152

### CODE REVIEW

**Comment by dangbb** [comment]
I also do addition testing for conversions\octal_to_decimal.py. 

[Test Report - add MCC and DU path test.pdf](https://github.com/TheAlgorithms/Python/files/8710632/Test.Report.-.add.MCC.and.DU.path.test.pdf)

Here is the document about MCC and DU path for testing conversions\octal_to_decimal.py.

**Comment by poyea** [comment]
Thanks @dangbb Please fix the pre-commit issue?

**Comment by dangbb** [comment]
Thank @poyea , I have fixed the pre-commit issue. Please give it a check.

**Review by poyea — APPROVED** [review]
Thank you for your pull request!🤩

**Pull request merged**
