### PR TITLE
Adding kmeans clustering algorithm with scikit-learn library

### PR DESCRIPTION
**Pull request by Kaif10**
### **Describe your change:**

Added a new machine learning algorithm

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
This is a how-to-use rather than an algorithm as discussed in CONTRIBUTING.md.

**Comment by Kaif10** [comment]
I cannot add an example with inbuilt Python package?? I saw there is an
example of knn with sklearn in machine learning repository.

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/machine_learning/k_means_clust.py 

Last paragraph of https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#what-is-an-algorithm

**Comment by Kaif10** [comment]
https://github.com/TheAlgorithms/Python/blob/master/machine_learning/knn_sklearn.py Sent from Mail for Windows 10 From: Christian ClaussSent: 19 July 2020 00:06To: TheAlgorithms/PythonCc: Kaif Kohari; MentionSubject: Re: [TheAlgorithms/Python] Adding kmeans clustering algorithm with scikit-learn library (#2213) https://github.com/TheAlgorithms/Python/blob/master/machine_learning/k_means_clust.pyLast paragraph of https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#what-is-an-algorithm—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request closed without merging**
