### PR TITLE
Updated maths/number_of_digits.py

### LINKED ISSUE #2220: maths/number_of_digits.py is naive!
<code>[maths/number_of_digits.py](https://github.com/TheAlgorithms/Python/blob/master/maths/number_of_digits.py)</code> has a naive method. The suggested method has a time complexity of O(n). We can count number of digits of a number in O(1).

### PR DESCRIPTION
**Pull request by vasugamdha**
### **Added two more methods!**
`Fixes: #2220 `
I have added 2 methods for <code>[maths/number_of_digits.py](https://github.com/TheAlgorithms/Python/blob/master/maths/number_of_digits.py)</code>:
1. <code>num_digits2()</code>: Also an O(n) algorithm approach.
2. <code>num_digits_fast()</code>: An O(1) algorithm for counting the number of digits

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

closes #2220

### CODE REVIEW

**Comment by vasugamdha** [comment]
@cclauss I don't know why my PR is failing TravisCI checks. Please suggest some changes that need to be implemented to pass the checks. @TravisBuddy

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/Travis_CI_tests_are_failing.md

**Comment by vasugamdha** [comment]
@cclauss I have fixed the #2220 issue and it's ready for review and merge.

**Comment by vasugamdha** [comment]
hello @cclauss , can you please merge this PR, as it has already passed both the checks and fixes the #2220 issue? Thanks.

**Comment by cclauss** [comment]
Unfortunately, I see no benchmark code.

**Comment by vasugamdha** [comment]
I haven't written benchmark code, as the function , I defined (`num_digits_fast()`), clearly returns number of digits in `O(1)`. While the one already written function returns the same in `O(n)`.

**Comment by cclauss** [comment]
What _proof_ do you have for those _theoretical_ statements without benchmarking them with the same data?  Here examples of algorithms with benchmarks using [timeit](https://docs.python.org/3.8/library/timeit.html): https://github.com/TheAlgorithms/Python/search?q=timeit

**Comment by vasugamdha** [comment]
### **First comment update!!**
### Added two more methods!
`Fixes: #2220 `
I have added 2 methods for <code>[maths/number_of_digits.py](https://github.com/TheAlgorithms/Python/blob/master/maths/number_of_digits.py)</code>, which are comparatively faster then already present method:

1. `num_digits_fast()`
2. `num_digits_faster()`

### Here is the output of the benchmark code.

image

**Pull request merged**
