### PR TITLE
Change shebang of validation script to python, because python3 is not installed on Windows

### PR DESCRIPTION
**Pull request by Cjkjvfnby**
### Describe your change:

When I run `pre-commit run --all files` I got an error. 

```
Validate filenames.......................................................Failed
- hook id: validate-filenames
- exit code: 9009
```

This error happens because the python3 executable is not found. 

I have a Windows machine and just installed the latest Python via the official installer. Python3 alias is not included.

It was a time when using python2 and python3 aliases was important, but now python2 is not used anymore so it should not be a problem.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
Does Windows use shebang files?!?

On my Mac... `python --version`
```
zsh: command not found: python
```
This can be fixed by adding a venv but that is the default behavior.

**Comment by Cjkjvfnby** [comment]
> Does Windows use shebang files?!?

It uses the associated program by an extension.  When Python is installed, `py` is associated with it.   
`py` is a switcher between installed Pythons, and it respects the shebang.  https://docs.python.org/3/using/windows.html#python-launcher-for-windows

> On my Mac... python --version

On my Mac I use pyenv, I have both python and python3.  But not sure that my installation could be considered typical.

Docker image python:3.9.10 also supports `python` 


I'll check if I could fix it on my Win machine with py.ini.  If it will work I'll post the solution here and close the PR.  Other users will be able to find this problem by searching.

**Comment by cclauss** [comment]
Funny because, I use `py` on my Mac and earlier today I opened and then closed https://github.com/brettcannon/python-launcher/issues/235

**Comment by Cjkjvfnby** [comment]
In my case, it's `py` from cPython.   According to docs and my experiments `python3` and `/usr/bin/env python` are supported and `/usr/bin/env python3` is not.  I Will resubmit the issue there. 

I haven't found any workaround yet.

**Pull request closed without merging**
