### PR TITLE
Delete double_ended_queue.py

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #1200 

As discussed on #1200 this file does not contain an algorithm as it does not implement a double ended queue but instead just uses the standard library's DEQ.  @paulo9428 @cozek Your reviews please.

### CODE REVIEW

**Comment by paulo9428** [comment]
I totally agree with that.

**Comment by cozek** [comment]
> I totally agree with that.

Hey, @paulo9428. I think that it's great that you want to commit to open source. And I want to see your pull request be merged! Please do not be discouraged.

I would advise you to read up on how to implement queues first. Once you are comfortable with that and have a clear understanding of how it's working, try to implement deque on your own. After that, you should write comments that clearly describe the logic behind your code in the format described in the contribution guide of this repo (along with doctests, but that's for later). You could, for instance, take reference from the other queues already contributed to this repo and build on that (with due credits to the authors). Maybe even pick up jupyter notebook and write a story on deques. The main point of your contribution is that it need not be industry level perfect, but it should educate the person reading your code about deques and how it works. 

I hope we see another PR from you soon! Keep coding!

**Comment by paulo9428** [comment]
thank you!

**Comment by cclauss** [comment]
@paulo9428 We look forward to your next contribution...  Thanks for joining our team!

**Pull request closed without merging**
