### PR TITLE
Add `Mirror a Binary Tree` solution

### PR DESCRIPTION
**Pull request by gouravrajbit**
### Describe your change: Add an algorithm to invert a binary tree with an example demonstrating inversion of a sample binary tree.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by gouravrajbit** [comment]
@tianyizheng02 Please review this PR 🙏

**Comment by gouravrajbit** [comment]
@tianyizheng02 Please review this PR.

**Comment by tianyizheng02** [comment]
Inverting a binary tree appears to already be implemented in [data_structures/binary_tree/binary_tree_mirror.py](https://github.com/TheAlgorithms/Python/blob/fdb0635c71318da758fafcda80154d03dbbd5c5a/data_structures/binary_tree/binary_tree_mirror.py). However, this existing implementation uses a dict-based representation of a binary tree rather than a node-based representation, and I personally prefer this PR's implementation.

@cclauss, should we keep both implementations? Or should this one replace the existing implementation?

**Review by cclauss — APPROVED** [review]
I like the name `mirror` more than if you have a triangle shaped like:
```
  *
 ***
*****
```
then the ___inverted___ triangle has a shape:
```
  *
 ***
*****
```
When I stand on my head, I am inverted.
When I look in the mirror, left and right are swapped but top and bottom are not.

Given that this directory is `data_structures` I think that using a dict to represent a binary tree is a bit strange but let's keep both in place for now.

**Pull request merged**
