### PR TITLE
Update coin_change.py

### LINKED ISSUE #2612: Update coin change
Code of coin change  in dynamic programming  is incomplete as it is showing no output and no input is provided in given code .

### PR DESCRIPTION
**Pull request by Mohitkumar6122**
### **Describe your change:**

Fixed #2612 
updated coin change problem 

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by poyea** [comment]
Usually we ask for input from users. Can you change it?

**Comment by Mohitkumar6122** [comment]
> Usually we ask for input from users. Can you change it?

yeah sure

**Review by Mohitkumar6122 — COMMENTED** [review]
updated  ( takes input from user )

**Comment by Mohitkumar6122** [comment]
@cclauss can u tell me what is this pre-commit error showing in my code ?

**Review by Kush1101 — COMMENTED** [review]
This is not a useful contribution. Please bring forward a genuine idea/implementation to contribute

**Pull request closed without merging**
