### PR TITLE
Added static typing to backtracking algorithms

### PR DESCRIPTION
**Pull request by jenia90**
For issue #2128: I've added static typing to every function that was missing it in the backtracking algorithms folder.

### CODE REVIEW

**Comment by spamegg1** [comment]
Looks good!

**Review by poyea — APPROVED** [review]

**Comment by dhruvmanila** [comment]
Um, this pull request contains invalid type hints, I don't understand why you merged it? @poyea 
This is only increasing the `mypy` errors in this repository 😞

**Comment by poyea** [comment]
> Um, this pull request contains invalid type hints, I don't understand why you merged it? @poyea
> This is only increasing the `mypy` errors in this repository 😞

Where's it? The code passes the check, but we can fix it in a new one quickly.

**Comment by dhruvmanila** [comment]
Currently, we are not running `mypy` in our CI as there are more than 700 errors in the entire repository.
https://github.com/TheAlgorithms/Python/blob/master/.pre-commit-config.yaml#L33

Any PR which provides type hints should be checked by the maintainer by running `mypy` locally until we start running it in our CI.

**Comment by poyea** [comment]
@jenia90 would you be able to fix this - probably due to `[int]`? Otherwise I can fix this.

**Comment by dhruvmanila** [comment]
Please run `mypy` to whichever files is being fixed.

**Pull request merged**
