### PR TITLE
add forecasting code

### PR DESCRIPTION
**Pull request by nandiya**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Ankuraxz** [comment]
E   FileNotFoundError: [Errno 2] No such file or directory: 'ex_data.csv'
Kindly add ex_data.csv in correct sub-repo/dir

**Comment by Ankuraxz** [comment]
+import warnings
+
 import numpy as np
 import pandas as pd
 from sklearn.preprocessing import Normalizer
 from sklearn.svm import SVR
 from statsmodels.tsa.statespace.sarimax import SARIMAX
-import warnings
 
 
 def lin_reg_pred(train_dt, train_usr, train_mtch, test_dt, test_mtch):
@@ -81,7 +82,7 @@ def data_safety_checker(list_vote, actual_result):
 
 # data_input_df = pd.read_csv("ex_data.csv", header=None)
 list_data = [[18231, 0.0, 1], [22621, 1.0, 2], [15675, 0.0, 3], [23583, 1.0, 4]]
-data_input_df = pd.DataFrame(list_data, columns=['total_user', 'total_even', 'days'])
+data_input_df = pd.DataFrame(list_data, columns=["total_user", "total_even", "days"])
 
 """

Errors in spacing and placement of libs

**Comment by nandiya** [comment]
@Ankuraxz  please review the one in forecast branch, and  for the ex_data.csv.. i'm still confused why it can't read the path
i'm already following the other folder in lstm but it's still cant read the path even though it works fine locally

so i only give a couple of data to test in forecast branch

**Comment by Ankuraxz** [comment]
Ok I will fork your repo and suggest change in pr

**Comment by Ankuraxz** [comment]
What are the updates on this project, did you resolved the issues?

**Comment by nandiya** [comment]
> What are the updates on this project, did you resolved the issues?

as i said, i had new branch called "forecast" 
and its already merged and resolved

**Comment by Ankuraxz** [comment]
well done then

**Comment by nandiya** [comment]
ty ankur^^

**Pull request closed without merging**
