### PR TITLE
Created cube_3d.py

### PR DESCRIPTION
**Pull request by debnath003**
### Describe your change:

Added a code that shows a 3D cube using matplotlib module in Python in the "graphics" directory

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by debnath003** [comment]
@cclauss In my computer the code is working fine, but here it shows the module error, why is it so? And please give suggestions so that I can edit the PR for getting approval, thank you!

**Comment by debnath003** [comment]
@cclauss could you please merge and approve this PR for hacktoberfest and give that hacktoberfest-accepted label? awaiting your review!

**Comment by cclauss** [comment]
I would change the filename to `cube_3d.py`.

According to CONTRIBUTING.md, this would be classified as a how-to-use for matplotlib and not an algorithm.  Also, the doctest exists but it is skipped but `graphics` are difficult to test.

I kind of like this one so I will leave it to @ChrisO345 and/or @tianyizheng02

**Comment by debnath003** [comment]
> I would change the filename to `cube_3d.py`.
> 
> According to CONTRIBUTING.md, this would be classified as a _how-to-use_ for matplotlib and not an algorithm. Also, the doctest exists but it is skipped however `graphics` are difficult to test.
> 
> I kind of like this one so I will leave it to @ChrisO345 and/or @tianyizheng02

So I have to change the filename only right? @cclauss

**Comment by cclauss** [comment]
Right.

**Comment by debnath003** [comment]
I think the filename is now correct, but who will merge this PR then? You @cclauss or any other one?

**Comment by debnath003** [comment]
@cclauss @ChrisO345 @tianyizheng02 Someone please approve and merge this PR so that it can get eligibility for hacktoberfest! Also please give hacktoberfest-accepted label in this PR! Thank you and waiting for approved review!

**Comment by cclauss** [comment]
@debnath003 This is a how-to-use, not an algorithm.  We have 118 open pull requests and on Oct. 1st we had zero.  There is no guarantee that this will be merged.  If you are impatient then close this one and create a new algorithm PR.

**Pull request closed without merging**
