### PR TITLE
Create SortReadme.nmd

### PR DESCRIPTION
**Pull request by prateekiiest**
Create a new Readme for sorts part and delete those sort description in the main Readme.md

### CODE REVIEW

**Comment by H-Darji** [comment]
Why you closed this?

**Comment by prateekiiest** [comment]
Sorry, I created this PR by mistake.

**Comment by prateekiiest** [comment]
I actually created this PR for a different repo, but added this by mistake to this repo

**Comment by H-Darji** [comment]
OK

**Pull request closed without merging**
