### PR TITLE
Fixes: #3163 Adds solution to problem 102

### PR DESCRIPTION
**Pull request by pastre**
### **Describe your change:**

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by pastre** [comment]
Is there anything missing for this PR to be merged? :)

**Review by 53jk1 — APPROVED** [review]

**Comment by poyea** [comment]
For `project_euler` you should have a solution class.

**Comment by pastre** [comment]
@poyea what class should I create? As far as I can see, my submission perfectly matches all requirements in the [README](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) inside `project_euler`

**Comment by poyea** [comment]
It requires default parameter for solution function, no? Also can the txt file be read locally?

**Comment by pastre** [comment]
@poyea  `def solution() -> int` does not require any parameter. It can read from the local text file, but since the CI was failing at it, I chose to read from a remote URL

**Comment by poyea** [comment]
ah ok. Although there're other ways, I think this is good enough.

**Review by poyea — APPROVED** [review]

**Comment by poyea** [comment]
I'll review this in a moment

**Comment by dhruvmanila** [comment]
I will include a guide in the README about how to use local files in the solution soon. As we are going to get the input from a file, there won't be any requirement of arguments to the `solution` function as the main goal to provide a parameter is to add the ability to test the function with different input.

As of now please take a look at this comment on how to use a local file in your algorithm: https://github.com/TheAlgorithms/Python/issues/2695#issuecomment-704237225

**Comment by pastre** [comment]
@dhruvmanila checkout `solution.py` on 7e93dfe9026e16f07cc721d7a0d40fcf5d3d284a, I was trying to load locally before fetching from the web. If nothing changed on Travis, it will not work. If there's anything I can do, just let me know

**Comment by dhruvmanila** [comment]
Please don't take things literally as specified. There should be a file extension to the actual path. What I meant by `<file name without extension>` is not to literally name it that but to make the variable name the same as that of the file so that it is easier to understand. You can use any name you like, that was just a framework.
```python
    script_dir = os.path.abspath(os.path.dirname(__file__))
    filepath = os.path.join(script_dir, "triangles_euler102.txt")
    with open(filepath, "r") as file_hand:
```

**Review by dhruvmanila — CHANGES_REQUESTED** [review]
Please make the necessary changes regarding the file input.

Also, there are many problems in the type hints specified and there are functions that do not contain type hints. Please provide the return type hints as well. Use `List[type]` where you return or input `list`. Take a look at the official documentation regarding type hints.

**Pull request closed without merging**
