### PR TITLE
Create quicksort.py

### LINKED ISSUE #12046: add quicksort under divide and conquer
### Feature description

would like to add quicksort algo under divide and conquer

### PR DESCRIPTION
**Pull request by OmMahajan29**
### Describe your change:

adding quicksort under divide and conquer in order to effective learn and understand data structures and algorithms

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #12046".

### CODE REVIEW

**Review by imSanko — CHANGES_REQUESTED** [review]
=========================== short test summary info ============================
FAILED divide_and_conquer/quicksort.py::divide_and_conquer.quicksort.partition
============ 1 failed, 1916 passed, 2 warnings in 74.56s (0:01:14) =============
Solve this !

**Comment by OmMahajan29** [comment]
> =========================== short test summary info ============================ FAILED divide_and_conquer/quicksort.py::divide_and_conquer.quicksort.partition ============ 1 failed, 1916 passed, 2 warnings in 74.56s (0:01:14) ============= Solve this !

thats what I am not understanding the bot is looking for doctest.testmod() after the first function

**Comment by OmMahajan29** [comment]
all tests passed allow merge or approve

**Review by Kabilduke — APPROVED** [review]

**Comment by tianyizheng02** [comment]
See my comment in the linked issue

**Pull request closed without merging**
