### PR TITLE
Create FirstQuartile.py

### PR DESCRIPTION
**Pull request by AugustofCravo**
Added function in Python that calculates the first quartile of a list.

### CODE REVIEW

**Comment by AnupKumarPanwar** [comment]
@AugustofCravo Can you extend the code to find all the 3 quartiles?

**Comment by AugustofCravo** [comment]
I´ll extend the code for the 3 quartiles.

**Comment by cclauss** [comment]
@AnupKumarPanwar Can you please re-review?

**Comment by AugustofCravo** [comment]
Yes, I will. Please, just give me some time. Im really busy right now. 3 days, ok?

**Pull request closed without merging**
