### PR TITLE
[ADD] Added integer_break.py

### PR DESCRIPTION
**Pull request by theinit01**
### Describe your change:

Added Integer break algorithm

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by theinit01** [comment]
@cclauss, can you please review the PR?
Thanks.

PS: please don't close this one please :cry:

**Comment by cclauss** [comment]
In what situation would the algorithm be used to solve a real-world problem?

**Comment by theinit01** [comment]
The "Integer Break" algorithm solves resource allocation problems encountered in engineering and manufacturing. It optimizes the distribution of resources to maximize product value, helping in efficient material utilization and cost-effective product design.

**Comment by theinit01** [comment]
@cclauss

**Comment by cclauss** [comment]
We currently have 213 open pull requests.  On October 1st. we had zero.  I asked a question and got a vague answer.  If you can tell me about a real, practical situation where this calculation would save time and/or money then we can continue.  If not, then please close this PR.

**Comment by theinit01** [comment]
@cclauss, can you tell me a valuable algorithm you think I can contribute?

**Pull request closed without merging**
