### PR TITLE
Added script for automatically generating DIRECTORY.md

### PR DESCRIPTION
**Pull request by NielXu**
I added a python script that scans through the directory and generates the corresponding DIRECTORY.md. I have also done some formatting for the names, for example, replace underscores to whitespaces, capitalize folder names. However, contributors must still run `python script.py` in order to generate DIRECTORY.md.

### CODE REVIEW

**Comment by NielXu** [comment]
And also, I did not check all the links in `DIRECTORY.md`, I only check some of them and they are all correct.

**Comment by cclauss** [comment]
Slick...  Well done.  A nice improvement would be sorting of the sub-directories & files.

**Comment by cclauss** [comment]
#890 demonstrates where to put it into __.travis.yml__ but then we need to commit the changed file to the repo under test.

**Comment by NielXu** [comment]
@cclauss Do you mean sorting files and directories by alphabetical order? I have done sorting the directories and it is not difficult to sort files as well. And thanks I will check out the .travis.yml

**Comment by cclauss** [comment]
Yes.  Sorting file directories by alphabetical order too.  Thanks much.

**Comment by poyea** [comment]
Thank you very much. I'll merge this. It's okay to improve the script or method based on this PR.

**Comment by poyea** [comment]
That's a lot of work. Thanks.

**Pull request merged**
