### PR TITLE
Improved Formatting and Style of Math Algos

### PR DESCRIPTION
**Pull request by PatOnTheBack**
I improved formatting and style to make PyLama happier.

Linters used:

- mccabe
- pep257
- pydocstyle
- pep8
- pycodestyle
- pyflakes
- pylint
- isort

### CODE REVIEW

**Comment by cclauss** [comment]
The recommendation of the Python Core Team is that you just run [__python/black__](https://github.com/python/black)

**Comment by fty48jj19** [comment]
e  vou adicionar mas codigos para empressa vc esta buscando pobremas para
mim nao vou seguir vc nao portanto por favor jamandei uma message avisando
seus abuso  vou expulsar vc estou te avisando para de fica mandano em algo
q nao te perteçe vc esta cendo abusado ja te falei sou o dono da empressa
nao vou tida ousadia nao ,

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sáb, 6 de jul de 2019 às 14:32, cclauss <notifications@github.com>
escreveu:

**Comment by fty48jj19** [comment]
a  github na manda na empressa nao vc precisa sabe disso github e penas um
fornecedor para mim de codigos pull  enterprase olha estou te avisando pare
de pertubar nao vou seguir vc nao por favor vopu apaga suas messsge eu vou
te expulsar nao vou volta atras nao estou te avisando nao e de hoje nao ,

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sáb, 6 de jul de 2019 às 14:38, joao tv <notifications@github.com>
escreveu:

**Comment by PatOnTheBack** [comment]
@cclauss Good to know, I installed black with pip.

**Comment by cclauss** [comment]
Can you resolve the conflicts?

**Comment by PatOnTheBack** [comment]
@cclauss I cannot resolve the conflicts. The conflicts are too complex to resolve on GitHub.com, but I cannot access the conflicts from `git` in the terminal, GitHub Desktop, or Atom. I have been troubleshooting for a while without finding a way to resolve the problem. I read [GitHub's docs](https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line).

`git status` shows no conflicts, so I don't know what I can try next.

**Comment by cclauss** [comment]
Conflicts can be a pain...  There is just one file that is conflicted so what I would do is go to the current master and copy and paste that content into the file which should have the effect of resolving the conflict.  Then once the PR lands, you can go back and fix that one file in a separate PR.

**Pull request merged**
