### PR TITLE
Hacktoberfest: add project euler for problem 357

### PR DESCRIPTION
**Pull request by Takosaga**
### **Describe your change:**

Find the sum of all positive integers n not exceeding 100 000 000
such that for every divisor d of n, d+n/d is prime.

Solution: Since all numbers are divisible by 1 than 1 plus the number
must be a prime, so possible prime generating integers are prime - 1.
d+30/d is actually the pairs of factors so adding the factor pairs and checking
if it is prime determines if the number is a prime generating integer.

3rd PR for Hactoberfest, not sure if fast enough but tried all day to optimize from 5 hour run time

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by xcodz-dot** [comment]
please make changes accordingly, so that the workflows does not fail

**Comment by dhruvmanila** [comment]
@cclauss Can you take a look at this? This user has given links in all function from where it got the code/idea from? I don't know whether this counts as plagiarism or not. Thanks if you do.

**Comment by cclauss** [comment]
If those sources publish under the MIT license as this repo does then I have no problem with properly sighted works.  However, if their licenses are significantly different then we should steer away from republishing them under a different license without written permission to do so.

**Comment by xcodz-dot** [comment]
For all the above functions:
* sieve_of_eratosthenes is from geekforgeeks (They have not mentioned any license on provided link but they have mentioned license on there [website](https://www.geeksforgeeks.org/licenses-of-softwares/))
* is_prime (They have not mentioned any license)
* get_divisors (They have not mentioned any license on provided link but they have mentioned license on there [website](https://www.geeksforgeeks.org/licenses-of-softwares/))

**Comment by dhruvmanila** [comment]
That seems like just a blog post to me.
@Takosaga Can you do some research on what type of license is used by the sources from which the code was taken?

By 'code was taken' I don't mean to say that you copy pasted the code but you took the inspiration from the given sources and incorporated into your own algorithm.

**Pull request closed without merging**
