### PR TITLE
Implement genetic algorithm for optimizing continuous functions

### LINKED ISSUE #11578: Genetic Algorithm for Function Optimization
### Feature description

This feature would introduce a new genetic algorithm-based approach to optimize mathematical functions. It would allow users to find the minimum or maximum values of continuous functions using genetic algorithms.

#### Key Components:
- **Target Function**: The user can define their own function to optimize, for example, \( f(x, y) = x^2 + y^2 \), or more complex functions.
- **Population Initialization**: Randomly generate initial solutions (chromosomes) within a defined search space.
- **Fitness Function**: Evaluate each chromosome's fitness based on how close the function value is to the desired optimum (minimization or maximization).
- **Selection**: Use selection methods like tournament selection or roulette wheel to pick parents for crossover based on their fitness scores.
- **Crossover**: Implement crossover strategies such as one-point, two-point, or uniform crossover to combine parent chromosomes into offspring.
- **Mutation**: Introduce random mutations to offspring to maintain diversity in the population and avoid local minima.
- **Termination Condition**: Allow the algorithm to stop after a set number of generations or when the improvement between generations is minimal.
  
This implementation would be useful for users needing a flexible and easy-to-use method for solving optimization problems in continuous spaces.

### PR DESCRIPTION
**Pull request by UTSAVS26**
### Describe your change:

- Added a flexible genetic algorithm that allows users to define their own target functions for optimization.
- Included features for population initialization, fitness evaluation, selection, crossover, and mutation.
- Example function provided for minimizing f(x, y) = x^2 + y^2.
- Configurable parameters for population size, mutation probability, and generations.

- **Add an algorithm?** ✅ Yes
- **Fix a bug or typo in an existing algorithm?** ❌ No
- **Add or change doctests?** ❌ No
- **Documentation change?** ❌ No

### Checklist:
- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Python files are placed inside an existing directory.
- [x] All filenames are in all lowercase characters with no spaces or dashes.
- [x] All functions and variable names follow Python naming conventions.
- [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
- [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
- [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
- [x] If this pull request resolves one or more open issues, then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

Fixes #11578

### CODE REVIEW

**Comment by night-spring** [comment]
remove extra spaces thats the problem

**Comment by UTSAVS26** [comment]
> remove extra spaces thats the problem

Thanks i will try to remove it and then rerun the jobs.

**Comment by UTSAVS26** [comment]
@night-spring can you guide me what extra spaces I need to remove as i am checking my code and based on that I can't able to find any extra whitespace. If possible for you can you help me for resolving the error and for merging this pr.

**Comment by night-spring** [comment]
> @night-spring can you guide me what extra spaces I need to remove as i am checking my code and based on that I can't able to find any extra whitespace. If possible for you can you help me for resolving the error and for merging this pr.

after end of every para of your code you may give two newlines. remove one.

**Comment by UTSAVS26** [comment]
> > @night-spring can you guide me what extra spaces I need to remove as i am checking my code and based on that I can't able to find any extra whitespace. If possible for you can you help me for resolving the error and for merging this pr.
> 
> after end of every para of your code you may give two newlines. remove one.

Para means functions right? 
Any other changes I need to do?

**Comment by UTSAVS26** [comment]
@night-spring and @cclauss what this error means? 

```
﻿2024-10-04T06:39:26.5187712Z ##[group]Run ruff check --output-format=github .
ruff check --output-format=github .
shell: /usr/bin/bash -e {0}
genetic_algorithm/genetic_algorithm_optimization.py:1:1: I001 Import block is un-sorted or un-formatted
Process completed with exit code 1.
``

**Comment by night-spring** [comment]
> @night-spring and @cclauss what this error means?
> 
> ```
> ﻿2024-10-04T06:39:26.5187712Z ##[group]Run ruff check --output-format=github .
> ruff check --output-format=github .
> shell: /usr/bin/bash -e {0}
> genetic_algorithm/genetic_algorithm_optimization.py:1:1: I001 Import block is un-sorted or un-formatted
> Process completed with exit code 1.
> ``
> ```

just fix format using copilot or any ai

**Comment by cclauss** [comment]
https://docs.astral.sh/ruff/rules/#isort-i
% `ruff check --select=I001 --fix genetic_algorithm/genetic_algorithm_optimization.py`
% `ruff rule I001`
# unsorted-imports (I001)

Derived from the **isort** linter.

Fix is sometimes available.

## What it does
De-duplicates, groups, and sorts imports based on the provided `isort` settings.

## Why is this bad?
Consistency is good. Use a common convention for imports to make your code
more readable and idiomatic.

## Example
```python
import pandas
import numpy as np
```

Use instead:
```python
import numpy as np
import pandas
```

**Comment by UTSAVS26** [comment]
@cclauss Thanks for the help, i will try to resolve the error. Thank you once again for giving your time.

**Comment by UTSAVS26** [comment]
@cclauss i have used these for the imports and use the same order

```python
import numpy as np
import random
from concurrent.futures import ThreadPoolExecutor
```

**Comment by cclauss** [comment]
PEP8 has been the Python style guide for a long time.  https://peps.python.org/pep-0008/#imports

`random` comes from the standard libraries so it should be imported ___before___ third-party libraries.

**Comment by UTSAVS26** [comment]
So I only need to remove the random module import statement right?

**Comment by UTSAVS26** [comment]
@cclauss can you please check my code as it is failing the test cases and don't know how to resolve, if possible for you. Thank you.

**Comment by cclauss** [comment]
There are three ___Details___ buttons to the right of the three failing tests below.  Click on each, read the error messages, and try to fix the code so those errors disappear.

**Comment by UTSAVS26** [comment]
Thank you @cclauss for your guidance, i will try to make necessary changes that you listed . 

Thank you once again for your time.

**Pull request closed without merging**
