### PR TITLE
Added euler_totient_function.py

### PR DESCRIPTION
**Pull request by k3x9**
Euler totient function returns the count of the relative prime of n lie between 1 to n.

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to [Wikipedia](https://en.wikipedia.org/wiki/Euler%27s_totient_function) or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by CaedenPH — CHANGES_REQUESTED** [review]
Could you link to a wikipedia page or some other relevant documentation about this algorithm?

**Comment by k3x9** [comment]
[Wikipedia](https://en.wikipedia.org/wiki/Euler%27s_totient_function)
I also mention this as a hyperlink in commit description.

**Comment by tianyizheng02** [comment]
We already have implementations of Euler's totient function in [maths/eulers_totient.py](https://github.com/TheAlgorithms/Python/blob/f8fe72dc378232107100acc1924fef31b1198124/maths/eulers_totient.py) and [maths/basic_maths.py](https://github.com/TheAlgorithms/Python/blob/f8fe72dc378232107100acc1924fef31b1198124/maths/basic_maths.py). Is this PR significantly distinct from these existing implementations?

**Comment by tianyizheng02** [comment]
Closing due to a lack of response and due to this repo already having implementations of Euler's totient function.

**Pull request closed without merging**
