### PR TITLE
Added solution for Project Euler problem 125

### PR DESCRIPTION
**Pull request by fpringle**
Name: Palindromic sums

The palindromic number 595 is interesting because it can be written as the sum of consecutive squares: 6^2 + 7^2 + 8^2 + 9^2 + 10^2 + 11^2 + 12^2.

There are exactly eleven palindromes below one-thousand that can be written as consecutive square sums, and the sum of these palindromes is 4164. Note that 1 = 0^2 + 1^2 has not been included as this problem is concerned with the squares of positive integers.

Find the sum of all the numbers less than 10^8 that are both palindromic and can be written as the sum of consecutive squares.

Reference: [https://projecteuler.net/problem=125](url)

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Hey, this looks perfect. 
This doesn't fix the issue, you can say this is a reference to it: `reference: #issue` 
I see you have submitted a lot of PR so please make the above changes to all of them.

**Review by dhruvmanila — APPROVED** [review]

**Comment by dhruvmanila** [comment]
Oh sorry to be ambiguous but I meant to put the reference part in the description and not in the title.

**Comment by fpringle** [comment]
Gotcha, will do

**Comment by dhruvmanila** [comment]
@fpringle Hey, if possible can you take a look at the problem 234's solution in the repo? Every problem has been fixed for #2786 except for that because it's asking for an `input` in every loop. Thanks if you do.

**Comment by fpringle** [comment]
> @fpringle Hey, if possible can you take a look at the problem 234's solution in the repo? Every problem has been fixed for #2786 except for that because it's asking for an `input` in every loop. Thanks if you do.

@dhruvmanila sure thing! At first glance it looks like someone's mixed up 2 different problems - the docs Tring description is problem 234 as required, but the code itself seems to be related to problem 230 (completely unrelated problem). My guess is that the original poster make a typo in their commit, and then some automated tool added the docstrings? Just a guess.
Beyond that, I can't really figure out what the algorithm itself is meant to do, nor why there are repeated uses of input(). Maybe there was only meant to be one initial stored input(), for entering the original A and B strings from problem 230?

**Comment by dhruvmanila** [comment]
As per the history of the file, it was submitted as a solution to problem 234 so it being a solution for problem 230 is quite unlikely. I will most likely open an issue regarding this to change or remove the solution. If you've solved this problem then you can open a PR but ***AFTER*** I open the issue.

I also see that you have submitted a lot of solutions which is really good but if possible can you slow down a bit, as the number of PRs is increasing a lot due to Hacktoberfest and one of our main maintainers is busy in some other work.

**Comment by fpringle** [comment]
> As per the history of the file, it was submitted as a solution to problem 234 so it being a solution for problem 230 is quite unlikely. I will most likely open an issue regarding this to change or remove the solution. If you've solved this problem then you can open a PR but ***AFTER*** I open the issue.

Sure thing. Please let me know when you open the new issue. 

> I also see that you have submitted a lot of solutions which is really good but if possible can you slow down a bit, as the number of PRs is increasing a lot due to Hacktoberfest and one of our main maintainers is busy in some other work.

Of course, sorry for the increased workload! I'll be away from a computer for the next 4 or 5 days anyway.

**Pull request merged**
