### PR TITLE
Travis integration (Add .travis.yml)

### PR DESCRIPTION
**Pull request by SergeyTsaplin**
Add travis-ci integration (Need to be additionally configured via https://travis-ci.org)

### CODE REVIEW

**Comment by SergeyTsaplin** [comment]
Example of build result https://travis-ci.org/SergeyTsaplin/Python

**Comment by H-Darji** [comment]
@SergeyTsaplin 
Hi, I've read some documents about **travis-ci**, but I'm still not able to understand that what it actually do.
Can you please explain it (of course in short)?

**Comment by SergeyTsaplin** [comment]
travis-ci is regular continuous integration service. It provides test runnings on all required platforms on each commit and pull requests. So you always understand if your code is broken before you merge it to master. Also there are some extra abilities for example test coverage, linters runnings etc

**Comment by H-Darji** [comment]
@SergeyTsaplin 
Last query, How it works?

**Comment by SergeyTsaplin** [comment]
@H-Darji githab call travis' webhook on each pull request, merge or push, travis fetches the changes and runs the commands declared in .travis-ci.yml file

**Comment by H-Darji** [comment]
@SergeyTsaplin As you know, travis requires permission from owners of the organization to access repositories, I've requested owners for this. Once they grants access, I'll merge this.

**Comment by SergeyTsaplin** [comment]
@H-Darji Of course you have to grant access to reposito

**Pull request merged**
