### PR TITLE
Simplify climbing stairs and use constant memory

### PR DESCRIPTION
**Pull request by giladwo**
### Describe your change:
Improve current solution to the climbing stairs problem by reducing memory footprint.

Just to be sure I haven't broken the original solution (new version is `climb_stairs_new` in the following test snippet):
```python
>>> from hypothesis import given
>>> from hypothesis.strategies import integers
>>> 
>>> @given(integers(min_value=1, max_value=200))
>>> def test_fast(n: int) -> None:
>>>     assert climb_stairs(n) == climb_stairs_new(n)
>>> 
>>> test_fast()
```

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
Please create https://docs.python.org/3/library/timeit.html benchmarks to prove that the proposed algorithm is as fast or faster than the current implementation.

There are plenty of example benchmarks in this repo https://github.com/TheAlgorithms/Python/search?q=timeit

**Comment by giladwo** [comment]
> There are plenty of example benchmarks in this repo https://github.com/TheAlgorithms/Python/search?q=timeit

Creating a benchmark like these requires multiple implementations and I don't see much point in keeping the original, so I created a throwaway [benchmark.py](https://github.com/TheAlgorithms/Python/files/9705372/benchmark.py.txt), the results of which are:
```bash
$ python benchmark.py
     input       |     original     |       new        |      ratio
               2 |           0.4845 |            0.286 |           0.5904
               5 |           0.7624 |           0.3769 |           0.4943
               8 |            1.041 |           0.4777 |           0.4588
              11 |            1.294 |           0.5749 |           0.4442
              14 |            1.638 |           0.6826 |           0.4167
              17 |             1.89 |           0.8062 |           0.4266
              20 |            2.163 |           0.9422 |           0.4356
              23 |             2.43 |            1.047 |           0.4311
              26 |            2.743 |            1.196 |           0.4361
              29 |            3.018 |            1.287 |           0.4264
              32 |            3.286 |            1.407 |           0.4282
              35 |            3.542 |            1.517 |           0.4284
              38 |            3.823 |            1.632 |            0.427
              41 |            4.115 |            1.749 |            0.425
              44 |            4.385 |            1.866 |           0.4256
              47 |            4.657 |            2.008 |           0.4312
              50 |            4.924 |            2.138 |           0.4343
```

It can be easily adapted into `dynamic_programming/climbing_stairs.py`, but that would obviously be a much bigger diff.

Let me know what you'd like to have included in the PR :)

**Comment by giladwo** [comment]
Hi @cclauss, looking forward to your answer here.

**Review by cclauss — APPROVED** [review]
AWESOME!!  Pythonic and fast!

**Pull request merged**
