### PR TITLE
Add __init__.py files in all the directories

### PR DESCRIPTION
**Pull request by dhruvmanila**
Fixes: #2502 

**Please check if there's any directory where it's not needed.**

### **Describe your change:**

* [x] Fix a bug or typo in an existing algorithm?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
That was a disaster! Let me see what's going on in there.

**Comment by dhruvmanila** [comment]
@cclauss Ok, I found the reason for all the errors. 
The errors are happening because of how namespace packages work. As we're adding all the `__init__.py` files, we're basically creating sub-packages in our parent directory (`Python/`). What this means is that if we want to use `import` in a file inside a sub-directory, then we need to use absolute import from our parent directory. 

For example:
In `ciphers/affine_cipher.py`, instead of `import cryptomath_module as cryptomath` we will have to do `import ciphers.cryptomath_module as cryptomath`

This doesn't seem like a viable solution so I will take a further look into this.

**Comment by dhruvmanila** [comment]
I don't think there's any other choice if we're adding the `__init__.py` files.
It also seems that in some of the files we're using relative imports and in others we're using absolute. It would be better, in the long run, to stick with one. For more information on relative imports: https://docs.python.org/3/reference/import.html#package-relative-imports

If we're importing a module from the current directory we can use either of the following:
- `from parent.module import function` 
- `import .module`. 

Remember that a `module` is just another Python file.

**Comment by dhruvmanila** [comment]
I fixed all the imports on my local copy and it fixes everything up.
Shall I make a PR to fix the imports? @cclauss

**Review by cclauss — APPROVED** [review]

**Comment by cclauss** [comment]
Yes. please.  Just the changes to get Travis CI to be green again.

**Comment by AayushDadhich** [comment]
Typo

in data structures directory folder is named as trie instead of tree

**Comment by cclauss** [comment]
@AayushDadhich https://en.wikipedia.org/wiki/Trie

**Comment by annsleyshakeah66** [comment]
https://amzn.to/3wG6XcY
https://amzn.to/3eLecL2
https://amzn.to/38c7OZ2
https://amzn.to/3dG5sVl
https://amzn.to/3BcOacw
https://amzn.to/3jJ0Lhp
https://amzn.to/2RgUPQY
https://amzn.to/2TzhM31
https://amzn.to/3jQ2guj
https://amzn.to/3yr1nfB
https://amzn.to/3jkJn1V
https://amzn.to/3ks6V4b

**Comment by kmkurumi** [comment]
annsleyshakeah66 ***@***.***>於 2021年9月7日 週二，下午6:58寫道：

**Pull request merged**
