### PR TITLE
Adding doctests into LDA algorithm

### LINKED ISSUE #1620: Implementation of doctests in linear discriminant analysis
Adding linear discriminant analysis in test list

### PR DESCRIPTION
**Pull request by EverLookNeverSee**
I have fixed #1620 by adding doctest into LDA functions

### CODE REVIEW

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/Travis_CI_tests_are_failing.md

**Comment by cclauss** [comment]
This PR touches four different files in three different directories.  Each PR should only touch one file.

**Comment by EverLookNeverSee** [comment]
Actually , i changed one file(Linear Discriminant analysis) but 3 other files has added automatically to my PR after i did git pull --rebase upsteram master

**Comment by cclauss** [comment]
`git checkout master ; git pull --rebase upstream master ; git push origin master ; git branch`

then go back to your branch and

`git fetch upstream ; git merge upstream/master ; git push --force origin`

**Comment by EverLookNeverSee** [comment]
Hey @cclauss , What should i do now?

**Comment by EverLookNeverSee** [comment]
@cclauss Thanks for merging.

**Pull request merged**
