### PR TITLE
merge double_factorial

### PR DESCRIPTION
**Pull request by AVAniketh0905**
### Describe your change:

Contributes to #8098 

- Deleted `maths/double_factorial_iterative.py` and `maths/double_factorial_irecursive.py`. 
- Created `maths/double_factorial.py`. Which inlcudes the above 2 implementations.
- Changed the `DIRECTORY.md` to include only `double_factorial.py` file.

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by AVAniketh0905** [comment]
I have changed a doctest to satisfy for ruff error.

**Review by tianyizheng02 — CHANGES_REQUESTED** [review]
1. Please do not edit DIRECTORY.md. This file is auto-generated with a script.
2. Please keep the original doctest that you changed. Ruff was failing on that line because the line was too long, not because the test was incorrect.

**Comment by AVAniketh0905** [comment]
> 1. Please do not edit DIRECTORY.md. This file is auto-generated with a script.
> 2. Please keep the original doctest that you changed. Ruff was failing on that line because the line was too long, not because the test was incorrect.

@tianyizheng02 Sorry I didnt know about `DIRECTORY.md`. I have reverted my changes. Now can you check?

**Comment by tianyizheng02** [comment]
@AVAniketh0905 Please fix the failing ruff errors. Some lines are too long.

**Comment by AVAniketh0905** [comment]
> @AVAniketh0905 Please fix the failing ruff errors. Some lines are too long.

The current test case is indeed exceeding the ruff limit. So can I change the test case?

```python
# Old Test Case
all(double_factorial_iterative(i) == math.prod(range(i, 0, -2)) for i in range(20))
True

# New Test Case
double_factorial_iterative(5) == math.prod(range(5, 0, -2))
True
```
If you confirm ill do the necessary changes...
Srry this is taking too long...

**Comment by tianyizheng02** [comment]
No, I already said not to change the test case. Please break that test case into multiple lines if it's too long.

**Comment by AVAniketh0905** [comment]
> No, I already said not to change the test case. Please break that test case into multiple lines if it's too long.

yes sorry i didnt know we could do that.

**Comment by tianyizheng02** [comment]
I modified your PR description to say "Contributes to..." rather than "Fixes..." because the latter will automatically close the issue. This PR helps with the issue but doesn't fix it completely.

**Review by tianyizheng02 — APPROVED** [review]

**Comment by AVAniketh0905** [comment]
> I modified your PR description to say "Contributes to..." rather than "Fixes..." because the latter will automatically close the issue. This PR helps with the issue but doesn't fix it completely.

I understand. Thank you for taking your time reviewing this PR.

**Pull request merged**
