### PR TITLE
Added Graph algorithms

### PR DESCRIPTION
**Pull request by imshubham27**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by xcodz-dot — CHANGES_REQUESTED** [review]
Please change you Driver Code to be contained in a `if __name__ == '__main__'` statement

**Comment by imshubham27** [comment]
> ## Travis tests have failed
> Hey @imshubham27,
> Please read the following log in order to understand the failure reason.
> It'll be awesome if you fix what's wrong and commit the changes.
> 
> ###### TravisBuddy Request Identifier: 34552290-15e9-11eb-94fa-edf6748ec8ed

Yes Updated the codes, just check now

**Comment by xcodz-dot** [comment]
@imshubham27, please wait. I will get you the solution for the automated tests

**Comment by xcodz-dot** [comment]
This PR might be closed, reasons:
* Multiple algorithms in single PR

Fixes:
* Create separate PRs for different files.

@imshubham27, please follow the above steps

**Comment by imshubham27** [comment]
> This PR might be closed, reasons:
> 
> * Multiple algorithms in single PR
> 
> Fixes:
> 
> * Create separate PRs for different files.
> 
> @imshubham27, please follow the above steps

yes attaching gimme a minute

**Pull request closed without merging**
