### PR TITLE
Added vertex-limited network flow reduction

### PR DESCRIPTION
**Pull request by iiloni-umd**
### Describe your change:

Implemented a reduction algorithm for flow networks that have capacities on vertices instead of edges. This reduction converts such a flow network into a standard flow network for which the Ford-Fulkerson algorithm can compute a max-flow.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by iiloni-umd** [comment]
It appears that ruff is catching issues from files that I have not modified. I'm not sure what I need to do to get ruff to pass.

**Comment by tianyizheng02** [comment]
> It appears that ruff is catching issues from files that I have not modified. I'm not sure what I need to do to get ruff to pass.

Other people have been having that issue with their PRs too. Try running `ruff .` and then `ruff --fix .`

**Comment by iiloni-umd** [comment]
These are the results from running `ruff --fix .`
image

I did not contribute to the `maths` directory, is there something I can do to make this PR pass or would I need to modify those other files?

**Comment by tianyizheng02** [comment]
Not sure. It also seems that whether ruff identifies these errors is system-dependent: the errors appear when GitHub Actions runs ruff on my fork but not when I run ruff on my local git repo. @cclauss any ideas on how @iiloni-umd and others can get rid of these ruff errors?

**Comment by tianyizheng02** [comment]
@iiloni-umd The ruff issue has been fixed in #8732. Update your branch and ruff should pass this time

**Comment by tianyizheng02** [comment]
@iiloni-umd Could you rebase your branch to bring in the latest commits? The ruff errors have been fixed

**Comment by tianyizheng02** [comment]
Closing due to lack of response. In addition, please read the contributing guidelines to make sure that your code follows our requirements

**Pull request closed without merging**
