### PR TITLE
Fixes black failures from Previous PR

### PR DESCRIPTION
**Pull request by onlinejudge95**
### **Describe your change:**

* Fixes failing `black` checks from #1740  
* Fixes [Testing equality to None](https://lgtm.com/projects/g/TheAlgorithms/Python/alerts?mode=tree&ruleFocus=7900090) alerts on LGTM

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
You might try changing this line:
https://github.com/TheAlgorithms/Python/blob/master/.travis.yml#L9
```
Change: flake8 . --count --exit-zero --max-line-length=127 --statistics
    To: flake8 . --count --max-complexity=10 --max-line-length=88 --statistics
```
This will uncover a bunch of issues to be fixed.

**Comment by onlinejudge95** [comment]
@cclauss there are approx 3k lines to ponder :p let's tackle it in a diff PR?

**Comment by cclauss** [comment]
Alright, how about changing that line to:
```
flake8 . --count --ignore=E2,E302,E4,E7,W29 --max-complexity=10 --max-line-length=127 --statistics
```

**Comment by onlinejudge95** [comment]
@cclauss again the count is not bearable to handle in this PR also since many files need to be changed, can you raise an issue and we can maybe track it in a separate PR?

**Pull request merged**
