### PR TITLE
Add GitHub Action mypy.yml to mypy --ignore-missing-imports

### PR DESCRIPTION
**Pull request by cclauss**
### **Describe your change:**

Add testing for  #4052 by running `mypy --ignore-missing-imports` on all directories that currently pass [mypy](https://mypy.readthedocs.io) tests.

I tried to add `mypy` testing to our pre-commits but #4272 was more pain than it was worth.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?
* [x] Add GitHub Action mypy.yml

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
The thing with `mypy` is it needs the additional dependencies for it to able to carry out the checks properly. This means we should add the job to our existing CI which already installs the dependencies.

**Comment by cclauss** [comment]
# --ignore-missing-imports

**Comment by dhruvmanila** [comment]
The flag `--ignore-missing-imports` is only for the imports whose types are missing. `mypy` usually complains if the type hints are missing from any imported module. This flag will make the type hint for those modules as `any`.

For the modules which do contain type hints, they will be used by `mypy` to do the validation even if this flag was passed.

**Comment by cclauss** [comment]
Closing in favor of #4276

**Pull request closed without merging**
