### PR TITLE
Add pytest-cov

### PR DESCRIPTION
**Pull request by sirex**
Also added coverage report in .travis.yml file.

### CODE REVIEW

**Comment by cclauss** [comment]
Nice!!  Thanks!  Is there a way to get a __sorted__ list showing those files with no tests or with little test coverage?

**Comment by sirex** [comment]
> Nice!! Thanks! Is there a way to get a **sorted** list showing those files with no tests or with little test coverage?

By default it is sorted by file name, bet here are other options:

> sort (string, default “Name”): Sort the text report by the named column. Allowed values are “Name”, “Stmts”, “Miss”, “Branch”, “BrPart”, or “Cover”.

Changed sorting to `Miss` (by missing statements).

**Comment by cclauss** [comment]
Can we do a reverse sort on cover?  That would put the 5% near the top of the list and the 95% near the bottom.  This is super cool.  Thanks for doing it!

**Comment by sirex** [comment]
> Can we do a reverse sort on cover? That would put the 5% test coverage near the top of the list and the 95% near the bottom. This is super cool. Thanks for doing it!

I'm not sure, but I guess reverse is not supported. Documentation lists these sort options:

- Name
- Stmts
- Miss
- Branch
- BrPart
- Cover

**Pull request merged**
