### PR TITLE
Fix style of the first ten solutions for Project Euler

### PR DESCRIPTION
**Pull request by darkstar**
### **Describe your change:**
This changes the style of the first 10 Project Euler solutions akin to the changes requested in #2875 and #2880:

- Unify the header docstring, and add reference URLs to Wikipedia or similar
- Fix docstrings to be properly multilined
- Add newlines where appropriate
- Add doctests where they were missing
- Remove doctests that test for the correct solution
- Remove redundant (trivial) comments
- fix obvious spelling or grammar mistakes in comments and exception messages
- Fix line endings to be UNIX. This makes two of the files seem to have changed completely
- **no functional changes in any of the solutions were done (except for the spelling fixes mentioned above)**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

@dhruvmanila Please comment if you have any input

### CODE REVIEW

**Comment by darkstar** [comment]
Okay, I had to remove the doctests from `problem_08/sol3.py` since they apparently give different results on Linux than they give on Windows. I literally copy/pasted what python gave me into the doctest, but travis seems to insist that the result is wrong...

Also I had to remove the prime test for 0 (which is not prime) since many solutions didn't properly check for that and I didn't want to change the implementation

**Comment by dhruvmanila** [comment]
We really appreciate you doing this but the guidelines for maintaining consistency in Project Euler are still in progress. So I will keep this PR `on hold` and convert to draft. In a few days once that guideline is out you can read it through and make the necessary changes where applicable.

**Review by dhruvmanila — COMMENTED** [review]
### Announcement:

@darkstar

*This message is sent to all pull requests which are **OPEN, NOT MERGED, not containing 'wontfix' label and contains 'Project Euler' or 'Project' or 'Euler' (case doesn't matter) in their title**. If this message doesn't apply to your pull request, please ignore this.*

### Message:

This is to notify all the users submitting a pull request for the Project Euler solution that the [README.md](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) file has been updated with all the style requirements necessary for the directory and solution files. ***Please read through it and make all the necessary changes required to your submission.***

**Comment by darkstar** [comment]
I fixed all issues that were not conforming to the styleguide.

This is still only for the first 10 projects but once this gets committed I'll gladly do the rest too

There is still the issue of the broken main function though, I'm not sure how you want it fixed as the bug is in the style guide's template. But once that is fixed in the guide, I'll incorporate it into the PR

**Comment by dhruvmanila** [comment]
Can you specify what the bug is in the template?

**Comment by darkstar** [comment]
> Can you specify what the bug is in the template?

I posted it here: https://github.com/TheAlgorithms/Python/commit/2d7e08ef8324867f47f381cdc800ee00f6d77be0#comments

This code does not work:
````
if __name__ == "__main__":
    print(f"{solution() = }")
````

it gives a syntax error when the file is run through python:

````
  File "<fstring>", line 1
    (solution() = )
                ^
SyntaxError: invalid syntax
````

But I left it in anyway since it might just be my setup (Windows-related, python 3.6.3 related, whatever)

**Comment by dhruvmanila** [comment]
That might be the version problem. Which version of Python are you running?
```console
$ python -V
```

**Review by dhruvmanila — APPROVED** [review]
This is awesome! Thanks for doing this :)

**Comment by darkstar** [comment]
> That might be the version problem. Which version of Python are you running?
> 
> ```
> $ python -V
> ```
> 
> This repository assumes you're on the latest version of Python.

3.6.3

I'll be updating to see if that helps. I thought 3.6 was recent enough, but now I see we're already at 3.9, so yeah, probably a problem on my side

**Pull request merged**
