### PR TITLE
Added solution for Project Euler problem 183

### PR DESCRIPTION
**Pull request by prakhargurunani**
### **Describe your change:**
Name: Maximum product of parts

Problem Statement: _Let N be a positive integer and let N be split into k equal parts, r = N/k, so that 
N = r + r + ... + r. Let P be the product of these parts, P = r × r × ... × r = rk. 
For example, if 11 is split into five equal parts, 11 = 2.2 + 2.2 + 2.2 + 2.2 + 2.2, 
then P = 2.25 = 51.53632. Let M(N) = Pmax for a given value of N. It turns out that 
the maximum for N = 11 is found by splitting eleven into four equal parts which leads 
to Pmax = (11/4)4; that is, M(11) = 14641/256 = 57.19140625, which is a terminating decimal.
However, for N = 8 the maximum is achieved by splitting it into three equal parts, 
so M(8) = 512/27, which is a non-terminating decimal. Let D(N) = N if M(N) is a non-terminating 
decimal and D(N) = -N if M(N) is a terminating decimal. For example, ∑ D(N) for 5 ≤ N ≤ 100 is 2438. 
Find ∑ D(N) for 5 ≤ N ≤ 10000._

Reference: https://projecteuler.net/problem=183

reference: #2695

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by prakhargurunani** [comment]
Dont know why `pre-commit` is failing..

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/issues/2510#issuecomment-701540969

**Comment by sarthaka1310** [comment]
Please read these:
* https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#other-standard-while-submitting-your-work
* https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#coding-style

**Review by dhruvmanila — COMMENTED** [review]
### Announcement:

@prakhargurunani

*This message is sent to all pull requests which are **OPEN, NOT MERGED, not containing 'wontfix' label and contains 'Project Euler' or 'Project' or 'Euler' (case doesn't matter) in their title**. If this message doesn't apply to your pull request, please ignore this.*

### Message:

This is to notify all the users submitting a pull request for the Project Euler solution that the [README.md](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) file has been updated with all the style requirements necessary for the directory and solution files. ***Please read through it and make all the necessary changes required to your submission.***

**Comment by prakhargurunani** [comment]
@Kush1101 Done ! All guidelines meet successfully 😊 .

**Comment by dhruvmanila** [comment]
Do not change the `.pre-commit-config.yaml` file.
Your solution doesn't comply with the [solution guidelines](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md). Please read it properly. It's quite simple.

**Comment by prakhargurunani** [comment]
@dhruvmanila done ! I don't know it mistakenly happened as I had switched to a different code editor.

**Comment by prakhargurunani** [comment]
@dhruvmanila Merge conflicts resolved. What are the missing solution guidelines which have not been incorporated ?

**Comment by dhruvmanila** [comment]
Read the guideline and you will be able to deduce. Take a look at point 5.

**Pull request closed without merging**
