### PR TITLE
Update atbash cipher (doc, doctest, performance)

### PR DESCRIPTION
**Pull request by mateuszz0000**
### **Describe your change:**
Added update for atbash cipher:
- doctests,
- type hints
- little performance improvement

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by mateuszz0000** [comment]
With small string speed is not visible - even worse. I've tried with 4 000 000 characters length and current implementation is little bit faster (from 3.2 sec -> 2.2 - 2.4 sec). That's why I wrote "little" in PR description :) 

I can put some performance tests I made If you want :)

**Comment by mateuszz0000** [comment]
> ```
> Running performance benchmarks...
> > atbash_slow() 18.921338292999998 seconds
> >      atbash() 16.922152821999997 seconds
> ```
> 
> How could `atbash()` be modified to be much faster?

I thought about modulo operations and remove completely searching characters in `ascii_letters`. If statement in list comprehensions slowing down too. For now I don't have idea but I know it's possible :)

**Comment by cclauss** [comment]
Would it help if we moved the definition of `letters` and `letters_reversed` outside the function?

**Comment by mateuszz0000** [comment]
> Would it help if we moved the definition of `letters` and `letters_reversed` outside the function?

Perhaps but insignifficant, these strings are too small. The bottleneck is here:
`.. letters.index(c) .. if c in letters else c. ..`

**Pull request merged**
