### PR TITLE
Optimization shell sort

### PR DESCRIPTION
**Pull request by shellhub**
### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by poyea — COMMENTED** [review]
It doesn't quite seem to me that this is an optimization. May I know the reasoning behind this?

**Comment by shellhub** [comment]
> It doesn't quite seem to me that this is an optimization. May I know the reasoning behind this?

If array is sorted already. It's no need to execute assignment statement.

**Comment by poyea** [comment]
@shellhub I've done a simple benchmark for this on random and sorted lists. I'd say they're similar in performance... Can you illustrate with an example in the test & comment: like
```python
# consider test case [xxx]
```

**Review by cclauss — CHANGES_REQUESTED** [review]
@shellhub Please create a timeit (or similar) benchmark that proves that the proposed change delivers measurable performance improvement.

**Comment by shellhub** [comment]
``` python
def shell_sort_slow(collection):
    gaps = [701, 301, 132, 57, 23, 10, 4, 1]
    for gap in gaps:
        for i in range(gap, len(collection)):
            insert_value = collection[i]
            j = i
            while j >= gap and collection[j - gap] > insert_value:
                collection[j] = collection[j - gap]
                j -= gap
            collection[j] = insert_value
    return collection


def shell_sort_faster(collection):
    gaps = [701, 301, 132, 57, 23, 10, 4, 1]
    for gap in gaps:
        for i in range(gap, len(collection)):
            insert_value = collection[i]
            j = i
            while j >= gap and collection[j - gap] > insert_value:
                collection[j] = collection[j - gap]
                j -= gap
            if j != i:
                collection[j] = insert_value
    return collection


def benchmark():
    from timeit import timeit
    print("shell_sort_slow", timeit("z.shell_sort_slow(z.nums)", setup="import __main__ as z"))
    print("shell_sort_faster", timeit("z.shell_sort_faster(z.nums)", setup="import __main__ as z"))


if __name__ == "__main__":
    nums = [i for i in range(1, 1000)]
    benchmark()

```
output:
```
('shell_sort_slow', 16.11249089241028)
('shell_sort_faster', 13.815173864364624)
```

@poyea @cclauss

**Comment by shellhub** [comment]
Please review this PR. Thanks @poyea @cclauss @dhruvmanila @mateuszz0000

**Review by cclauss — APPROVED** [review]

**Pull request merged**
