### PR TITLE
Create binary_search_alphabet.py

### PR DESCRIPTION
**Pull request by OfficialAhmed**
Binary search algorithm implementation to locate an alphabet in a list using the ASCII system

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.

### CODE REVIEW

**Review by IDEKENTERPRISES — APPROVED** [review]

**Comment by poyea** [comment]
This search can be done with https://github.com/TheAlgorithms/Python/blob/master/searches/binary_search.py - isn't it? You might want to add test cases to existing algorithms

**Comment by OfficialAhmed** [comment]
> This search can be done with https://github.com/TheAlgorithms/Python/blob/master/searches/binary_search.py - isn't it? You might want to add test cases to existing algorithms

No, because binary_search.py uses int type as inputs and return the index(searching for int in list). The binary_search_alphabet.py takes a list of alphabets and return the index occurrence(searching for a letter). The first one can be used here but needs to be tweaked to accepts strings etc.

**Comment by s39674** [comment]
I think @poyea meant that you are not implementing anything new if you're just using `ord()`, and that can be done with https://github.com/TheAlgorithms/Python/blob/master/searches/binary_search.py.

**Comment by OfficialAhmed** [comment]
@s39674 that’s correct

**Pull request closed without merging**
