### PR TITLE
Added Project Euler Problem 92: Fixes TheAlgorithms#2695

### PR DESCRIPTION
**Pull request by amy-graham-js**
### **Describe your change:**
I have added a solution to Project Euler Problem 92: Square digit chains.
It prints the solution for the default limit 10,000,000.

I ran doctests locally, black and flake8 and they have all passed.

I would like this to contribute towards hacktoberfest please. Thanks

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by sarthaka1310** [comment]
You are not supposed to edit the Directory: https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#other-standard-while-submitting-your-work

**Comment by amy-graham-js** [comment]
> You are not supposed to edit the Directory: https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md#other-standard-while-submitting-your-work

Thanks @sarthaka1310!

**Review by dhruvmanila — COMMENTED** [review]
### Announcement:

@amy-graham-js

*This message is sent to all pull requests which are **OPEN, NOT MERGED, not containing 'wontfix' label and contains 'Project Euler' or 'Project' or 'Euler' (case doesn't matter) in their title**. If this message doesn't apply to your pull request, please ignore this.*

### Message:

This is to notify all the users submitting a pull request for the Project Euler solution that the [README.md](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) file has been updated with all the style requirements necessary for the directory and solution files. ***Please read through it and make all the necessary changes required to your submission.***

**Comment by dhruvmanila** [comment]
Your code is taking 2 minutes to run: https://travis-ci.com/github/TheAlgorithms/Python/jobs/400631277#L246
You need to optimize it to bring it down. Try to think about some concepts which you can apply here as brute force algorithms are way too slow.

```console
$ time python project_euler/problem_092/sol1.py
solution() = 8581146

real    2m8.729s
user    2m7.627s
sys     0m0.404s
```

**Comment by dhruvmanila** [comment]
Also, it was not you who updated the directory, it was the automated script which does that whenever there's a new algorithm in the repository. So don't edit the directory ever. If you did it, then close this PR and open a new one with the optimization in place.

**Comment by amy-graham-js** [comment]
@dhruvmanila thanks for your help, I have created a new PR here https://github.com/TheAlgorithms/Python/pull/3509
I decided to add a the chain of numbers to a list until the squared numbers in the chain reach 89 or 1. Then I update a dictionary with all of these numbers in the chain and the final number. In this way the algorithm should be more performant because if any sum of squares is already in the dictionary, then it will break the while loop as we already know what it will end up as. Thanks for helping me to reconsider this problem :)

**Comment by dhruvmanila** [comment]
Closing this PR as the user made the changes and opened another PR as requested.

**Pull request closed without merging**
