### PR TITLE
Merge pull request #1 from TheAlgorithms/master

### PR DESCRIPTION
**Pull request by jiveshs98**
Updating repo

### CODE REVIEW

**Comment by cclauss** [comment]
Why does this keep happening?  Why not just clone or resync the repo?

**Comment by jiveshs98** [comment]
Actually, I wanted to know if there is a way to resync the repo without using git bash. I have tried, but in vain. Please tell me a solution.

**Comment by cclauss** [comment]
The first three commands:
https://devguide.python.org/gitbootcamp/#syncing-with-upstream

**Comment by jiveshs98** [comment]
Thank you!!

**Pull request closed without merging**
