### PR TITLE
random anime character python script

### PR DESCRIPTION
**Pull request by ashish-patwal**
### ** A small script that fetches a random anime character info along with saving an image of it in the same directory**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by ashish-patwal** [comment]
ptal @cclauss

**Comment by cclauss** [comment]
Tests are failing and requests for function tests are still unanswered.

**Comment by ASHIKSAR** [comment]
মজা করি নাই

**Comment by ashish-patwal** [comment]
> Tests are failing and requests for function tests are still unanswered.
> 
> `black web_programming/random_anime_character.py` # See CONTRIBUTING.md

**Comment by ashish-patwal** [comment]
> Tests are failing and requests for function tests are still unanswered.
> 
> `black web_programming/random_anime_character.py` # See CONTRIBUTING.md

hey @cclauss , i see your concern . But in this certain script i cannot write doctests as i have nothing to assert here as correct results or response to some doctest . It is because the script is generating a random string and random photo which i cannot pre assert beforehand .

**Comment by cclauss** [comment]
Please black format.

**Pull request closed without merging**
