### PR TITLE
Update and_gate.py

### PR DESCRIPTION
**Pull request by rohan472000**
addressing issue #8656 by calling `test_and_gate()` , ensuring that all the assertions are verified before the actual output is printed.

### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by rohan472000** [comment]
@cclauss kindly review it.

**Comment by rohan472000** [comment]
@cclauss it's been more than a week of this PR, kindly review it if any change needed then suggest.

**Review by CaedenPH — APPROVED** [review]
Very minor change, it will get merged whenever cclauss or another member of thealgorithms has a chance - No need to pester

**Comment by rohan472000** [comment]
Yeah ..it was raised in an issue that's why I tried to fix it.

**Review by ChrisO345 — APPROVED** [review]

**Pull request merged**
