### PR TITLE
Add typehints to blockchain

### PR DESCRIPTION
**Pull request by jenia90**
#2510 and #2128 Added type hints to the blockchain algorithms functions.

* [ ] Add an algorithm?
* [X] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by jenia90** [comment]
@poyea hey, I'm not sure I should address you here, but can you or someone else review and tag this PR for hacktoberfest? Thanks a lot in advance! :)

**Review by 53jk1 — APPROVED** [review]

**Comment by jenia90** [comment]
@53jk1 thanks for the review! Can this be tagged for hacktoberfest?

**Comment by 53jk1** [comment]
I am not authorized to add tags. :smile: 
Peace :heart:

**Review by poyea — APPROVED** [review]

**Comment by poyea** [comment]
Thank you for your pull request!🤩 And sorry for the delay.

**Comment by jenia90** [comment]
Hey @poyea, Idk if it's gonna help my last PRfor hacktoberfest, but can you please add the hacktoberfest-accepted label? Thank you 😊

**Pull request merged**
