### PR TITLE
Add typing to data_structures/queue/queue_on_pseudo_stack.py

### PR DESCRIPTION
**Pull request by saksham-chawla**
hacktoberfest

### Describe your change:

* [] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by CaedenPH — CHANGES_REQUESTED** [review]
This isn't really adding typing, this is just indicating that these functions return a type.
Please be specific with the types, `-> Any` doesn't tell us anything about the function return type.

**Comment by saksham-chawla** [comment]
>

**Comment by saksham-chawla** [comment]
> This isn't really adding typing, this is just indicating that these functions return a type. Please be specific with the types, `-> Any` doesn't tell us anything about the function return type.

**Comment by saksham-chawla** [comment]
> This isn't really adding typing, this is just indicating that these functions return a type. Please be specific with the types, `-> Any` doesn't tell us anything about the function return type.

Actually it tells that the function is generic and not limited to any particular primitive

**Comment by CaedenPH** [comment]
> > This isn't really adding typing, this is just indicating that these functions return a type. Please be specific with the types, `-> Any` doesn't tell us anything about the function return type.
> 
> Actually it tells that the function is generic and not limited to any particular primitive. @CaedenPH

What does the `get` method return?

**Comment by saksham-chawla** [comment]
> > > This isn't really adding typing, this is just indicating that these functions return a type. Please be specific with the types, `-> Any` doesn't tell us anything about the function return type.
> > 
> > 
> > Actually it tells that the function is generic and not limited to any particular primitive. @CaedenPH
> 
> What does the `get` method return?

An item from the stack. which could be of Any type here.

**Comment by CaedenPH** [comment]
> > > > This isn't really adding typing, this is just indicating that these functions return a type. Please be specific with the types, `-> Any` doesn't tell us anything about the function return type.
> > > 
> > > 
> > > Actually it tells that the function is generic and not limited to any particular primitive. @CaedenPH
> > 
> > 
> > What does the `get` method return?
> 
> An item from the structure. which could be of Any type here.

I see, I guess that is fine

**Comment by saksham-chawla** [comment]
@CaedenPH can you please review? i am unable to open new PRs because of pending review: https://github.com/TheAlgorithms/Python/pull/7043

**Review by CaedenPH — APPROVED** [review]

**Comment by saksham-chawla** [comment]
@CaedenPH is your review not sufficient to merge? do we need extra reviews?

**Comment by saksham-chawla** [comment]
requesting review if someone can please take a look. thanks in advance!

**Review by cclauss — APPROVED** [review]

**Comment by cclauss** [comment]
Thanks!!!

**Comment by saksham-chawla** [comment]
@cclauss can you please add hacktoberfest-accepted label to this as well? thanks in advance! :)

**Pull request merged**
