### PR TITLE
Delete euclidean_gcd.py

### PR DESCRIPTION
**Pull request by HighnessAtharva**
[workerB](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=qnbyUTM)
Take care of issue #8063 by removing duplicate problem solution
Fixes: #8063 

### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by HighnessAtharva** [comment]
@tianyizheng02 can you please review this? It addresses your issue.

**Comment by tianyizheng02** [comment]
Looks good, but it'll be up to the repo owners/maintainers to decide whether it's OK to merge

**Review by tianyizheng02 — APPROVED** [review]

**Comment by tianyizheng02** [comment]
Also you need to put the `Fixes: #8063` in your PR comment rather than the PR title for GitHub to automatically link the PR to the issue

**Comment by HighnessAtharva** [comment]
> Also you need to put the `Fixes: #8063` in your PR comment rather than the PR title for GitHub to automatically link the PR to the issue

Done

**Comment by tianyizheng02** [comment]
Oh, not in a code block, just in normal text:

Fixes: #8063 

You'll see it under the Development section on the right-hand side of the page if it worked

screenshot

**Pull request closed without merging**
