### PR TITLE
Create sol5.py

### PR DESCRIPTION
**Pull request by alpylmz**
added a solve for the problem

### CODE REVIEW

**Comment by shivg7706** [comment]
@alpylmz follow PEP8

**Comment by cclauss** [comment]
@alpylmz Line 3 is a Python syntax error.  Could you please fix that and resubmit?

**Comment by mrWiecek** [comment]
Shouldn't this solution be in project euler folder with all other solutions?

**Comment by cclauss** [comment]
Does this solution actually solve the problem?

**Comment by mrWiecek** [comment]
No it doesn't. With the syntax error you mentioned fixed it still creates infinite loop and it doesn't follow pep8. Now I see.

**Comment by cclauss** [comment]
And will it solve the problem _even if_ the syntax error is fixed?

**Comment by mrWiecek** [comment]
No it won't.

**Comment by cclauss** [comment]
Should we delete this file?

**Comment by mrWiecek** [comment]
Yes.

**Comment by shuklalok** [comment]
Yes, delete this file. File path, logic and standards - all incorrect.

**Pull request merged**
