### PR TITLE
Add solution to project_euler/problem_060

### PR DESCRIPTION
**Pull request by ignacio-gn**
### Describe your change:
Add a solution to problem 60 of project Euler

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by rohan472000** [comment]
@ignacio-gn use `ruff .` before making PR, if fix needed then use `ruff . --fix` ,so that it will automatically fix it.

**Comment by ignacio-gn** [comment]
> @ignacio-gn use `ruff .` before making PR, if fix needed then use `ruff . --fix` ,so that it will automatically fix it.

I noticed that ruff fails for files that were already present in the repository, which I did not edit. Because of that, I decided to leave these files intact. I can attempt to fix them or rebase once they are fixed. Below is the error message:

```
Error: ciphers/rsa_cipher.py:79:13: UP031 Use format specifiers instead of percent format
[5](https://github.com/TheAlgorithms/Python/actions/runs/4773277000/jobs/8486249952?pr=8678#step:4:6)
Error: ciphers/rsa_cipher.py:104:13: UP031 Use format specifiers instead of percent format
[6](https://github.com/TheAlgorithms/Python/actions/runs/4773277000/jobs/8486249952?pr=8678#step:4:7)
Error: machine_learning/linear_discriminant_analysis.py:402:16: S605 Starting a process with a shell, possible injection detected
[7](https://github.com/TheAlgorithms/Python/actions/runs/4773277000/jobs/8486249952?pr=8678#step:4:8)
Error: Process completed with exit code 1.
```

**Comment by rohan472000** [comment]
The first two errors suggest that we should use format specifiers instead of percent format. So we'll need to update the code in ciphers/rsa_cipher.py on lines 79 and 104 to use format specifiers. For example, instead of using %d, we would use {} and then use .format() to fill in the value.

The third error suggests that there may be a possible injection detected. we should check the code in machine_learning/linear_discriminant_analysis.py on line 402 and ensure that any commands being executed are properly sanitized and do not pose any security risks.

Once we have made the necessary changes, you can run ruff . --fix to automatically fix any remaining issues. After that, you can rebase your changes and submit your updated pull request for review.

**Comment by rohan472000** [comment]
@ignacio-gn I have made PR #8680 and #8679 to address above issue for both files, can you merge that two PR in one,  [rohan472000:patch-8](https://github.com/rohan472000/Python/tree/patch-8) into [rohan472000:patch-8](https://github.com/rohan472000/Python/tree/patch-9) because I cant see both branches in my local after fork.

**Comment by rohan472000** [comment]
I have merged both PR into one #8680

**Comment by rohan472000** [comment]
commenting out that line 402 is working for now, which is good, but what alternative can we put there instead of that line???

**Comment by ignacio-gn** [comment]
I have commented out the system call to clear the console on `machine_learning/linear_discriminant_analysis.py`. The reason for this is that I don't consider it to be relevant enough in the context of the program to implement an alternative that does not pose a security risk. The original call was there to clear the console on a new iteration of the program, but that behavior is not essential and it's blocking other PRs too (see [8684](https://github.com/TheAlgorithms/Python/pull/8684) and [8674](https://github.com/TheAlgorithms/Python/pull/8674)).

I haven't contributed to `machine_learning/linear_discriminant_analysis.py` so I'd understand if you want to find another solution and to discard this one. In that case, let me know and I'll rollback the changes.

**Comment by rohan472000** [comment]
@ignacio-gn , now you can uncomment that line as it is fixed , github actions should work fine.

**Review by rohan472000 — CHANGES_REQUESTED** [review]
as #8680 is merged so there is no need to make any changes in those files, just run github actions again , it should work fine.

**Pull request closed without merging**
