### PR TITLE
fix bug: edge case of avl delete

### PR DESCRIPTION
**Pull request by Leo-LiHao**
### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by xcodz-dot** [comment]
Possibly could you make the changes that bot said while also fixing the bug?

**Comment by dhruvmanila** [comment]
@algorithms-keeper review

**Comment by dhruvmanila** [comment]
@Leo-LiHao Hey can you describe as to what the bug is?

**Comment by Leo-LiHao** [comment]
> @Leo-LiHao Hey can you describe as to what the bug is?

Yes, I will add a test case later. Could you check my another PR? https://github.com/TheAlgorithms/Python/pull/4028#event-4096994235

**Comment by Leo-LiHao** [comment]
@dhruvmanila I added two test cases (one with 15 values, one with 1000 values), and here's the output of original code for 15 values after deleting 7 values (8 values left in the tree now):

```
        12        
    2        13    
  0    5    *    14  
 *  1  *  6  *  *  *  * 
```

after deleting value 13

```
        5        
    2        12    
  0    *    6    14  
 *  1  *  *  *  *  *  * 
*************************************
```

It is not an AVL tree (look at the subtree of 2). 

You could check the modified code and new test cases for more details.

**Pull request closed without merging**
