### PR TITLE
Hacktoberfest: Add a solution for problem 57

### PR DESCRIPTION
**Pull request by GGn0**
### **Describe your change:**
Create problem_57 folder and add one solution to it

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

#2695

### CODE REVIEW

**Review by meedo50 — COMMENTED** [review]
@GGn0

**Comment by GGn0** [comment]
> @GGn0 

Hi @meedo50! did you want to ask me something?

**Review by 53jk1 — APPROVED** [review]

**Review by GGn0 — COMMENTED** [review]
It seems like the approving review hasn't been detected

The automatic merge is still blocked

**Comment by dhruvmanila** [comment]
Thank you for your contributions but we do not accept a solution to existing problems. Take a look at the `project_euler/` directory and submit a solution for a non-existing problem.

**Comment by GGn0** [comment]
@dhruvmanila It was not existing when I created the pull request 20 days ago...

**Pull request closed without merging**
