### PR TITLE
Added solution for Project Euler problem 135

### PR DESCRIPTION
**Pull request by mtbun**
Same differences

Given the positive integers, x, y, and z, are consecutive terms of an arithmetic progression, the least value of the positive integer, n, for which the equation, x2 − y2 − z2 = n, has exactly two solutions is n = 27:
342 − 272 − 202 = 122 − 92 − 62 = 27
It turns out that n = 1155 is the least value which has exactly ten solutions.

How many values of n less than one million have exactly ten distinct solutions?

Reference: #2695
Reference: https://projecteuler.net/problem=135

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by mtbun** [comment]
Hey, how can i fix that problem?

**Comment by dhruvmanila** [comment]
Run:
```console
$ python -m pip install pre-commit
$ pre-commit run -a
```

**Comment by mtbun** [comment]
i fixed pre-commit. may you look my pull request?

**Comment by dhruvmanila** [comment]
There's already an open PR for this solution so this might not get accepted. If possible please try solving other problems and opening a pull request for it. Thank you for your cooperation.

**Pull request closed without merging**
