### PR TITLE
Another solution for Project Euler problem 145

### PR DESCRIPTION
**Pull request by the-other-sunny**
### Describe your change:

There is my solution for Project Euler problem 145.
The problem currently ranks as the slowest one to compute according to the Github Actions logs.
On my machine, the main function runs in 3µs, which should help drastically with #8594.
The explanation is pretty lenghty, if there's anything that needs to be removed or added I would be glad to fix it.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by the-other-sunny** [comment]
@dhruvmanila would you have time to check my pull request? Or guide me to someone that could help?

**Comment by the-other-sunny** [comment]
@cclauss @tianyizheng02 sorry for bothering, but can someone check my code? It's been almost a month since I opened the pull request and never receiving any sort of feedback.

**Comment by cclauss** [comment]
@dhruvmanila Do we accept multiple algorithms for a single Euler problem?

@the-other-sunny Is this solution faster, shorter, or easier to understand than the current solution?

**Comment by the-other-sunny** [comment]
> @dhruvmanila Do we accept multiple algorithms for a single Euler problem?
> 
> @the-other-sunny Is this solution faster, shorter, or easier to understand than the current solution?

@cclauss thank you for your reply.
This solution is significantly faster than the previous one. I ran a benchmark on my machine:

 - The previous solution takes around 24s to compute (which motivates it's presence at the top of #8594).
 - This solution takes around 3µs.

The time complexity of the previous solution seems at least exponential in the considered number of digits. This solution has a linear time complexity that can easily be improved into a logarithmic / constant complexity.

The code is fairly simple, just defining a few constants that are then used in basic calculations.
The lenghty part is the solution's explanation, which is missing on the other solution.

If any clarifications or improvements are needed, I'd be glad both to conduct them or let someone else take care of it.

**Comment by the-other-sunny** [comment]
Quite disappointed with the way things unfolded here.
I invested a significant amount of time into this, making sure the solution is well explained and efficient.
I closely followed the provided guidelines.
I addressed an issue that was marked with a "help wanted" tag.

All I received is a noticeable lack of consideration.

**Comment by the-other-sunny** [comment]
@dhruvmanila @cclauss

Quite disappointed with the way things unfolded here.

I invested a significant amount of time into this, making sure the solution is well explained and efficient. I closely followed the provided guidelines. I addressed an issue that was marked with a "help wanted" tag.

All I received is a noticeable lack of consideration.

**Comment by cclauss** [comment]
Hacktoberfest just began and we had 50 open pull requests so I closed them all enmasse before we are overwhelmed.  It is not personal… just defending the sanity of volunteers.  In general we do not need many ways to solve the same problem unless there is serious differentiation.

**Pull request closed without merging**
