### PR TITLE
Added new fractal code

### PR DESCRIPTION
**Pull request by rudransh61**
### Describe your change:
I have added a new fractal code in turtle .

[x] Add an algorithm?

### Checklist:
[x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
[x] This pull request is all my own work -- I have not plagiarized.
[x] I know that pull requests will not be merged if they fail the automated tests.
[x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
[x] All new Python files are placed inside an existing directory.
[x] All filenames are in all lowercase characters with no spaces or dashes.
[x] All functions and variable names follow Python naming conventions.
[x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
[x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.

### CODE REVIEW

**Comment by rudransh61** [comment]
idk why tests are showing error pls help

**Comment by rudransh61** [comment]
@cclauss sir pls help why tests are failing i cant understand

**Comment by tianyizheng02** [comment]
Thank you for your contribution, but unfortunately we're not accepting new PRs at the moment. We're currently trying to clear our backlog of existing PRs in preparation for Hacktoberfest. If you want to contribute, please wait until after October 1 to open a new PR.

**Comment by rudransh61** [comment]
ok sir and thanks to inform

**Pull request closed without merging**
