### PR TITLE
Added solution for Project Euler problem 89. 

### PR DESCRIPTION
**Pull request by fpringle**
Name: Roman numerals

For a number written in Roman numerals to be considered valid there are basic rules which must be followed. Even though the rules allow some numbers to be expressed in more than one way there is always a "best" way of writing a particular number.

For example, it would appear that there are at least six ways of writing the number sixteen:

IIIIIIIIIIIIIIII
VIIIIIIIIIII
VVIIIIII
XIIIIII
VVVI
XVI

However, according to the rules only XIIIIII and XVI are valid, and the last example is considered to be the most efficient, as it uses the least number of numerals.

The 11K text file, roman.txt (right click and 'Save Link/Target As...'), contains one thousand numbers written in valid, but not necessarily minimal, Roman numerals; see About... Roman Numerals for the definitive rules for this problem.

Find the number of characters saved by writing each of these in their minimal form.

Note: You can assume that all the Roman numerals in the file contain no more than four consecutive identical units.

Reference: [https://projecteuler.net/problem=89](url)
Reference: #2695

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by dhruvmanila — COMMENTED** [review]
### Announcement:

@fpringle

*This message is sent to all pull requests which are **OPEN, NOT MERGED, not containing 'wontfix' label and contains 'Project Euler' or 'Project' or 'Euler' (case doesn't matter) in their title**. If this message doesn't apply to your pull request, please ignore this.*

### Message:

This is to notify all the users submitting a pull request for the Project Euler solution that the [README.md](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) file has been updated with all the style requirements necessary for the directory and solution files. ***Please read through it and make all the necessary changes required to your submission.***

**Comment by fpringle** [comment]
Can anyone tell me what the protocol is for importing data for Project Euler problems? I.e. for this problem there's a file contain a list of words that need to be analysed. At the moment I'm defining them in a list in a separate file data.py and then importing them, but Travis doesn't like that. Should I leave them as a .txt file and us open()? Or move the list into the sol1.py file?

**Comment by dhruvmanila** [comment]
Hi, @fpringle please take a look at https://github.com/TheAlgorithms/Python/blob/master/project_euler/problem_054/sol1.py#L367-L369. If you have any doubts, feel free to post a comment tagging me.

**Comment by dhruvmanila** [comment]
Closing and reopening the pull request to run the latest test configuration.

**Comment by dhruvmanila** [comment]
Please use a `.txt` file instead.

**Review by dhruvmanila — CHANGES_REQUESTED** [review]
Please use a `.txt` file instead.

**Comment by fpringle** [comment]
Closing since there's already a solution for Problem 89.

**Pull request closed without merging**
