### PR TITLE
Added Sliding window and Kadane's Algorithm for Issue #8427

### PR DESCRIPTION
**Pull request by siddharth1009maker**
### Describe your change:

Added sliding window algorithm and kadane's algorithm

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by tianyizheng02 — COMMENTED** [review]
There are already multiple solutions to the maximum subarray sum problem in this repo (see #8609), so make sure that yours is distinct from those

**Review by tianyizheng02 — CHANGES_REQUESTED** [review]
Place your code files in an existing directory rather than making your own. Algorithms for similar topics should be in the same directory

**Comment by siddharth1009maker** [comment]
Ok I will put the code under the existing directory

**Comment by siddharth1009maker** [comment]
@tianyizheng02 
When I am trying push the changes , It is showing Everything-up-to-date 
Branch 'master' set up to track remote branch 'master' from 'origin'.

It will be great if you can provide some solution to the above issue.

**Pull request closed without merging**
