### PR TITLE
Directory.md

### PR DESCRIPTION
**Pull request by jaspalsb**
Directory that was suggested in #860

### CODE REVIEW

**Comment by AnupKumarPanwar** [comment]
@jaspalsb We will keep this on hold for now, as I'm thinking to include something similar in the README file itself, as it will allow easy navigation to the algorithms for those whole are coming for learning purpose. And yes, it is an overhead to update README file every time with the PR, but we can think of some automation script for it. But as of now, we will keep this PR on hold. Thanks for the work.

**Comment by poyea** [comment]
The automated script is available at `/~script.py`. However, I haven't completely test it. We may consider trying to integrate it with other bots/CI checks, and then we don't need to create these PRs. @AnupKumarPanwar

**Comment by fty48jj19** [comment]
e olha so por favor ja tenho conta asinatura nao quero mecher em nada nem
adicionar nada  codigo pull  pode me coloca a perde muita acoisa nao quero
nao  por favor nao emsista nao ,

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em sex, 5 de jul de 2019 às 06:08, John Law <notifications@github.com>
escreveu:

**Comment by AnupKumarPanwar** [comment]
@poyea Actually it is not necessary to generate this content list. My idea is to just make a good README file for the repo and I think adding the list of algorithms to readme is a good idea. If you can suggest some good content for the README then please go ahead, but that should not cause an overhead of updating it in every PR. I know my idea will lead to an overhead. I want some good suggestions from you.

**Comment by fty48jj19** [comment]
e  olha aqui vc esta encistino muito nao vou abri mao para vc sobre nada vc
e um contribuiite e vc esta juntano pessoas la no arquivo tem 11 pessoas
vou pedir minha equipe para verifica se vc anda certo por favor nao me peça
nada de repusitoro  nada de condigo nao adianta q nao vou sede para vc nao
vejo que vc esta muito avançado de mas por favor nao fica pedino mas nao ,

Em sáb, 6 de jul de 2019 às 03:02, Anup Kumar Panwar <
notifications@github.com> escreveu:

**Comment by cclauss** [comment]
> Do you have any ideas on how to automate this?

#964

**Comment by poyea** [comment]
I'm closing this as this is resolved by other PRs. We don't have to worry about the file now. Thank you for your pull request!🤩

**Comment by QuantumNovice** [comment]
Change this to `os.walk`. If greater speed is required use `fastio.walk`.
https://github.com/TheAlgorithms/Python/blob/05e567c2f92dc746969fe859cd806d5928067f52/scripts/build_directory_md.py#L20-L29

**Pull request closed without merging**
