### PR TITLE
 Finding Pythagorean triplets

### PR DESCRIPTION
**Pull request by rockysaikia730**
It is a simple program to calculate the Pythagorean triplets for a given number.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by xcodz-dot** [comment]
Could you please rename your file to contain `.py` extension.

**Comment by xcodz-dot** [comment]
and use python naming convention for naming your file

**Comment by xcodz-dot** [comment]
because your file might be included in a automated package of this repository

**Comment by dhruvmanila** [comment]
Closing this pull request as `invalid` as it contains an extensionless file. The user did not read the Contributing guidelines and haven't made the changes requested by a contributor.

**Pull request closed without merging**
