### PR TITLE
Update xgboost_regressor.py

### PR DESCRIPTION
**Pull request by rohan472000**
### Describe your change:

The `mean_squared_error()` function has been updated in the latest version of scikit-learn. The previous version of the function used a different formula for calculating the mean squared error, which resulted in a different value. This PR updates the code (changed the doctest results) to use the new formula.

The new version of the function uses the following formula:

          mean_squared_error(y_true, y_predicted) = np.average((y_true - y_predicted)**2)

The previous version of the function used the following formula:

         mean_squared_error(y_true, y_predicted) = np.sum((y_true - y_predicted)**2) / len(y_true)

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by rohan472000** [comment]
@cclauss kindly review this PR.

**Comment by tianyizheng02** [comment]
@rohan472000 Can you provide a source that documents this formula change?

**Comment by rohan472000** [comment]
https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/metrics/_regression.py#L404

**Comment by tianyizheng02** [comment]
> https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d/sklearn/metrics/_regression.py#L404

This is just a link to the `mean_squared_error` in scikit-learn's source code. How does this show that the formula has changed? If you check the blame for the file, you'll see that the code for the `mean_squared_error` function hasn't changed in years:

screenshot

> https://scikit-learn.org/stable/whats_new/v1.0.html

This is a changelog for scikit-learn 1.0, but the newest stable version is 1.3.0. You said the formula changed in the latest version, so why not link to the changelog for version 1.3.0? Either way, I wasn't able to find any info on either changelog stating that the formula for `mean_squared_error` has changed.

@rohan472000 I don't doubt that your PR fixes the broken doctests, but you haven't explained _why_ the outputs have changed. Do you have any sources to back up your claim that the formula actually changed? I want to make sure that your new doctest outputs are _actually_ the correct expected outputs and not simply due to an error in the implementation.

**Comment by rohan472000** [comment]
Yes ..you are correct as I read an article a month ago regarding metrics error especially mse and rmse, but it is my mistake i concluded that wrong..I also checked but no change in formula I found... deleting this PR.

**Pull request closed without merging**
