### PR TITLE
Made small improvements and shortened prime_check.py

### PR DESCRIPTION
**Pull request by Rolv-Apneseth**
### **Describe your change:**
Made small improvements and shortened prime_check.py
Shortened overall code and changed some of the comments/docstrings

For issue #3453

### CODE REVIEW

**Comment by Rolv-Apneseth** [comment]
Ok Not sure why that check failed, when I run `prime_check(1)` on my code it returns False as it should. However I'm not really sure how these tests work. Can somebody help?

**Comment by Rolv-Apneseth** [comment]
Pre-commit check is not failing on `self.assertFalse(prime_check(2 * 3))` but when run locally, all tests succeed, and running `prime_check(2 * 3)` returns False as it should so I'm confused

**Comment by poyea** [comment]
Please run `black .` for your code. https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md

**Comment by poyea** [comment]
I think you can enable the github actions in your setting of the fork too.

**Comment by Rolv-Apneseth** [comment]
@popyea of course, thanks you for the help!

**Review by poyea — APPROVED** [review]
Thank you for your pull request!🤩

**Pull request merged**
