### PR TITLE
Change_method_name

### LINKED ISSUE #1926: Same name for an attribute and a function
Hi, I'm new to programming and I'm not sure if it's a problem, but the code(
Python/data_structures/queue/queue_on_list.py) have the same name for an attribute and a function.
```
class Queue:
    def __init__(self):
        self.entries = []
        self.length = 0
        self.front = 0

    def front(self):
        return self.entries[0]
```
When executed it gives me the error:
TypeError: 'int' object is not callable

### PR DESCRIPTION
**Pull request by mrcloma**
Fixes #1926 
Change method name because it's the same name as an attribute.

### CODE REVIEW

**Comment by cclauss** [comment]
Why does this pull request have a `diff` that changes every single line in the file?  Is it line ending?

**Comment by mrcloma** [comment]
Maybe I made a mistake but at first only line 46 was changed.

**Comment by mrcloma** [comment]
Yes, its the line endings probably.

**Comment by cclauss** [comment]
Fixed in #1943

**Pull request closed without merging**
