### PR TITLE
Add solution 64

### PR DESCRIPTION
**Pull request by fatihhelvaci**

### CODE REVIEW

**Comment by dhruvmanila** [comment]
@dickyw71 Hey, can you edit the `auto_close_empty_issues` action to include pull request as well? You can open a PR and mention this comment and @ me.

**Comment by dhruvmanila** [comment]
Closed this PR as it is without any description.

**Comment by dickyw71** [comment]
@dhruvmanila I will look at adding another GitHub action to auto-closing PRs without a description. It will be pretty similar to the existing auto-close empty issues action but separate from it.

**Comment by dhruvmanila** [comment]
@dickyw71 Thanks for the reply but I don't think that will be needed. A bot is under production for this repository and we can add that functionality pretty easily into it.

**Pull request closed without merging**
