### PR TITLE
Python Program to check whether a string is Panagram or Not

### PR DESCRIPTION
**Pull request by SKAUL05**

### CODE REVIEW

**Comment by cclauss** [comment]
This has to be started from a clean branch.  Modifying four files is not good.  One file at a time.

Let's use the __other__ directory for now and not a new __string__ directory.

**Comment by SKAUL05** [comment]
Okay Sure

**Comment by cclauss** [comment]
My mistake.  We do have a https://github.com/TheAlgorithms/Python/tree/master/strings directory.

**Comment by SKAUL05** [comment]
Should I add it in other or master/strings directory

**Comment by cclauss** [comment]
strings

**Comment by SKAUL05** [comment]
Added

**Pull request closed without merging**
