### PR TITLE
An updated get_initial_centroids function

### PR DESCRIPTION
**Pull request by prashant564**

### CODE REVIEW

**Comment by AnshulMalik** [comment]
The earlier version is easier to understand @prashant564

**Comment by prashant564** [comment]
Yes it was but the vectorized implementation is better... The lesser the
code the better. I would request u accept my pull request

**Comment by AnshulMalik** [comment]
@prashant564 it's not always true `that lesser the code the better`. Our motive here is not to come up with the smallest and fastest code ever written, but to write algorithms in such a way that they perform well and are easier to understand for people. 
Hope you understand my point.

**Comment by prashant564** [comment]
Yeah,  you are right.

**Pull request closed without merging**
