### PR TITLE
Add search book via ISBN using openlibrary.org API

### PR DESCRIPTION
**Pull request by kellydosocorro**
### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by L3str4nge** [comment]
I am not sure if we want to have external dependencies like this API. I think it slows down the tests. Is it algorithm actually??

@cclauss @poyea

**Comment by cclauss** [comment]
@L3str4nge The `web_programming` directory is a bit special in that doctests are much less essential because they slow down our continuous integration and the Open Library may change the data which would break our tests.  I will propose a workaround to @kellydosocorro.

On the ___Is it an algorithm___ question in this directory, we have been requesting that there be some [pre- or post-processing of the data](https://github.com/TheAlgorithms/Python/pull/5736/files#diff-6cbe7ec8a82c933741fa7a2ee6744a6bdb0f7cd6f030fcdaa0d498dd47d5b822R48) to add value beyond the raw data provided by the api.  So the entries in this directory  are often more how-to-use-this-api than actual algorithms but I believe that @kellydosocorro has a good submission here.  Suggestions to follow…

**Comment by cclauss** [comment]
Please run psf/black on this code as discussed in CONTRIBUTING.md to fix the failing test.

**Review by cclauss — APPROVED** [review]
LGTM.  Thanks for doing this.

**Review by poyea — APPROVED** [review]
Thank you for your pull request!🤩

**Pull request merged**
