### PR TITLE
This is a simple exploratory notebook that heavily expolits pandas and seaborn

### PR DESCRIPTION
**Pull request by rishu2403**
Context
Our world population is expected to grow from 7.3 billion today to 9.7 billion in the year 2050. Finding solutions for feeding the growing world population has become a hot topic for food and agriculture organizations, entrepreneurs and philanthropists. These solutions range from changing the way we grow our food to changing the way we eat. To make things harder, the world's climate is changing and it is both affecting and affected by the way we grow our food – agriculture. This dataset provides an insight on our worldwide food production - focusing on a comparison between food produced for human consumption and feed produced for animals.

Content
The Food and Agriculture Organization of the United Nations provides free access to food and agriculture data for over 245 countries and territories, from the year 1961 to the most recent update (depends on the dataset). One dataset from the FAO's database is the Food Balance Sheets. It presents a comprehensive picture of the pattern of a country's food supply during a specified reference period, the last time an update was loaded to the FAO database was in 2013. The food balance sheet shows for each food item the sources of supply and its utilization. This chunk of the dataset is focused on two utilizations of each food item available:

Food - refers to the total amount of the food item available as human food during the reference period.
Feed - refers to the quantity of the food item available for feeding to the livestock and poultry during the reference period.
Dataset's attributes:

Area code - Country name abbreviation
Area - County name
Item - Food item
Element - Food or Feed
Latitude - geographic coordinate that specifies the north–south position of a point on the Earth's surface
Longitude - geographic coordinate that specifies the east-west position of a point on the Earth's surface
Production per year - Amount of food item produced in 1000 tonnes

### CODE REVIEW

**Comment by cclauss** [comment]
The notebook looks supercool!  Congratulations.  To keep the project tidy, we do not put contribution files at the root of the directory.  Try to pick a foldername in the project than makes sense for this contribution.  Then (let's suppose that your pick __other__) go to each of your files and click __Edit__ and then put __other/__ just in front of your filename.  Like __Python/FAO.csv__ --> __Python/other/FAO.csv__.  Thanks for your contributions.

**Comment by rishu2403** [comment]
> This notebook looks supercool! Congratulations. To keep the project tidy, we do not put contribution files at the root of the directory. Try to pick a foldername in the project than makes sense for this contribution. Then (let's suppose that your pick **other**) go to each of your files and click **Edit** and then put **other/** just in front of your filename at the top of the page and then **Commit change** at the bottom of the page. Like **Python/FAO.csv** --> **Python/other/FAO.csv**. Thanks for your contributions.

I have done as requested please let me know if i am right . Thankyou for helping me. I am actually new to github and trying to learn.

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/other/food_wastage_analysis_from_1961-2013_fao.ipynb already exists in this repo.  Can we close this PR or is it an improvement on that file?  Why does the file not properly display on GitHub?

**Comment by rishu2403** [comment]
> https://github.com/TheAlgorithms/Python/blob/master/other/food_wastage_analysis_from_1961-2013_fao.ipynb already exists in this repo. Can we close this PR or is it an improvement on that file? Why does the file not properly display on GitHub?

Please close this PR.
Thankyou

**Pull request closed without merging**
