### PR TITLE
Added A General Swish Activation Function inNeural Networks

### PR DESCRIPTION
**Pull request by shivansh-bhatnagar18**
### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by tianyizheng02 — COMMENTED** [review]
Thanks for your contribution, but could you modify [neural_network/activation_functions/sigmoid_linear_unit.py](https://github.com/TheAlgorithms/Python/blob/d96029e13d181229c692b8e4cafe2661cdae919e/neural_network/activation_functions/sigmoid_linear_unit.py) rather than making a separate file for the general swish function? Since the SiLU function is just the swish function with a parameter of 1, I think it'd make much more sense if you could rename that file to `swish.py` and generalize the existing function.

**Comment by shivansh-bhatnagar18** [comment]
@tianyizheng02 [Modified] The general swish function was added in the Sigmoid Linear Unit and was labeled as 'swish.py'. Could you look into it and merge my pull request?

**Comment by shivansh-bhatnagar18** [comment]
@tianyizheng02 Sir, I added the general swish model in the Sigmoid Linear Unit Model and renamed it as 'swish.py'. Now in order to maintain learning through these algorithms, I didn't find it appealing enough to delete the existing SiLU function to let others know that it is a popular name for the swish function of parameter 1. Hence I just added both functions. Could you please look into this and merge my PR?

**Review by tianyizheng02 — APPROVED** [review]

**Comment by tianyizheng02** [comment]
Thanks for your contribution!

**Pull request merged**
