### PR TITLE
Cache pre-commit workflow

### PR DESCRIPTION
**Pull request by dhruvmanila**
### **Describe your change:**

Add the ability to cache pre-commit workflow to be reused later.

* [x] Improve workflow

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.

### CODE REVIEW

**Review by cclauss — CHANGES_REQUESTED** [review]
RSLGTM Do you have a sense for how much time this saves us?

**Review by cclauss — APPROVED** [review]

**Comment by dhruvmanila** [comment]
This will cache the `pip` and `pre-commit` downloads. This will also cache all the environments `pre-commit` initializes at the start of each run which includes `black`, `flake8`, `isort`, and the rest of them.

I think approximately a minute or so in each run.

**Comment by cclauss** [comment]
https://chromium.googlesource.com/chromiumos/docs/+/master/glossary.md

**Comment by cclauss** [comment]
1m17s --> 41s

**Pull request merged**
