### PR TITLE
Create function_composition.py

### PR DESCRIPTION
**Pull request by QuantumNovice**
### Added function `Compose` class that facilitates function composition in a way that lead to optics.
Makes function composition possible in a mathematical way.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.

### CODE REVIEW

**Comment by QuantumNovice** [comment]
This works for any function/object. No need for mypy static type hints.

**Comment by cclauss** [comment]
In theory, would this be possible for functions that took two parameters like x,y or lat, lon?

**Comment by QuantumNovice** [comment]
> 
> 
> In theory, would this be possible for functions that took two parameters like x,y or lat, lon?
Yes, int theory although I am not entirely sure how I would do it here. I think eventually those functions are reduced to a single variable functions via partial differentiation.

**Comment by cclauss** [comment]
*args, **kwargs would allow us to pass an arbitrary number of params but...

**Comment by QuantumNovice** [comment]
> 
> 
> *args, **kwargs would allow us to pass an arbitrary number of params but...
In case of multivariate functions this notation becomes ambiguous because if
f = a(x,y)
g = b(x,y)
then `( f * g)(x)` could be any of `f(g(x,y), y)` , `f(x, g(x,y)`

https://en.wikipedia.org/wiki/Function_composition

**Comment by cclauss** [comment]
If the call is `( f * g)(*args)` then
```
    answer = f(g(*args), args[-1])
    if f(args[0], g(*args)) != answer:
        raise Exception()
    return answer
```
That _might_ work `if len(args) in (1, 2)`

**Pull request closed without merging**
