### PR TITLE
Add matrix_multiplication

### PR DESCRIPTION
**Pull request by ojas-wani**
### Describe your change:
This Python script demonstrates matrix multiplication using a recursive algorithm. 
Matrix multiplication is a fundamental operation in linear algebra and computer science.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by ojas-wani** [comment]
Dear Reviewer, 

I need your little help here. As all the things seem good but I don't know why I am not passing the ruff test. I made all the suggested changes still have the same issue.

**Comment by haxkd** [comment]
first of all make seperate pull request for digital_image_processing/filters/laplacian_filter.py & maths/matrix_multiplication_recursion.py

**Comment by cclauss** [comment]
Please remove the first file and only modify one file.

Python 3.5 added an `@` matrix multiplication operator.  Why not just use that (or numpy)?
```
from dataclasses import dataclass

@dataclass
class Matrix:
    data: list[list[int]]

    def __matmul__(self, other):
        if len(self.data[0]) != len(other.data):
            raise ValueError("Matrix dimensions are not compatible for multiplication")

        result = []
        for i in range(len(self.data)):
            row = []
            for j in range(len(other.data[0])):
                dot_product = sum(self.data[i][k] * other.data[k][j] for k in range(len(other.data)))
                row.append(dot_product)
            result.append(row)
        return Matrix(result)

# Example usage
matrix1 = Matrix([[1, 2, 3], [4, 5, 6]])
matrix2 = Matrix([[7, 8], [9, 10], [11, 12]])
result_matrix = matrix1 @ matrix2

for row in result_matrix.data:
    print(row)
```

**Comment by cclauss** [comment]
If we are going to land this then the file needs to go into https://github.com/TheAlgorithms/Python/tree/master/matrix

This work is on the branch `ojas-wani:laplacian-filter` which also contains the file `digital_image_processing/filters/laplacian_filter.py` which is unrelated to matrix multiplication.

If you want this to land then please create a new branch and modify only one file that goes in the matrix directory.

**Comment by ojas-wani** [comment]
I changed the file location. I had a conflict that's why worked in the same branch. Please accept this time. I will create a new branch next time for another file.

**Comment by ojas-wani** [comment]
Hello reviewers, I opened this pull request last week and passed all the tests. Can you please review and merge it?

**Comment by ManpreetSingh2004** [comment]
Hi @ojas-wani ,

I've taken a close look at your pull request, while I'm not a repository maintainer and can't merge the changes, I'm here to help. As cclauss suggested please create a new branch to get this PR merged.

Here are a few suggestions:

1. It would be beneficial to ensure the consistency of the docstring style with the other files in the repository. Refer to this example in the repository: [maths/tanh.py](https://github.com/TheAlgorithms/Python/blob/b5786c87d820cc4d68707731df0812507063bf8b/maths/tanh.py#L16) for guidance.

2. Please add the expected output that the function should produce in the doctests. For example, for matrix_multiply_recursive function add:

    ```python
    >>> matrix_a = [[1, 2], [3, 4]]
    >>> matrix_b = [[5, 6], [7, 8]]
    >>> matrix_multiply_recursive(matrix_a, matrix_b)
    [[19, 22], [43, 50]]
    ```

    Additionally, for the `multiply()` function, the doctests can be written as follows:

    ```python
    >>> matrix_a = [[1, 2], [3, 4]]
    >>> matrix_b = [[5, 6], [7, 8]]
    >>> result = [[0, 0], [0, 0]]
    >>> multiply(0, 0, 0, matrix_a, matrix_b, result)
    >>> result
    [[19, 22], [43, 50]]
    ```

Please consider these recommendations to enhance the quality of the pull request. If you have any questions or need further assistance, feel free to reach out.

**Review by cclauss — APPROVED** [review]

**Pull request merged**
