### PR TITLE
Implementation of the Knapsack Problem Solver #11401

### LINKED ISSUE #11401: Implementation of the Knapsack Problem Solver
### Feature description

**_Description_**
I propose the addition of a new feature to solve the Knapsack Problem, a fundamental challenge in combinatorial optimization. This problem involves selecting items with specific weights and values to maximize the total value without exceeding the weight capacity of the knapsack. It has applications in resource allocation, logistics, finance, and more.

**Suggested Implementation**
The solver could be implemented using Python, and I recommend starting with a dynamic programming approach for the 0/1 Knapsack Problem. Future enhancements might include other variations like the Bounded and Unbounded Knapsack Problems.

Educational Value: Great for demonstrating algorithm efficiency and optimization techniques.
Utility: Can be used as a utility for other features within the project that may require optimization capabilities.
Community Engagement: Offers a well-defined problem that could help new contributors get involved with the project through clear, manageable goals.

**Requirements**
A function to accept arrays/lists of weights, values, and the maximum capacity of the knapsack.
An algorithm to compute the maximum value that can be carried in the knapsack without exceeding the weight limit.
Unit tests to ensure the functionality works correctly under various scenarios.

**Possible Extensions**
Adding support for fractional items (for the fractional knapsack problem).
Implementing different algorithms for comparison, such as a greedy approach, branch and bound, or genetic algorithms.
I believe this feature would be a valuable addition to the project and look forward to the community's feedback and ideas on this proposal.

[Example_Knapsack Problem.pdf](https://github.com/TheAlgorithms/Python/files/15287324/Example_Knapsack.Problem.pdf)

### PR DESCRIPTION
**Pull request by snigdha510**
### Describe your change:

Fixes #11401

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ x] This pull request is all my own work -- I have not plagiarized.
* [ x] I know that pull requests will not be merged if they fail the automated tests.
* [ x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x] All new Python files are placed inside an existing directory.
* [ x] All filenames are in all lowercase characters with no spaces or dashes.
* [ x] All functions and variable names follow Python naming conventions.
* [ x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by imSanko — CHANGES_REQUESTED** [review]
How about adding few of these?
 
 """

    >>> capacity = 50
    >>> values = [60, 100, 120]
    >>> weights = [10, 20, 30]
    >>> knapsack_dp(capacity, weights, values)
    220

    >>> capacity = 0
    >>> values = [60, 100, 120]
    >>> weights = [10, 20, 30]
    >>> knapsack_dp(capacity, weights, values)
    0

    >>> capacity = 10
    >>> values = [10, 10, 10]
    >>> weights = [5, 5, 5]
    >>> knapsack_dp(capacity, weights, values)
    20

    >>> capacity = 100
    >>> values = [60, 100, 120, 80, 30]
    >>> weights = [10, 20, 30, 40, 50]
    >>> knapsack_dp(capacity, weights, values)
    300

    >>> capacity = 7
    >>> values = [1, 4, 5, 7]
    >>> weights = [1, 3, 4, 5]
    >>> knapsack_dp(capacity, weights, values)
    9
    """

**Review by imSanko — APPROVED** [review]
Until that looks fine!!

**Comment by snigdha510** [comment]
sure I'll do that as well

**Review by snigdha510 — COMMENTED** [review]
Implemented the changes asked as well

**Comment by liyahshaikh** [comment]
Here the docstring has an incorrect case. 
The below should be 360 I believe, which is why the doctest is failing.

```
>>> capacity = 100
>>> values = [60, 100, 120, 80, 30]
>>> weights = [10, 20, 30, 40, 50]
>>> knapsack_dp(capacity, weights, values)
360
```

**Comment by tianyizheng02** [comment]
We already have an implementation of the DP solution to the 0-1 knapsack problem in [`dynamic_programming/knapsack.py`](https://github.com/TheAlgorithms/Python/blob/723cf9c42839c47e9e6fb83362a7391177355505/dynamic_programming/knapsack.py). Please check the repo for existing implementations before you contribute, and please consider improving upon the existing implementation instead of contributing a duplicate.

**Pull request closed without merging**
