### PR TITLE
Travis CI: Upgrade to Python 3.8

### PR DESCRIPTION
**Pull request by cclauss**
ERROR: Could not find a version that satisfies the requirement opencv-python (from -r requirements.txt (line 6)) (from versions: none)

219ERROR: No matching distribution found for opencv-python (from -r requirements.txt (line 6))

### CODE REVIEW

**Comment by poyea** [comment]
Does it persist? I can't figure out why.

**Comment by cclauss** [comment]
Blocked by https://github.com/skvark/opencv-python/issues/253

**Comment by onlinejudge95** [comment]
Just a nudge, should we think about pinning dependencies

**Comment by cclauss** [comment]
Nope.  We are not distributing an package or application so reproducible builds are _not a goal_ for this repo.  We want our users to be assured that these algorithms are _ready-to-use_ so we want CI testing to alert us immediately when any of our algorithms break on the latest and greatest version of their dependencies.

**Comment by cclauss** [comment]
Blocked by https://pypi.org/project/tensorflow at tensorflow/tensorflow#33374

**Comment by cclauss** [comment]
https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-571074915

**Comment by cclauss** [comment]
Closing in favor of #1783

**Pull request closed without merging**
