### PR TITLE
Add graph centrality algorithms to compute central and median nodes i…

### PR DESCRIPTION
**Pull request by jeffreyyancey**
### Describe your change:

**Title**: Add graph centrality algorithms for computing central and median nodes

**Description**:

This pull request introduces new algorithms to compute the central and median nodes in a weighted graph. It includes the implementation of the Floyd-Warshall algorithm for all-pairs shortest paths and functions to calculate eccentricity and harmonic closeness centrality. The code is well-documented, includes comprehensive type hints, and contains doctests for various graph scenarios to ensure correctness.

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [X] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [X] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a closing keyword: "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by imSanko — CHANGES_REQUESTED** [review]
Can you describe the changes

**Comment by jeffreyyancey** [comment]
@imSanko Certainly.

-------- 

Add graph centrality algorithms to compute central and median nodes in a graph

- Implement \`floyd_warshall_algorithm\` to compute all-pairs shortest paths using the Floyd-Warshall algorithm.
- Implement \`find_central_and_median_node\` to calculate eccentricity and harmonic closeness centrality for each node.
- Add helper functions:
  - \`initialize_distance_matrix\` for initializing the distance matrix and validating edge weights.
  - \`calculate_node_centrality\` for computing eccentricity and closeness of a single node.
- Include comprehensive module-level docstrings explaining:
  - The mathematical problem and its significance.
  - Descriptions of the algorithms used.
  - Pseudo-code for the Floyd-Warshall algorithm.
  - References to relevant Wikipedia articles.
- Add detailed type hints for all functions and variables to enhance code clarity and support static type checking.
- Refactor code to improve readability and maintainability:
  - Use descriptive variable names.
  - Introduce intermediate variables for complex expressions.
  - Add comments explaining key steps and computations.
- Ensure compliance with PEP 8 standards:
  - Adjust line lengths to not exceed 88 characters.
  - Reformat long strings and comments.
  - Fix issues identified by code linters like \`ruff\`.
- Handle exceptions properly:
  - Assign exception messages to variables before raising, adhering to best practices.
- Include doctests for various graph scenarios to verify correctness:
  - Single-node graphs.
  - Two-node graphs with positive weights.
  - Fully connected graphs.
  - Directed acyclic graphs (DAGs).
  - Disconnected graphs.
  - Graphs with zero or negative edge weights (raising exceptions).
  - Cyclic graphs.
  - Sparse graphs.

--------

Please let me know if you have further questions.

**Comment by jeffreyyancey** [comment]
My branches seemed to have gotten crossed. I'll close this and recreate a new PR with the proper branch.

**Comment by imSanko** [comment]
> @imSanko Certainly.
> 
> Add graph centrality algorithms to compute central and median nodes in a graph
> 
> * Implement `floyd_warshall_algorithm` to compute all-pairs shortest paths using the Floyd-Warshall algorithm.
> * Implement `find_central_and_median_node` to calculate eccentricity and harmonic closeness centrality for each node.
> * Add helper functions:
>   
>   * `initialize_distance_matrix` for initializing the distance matrix and validating edge weights.
>   * `calculate_node_centrality` for computing eccentricity and closeness of a single node.
> * Include comprehensive module-level docstrings explaining:
>   
>   * The mathematical problem and its significance.
>   * Descriptions of the algorithms used.
>   * Pseudo-code for the Floyd-Warshall algorithm.
>   * References to relevant Wikipedia articles.
> * Add detailed type hints for all functions and variables to enhance code clarity and support static type checking.
> * Refactor code to improve readability and maintainability:
>   
>   * Use descriptive variable names.
>   * Introduce intermediate variables for complex expressions.
>   * Add comments explaining key steps and computations.
> * Ensure compliance with PEP 8 standards:
>   
>   * Adjust line lengths to not exceed 88 characters.
>   * Reformat long strings and comments.
>   * Fix issues identified by code linters like `ruff`.
> * Handle exceptions properly:
>   
>   * Assign exception messages to variables before raising, adhering to best practices.
> * Include doctests for various graph scenarios to verify correctness:
>   
>   * Single-node graphs.
>   * Two-node graphs with positive weights.
>   * Fully connected graphs.
>   * Directed acyclic graphs (DAGs).
>   * Disconnected graphs.
>   * Graphs with zero or negative edge weights (raising exceptions).
>   * Cyclic graphs.
>   * Sparse graphs.
> 
> Please let me know if you have further questions.

Make sure that the answers are plagiarism free and not AI Generated !

**Pull request closed without merging**
