### PR TITLE
hacktoberfest

### PR DESCRIPTION
**Pull request by willtryagain**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm? no
* [ ] Documentation change? 

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by xcodz-dot** [comment]
Hello Sir, Please read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/main/CONTRIBUTING.md)

**Comment by xcodz-dot** [comment]
please check out this [link](https://github.com/TheAlgorithms/Python/pull/3659/checks?check_run_id=1297473177) to fix your code for any errors which are produced in the workflow checks.

**Comment by xcodz-dot** [comment]
Hello, Also you can split this up into two PR. One for 48 and one for 50. In 50 you can include your solution and __init__.py file and in 48 you can include the solution to project euler 48.

This will also complete your hactoberfest goal by twice.

**Comment by poyea** [comment]
@williamfzc Please split this into two PRs. Thanks.

**Comment by xcodz-dot** [comment]
@poyea the author is @willtryagain and not @williamfzc

**Pull request closed without merging**
