### PR TITLE
Travis CI: Identify our ten slowest pytests

### PR DESCRIPTION
**Pull request by cclauss**
https://howchoo.com/g/mtblodnjzjc/how-to-measure-unit-test-execution-times-in-pytest helps us to find the individual tests that are slowing down our Travis CI checks.

```
============================= slowest 10 durations =============================
36.16s call     project_euler/problem_34/sol1.py::problem_34.sol1.compute
20.02s call     sorts/sleep_sort.py::sleep_sort.sleep_sort
5.86s call     project_euler/problem_43/sol1.py::problem_43.sol1.compute_sum
5.82s call     graphs/bidirectional_breadth_first_search.py::bidirectional_breadth_first_search.BreadthFirstSearch
5.04s call     project_euler/problem_27/problem_27_sol1.py::problem_27_sol1.solution
4.90s call     project_euler/problem_44/sol1.py::problem_44.sol1.compute_num
4.70s call     project_euler/problem_25/sol1.py::problem_25.sol1.solution
4.03s call     project_euler/problem_33/sol1.py::problem_33.sol1.solve
3.52s call     project_euler/problem_47/sol1.py::problem_47.sol1.solution
2.86s call     maths/miller_rabin.py::maths.miller_rabin.is_prime
================ 738 passed, 769 warnings in 132.17s (0:02:12) =================
```
@Kush1101 Given that our slowest test is taking 36 seconds on every pull request, would you be willing to look at that test and see if you can speed things up?  Also, the third test.

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Kush1101** [comment]
@cclauss. Sure! I'd be happy to help.

**Comment by Kush1101** [comment]
> @cclauss. Sure

PR #2305 which added the file problem_34 (which takes the longest time) did not pass all the tests. Here is the [log](https://travis-ci.com/github/TheAlgorithms/Python/builds/179603918) of the test which failed. 
The solution itself takes more than 15 seconds to run, so @cclauss Do you suggest that I should come up with a faster solution or simply resolving the failed test would speed things up?

**Comment by cclauss** [comment]
The idea in to not lower the reader’s confidence that the code works as expected.

Best: speed up the implementation and keep the test.
Good: find a similar test that runs faster
Acceptable: comment out the test but do not remove it and write down why you have done so.

**Comment by Kush1101** [comment]
> The idea is to not lower the reader’s confidence that the code will work as expected.
> 
> Best: speed up the implementation and keep the test.
> Good: find a similar test that runs faster
> Acceptable: comment out the test but do not remove it and write down why you have done so.

I can speed up the implementation. Shall I start a PR now?

**Comment by cclauss** [comment]
Please don’t wait for permission...  If you see something that should be done then do it.

**Review by poyea — APPROVED** [review]

**Review by itsvinayak — APPROVED** [review]

**Pull request merged**
