### PR TITLE
`local_weighted_learning.py`: fix `mypy` errors and more

### PR DESCRIPTION
**Pull request by tianyizheng02**
### Describe your change:

For `local_weighted_learning.py`:
- Fixed the `mypy` errors related to the file (that I accidentally introduced in #8069 💀), related to #8070
- Expand function documentation
- Add detailed explanation of algorithm at top of file
- Miscellaneous refactoring and renaming for clarity

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by CaedenPH — APPROVED** [review]
Looks good to me!

**Comment by tianyizheng02** [comment]
@cclauss does this look good to merge?

**Comment by tianyizheng02** [comment]
@cclauss what do you think?

**Comment by tianyizheng02** [comment]
@ChrisO345 mind taking a look?

**Review by ChrisO345 — APPROVED** [review]

**Pull request merged**
