### PR TITLE
different take on bubble sort

### PR DESCRIPTION
**Pull request by ayush246**
this sorting algorithm sorts an array using the principle of bubble sort , but does it both from left to right and right to left , hence i decided to call it "double sort"

### CODE REVIEW

**Comment by AnshulMalik** [comment]
Hey @ayush246, this look too cryptic to understand, some comments or meaningful variable names might help :)

**Comment by ayush246** [comment]
This should help hopefully . Also thanks for replying ..

**Comment by cclauss** [comment]
Please remove the spaces between __print__ and (.  __print()__ is a function in Python just like __range()__ is.

**Comment by ayush246** [comment]
Sir , 
this pull request was closed before so i had deleted my local repo. Since it has been reopened , i am having trouble making commits to this pull request. Should i make a new one ?

**Comment by cclauss** [comment]
Yes.  Please.

**Pull request closed without merging**
