### PR TITLE
fixed the issue in strings/join.py

### LINKED ISSUE #12408: strings/join.py is incorrect
### Repository commit

3b1b70bf0e60dddb14917dd7cad34a41d429df01

### Python version (python --version)

Python 3.10

### Dependencies version (pip freeze)

n/a

### Expected behavior

s = ["", "", ""]
join(",", s) == ",".join(s)
# ',,' == ',,'

### Actual behavior

s = ["", "", ""]
join(",", s) == ",".join(s)
# '' != ',,'

### PR DESCRIPTION
**Pull request by RajdeepBakolia2004**
The issue was that join() function was not working as the join method of string due to strip method which truncates from end 
now whenever we have empty strings in our separated list it was just adding multiple terminator and all the terminator where getting strip which was different form the join method so a for loop was run for the entire list except the last element in which case it just add the last element and it also take care of the case when the list is empty

It fixes the bug in the join.py file

Fixes #12408

### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by MaximSmolskiy** [comment]
Added corresponding doctest

**Comment by MaximSmolskiy** [comment]
@RajdeepBakolia2004 Please fill [pull_request_template](https://github.com/TheAlgorithms/Python/blob/master/.github/pull_request_template.md) that I added to the end of your PR description

@cclauss We don't have any problems with automatic PRs closing by the robot if there is no template or nothing is filled in there? My PR #12450 was closed as invalid when I forgot to fill template, but I see some opened recent PRs with the same problem

**Review by MaximSmolskiy — CHANGES_REQUESTED** [review]
Please fix my comment above

**Comment by RajdeepBakolia2004** [comment]
sure thank you for reminding me

________________________________

**Comment by cclauss** [comment]
We want PRs to be autoclosed for no checkboxes are checked to limit spam PRs.  Maintainers should be able to reopen closed PRs.

**Review by MaximSmolskiy — APPROVED** [review]
@RajdeepBakolia2004 Thanks for fix, tried to make it more elegant and shorter

**Comment by RajdeepBakolia2004** [comment]
Thank you 🙂

________________________________

**Pull request merged**
