### PR TITLE
Update doubly linked list

### PR DESCRIPTION
**Pull request by shellhub**
### **Describe your change:**

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by cclauss — CHANGES_REQUESTED** [review]
There are really not enough tests here.  This submission deletes a lot of tests which is going in the wrong direction.  We need more tests, not fewer.  It is OK to create a separate test file as long as pytest finds it via test discovery but it is too difficult to spot bugs without tests.

Please move the definition of Node before LinkedList.
The name of the file and the name of the main class should match so perhaps the class should be DoublyLinkedList.

**Comment by cclauss** [comment]
Please add a doctest on `.__iter__()`...
```
        >>> linked_list = DoublyLinkedList()
        >>> linked_list.insert_at_head('b')
        >>> linked_list.insert_at_head('a')
        >>> linked_list.insert_at_tail('c')
        >>> tuple(linked_list)
        ('a', 'b', 'c')
```

**Comment by shellhub** [comment]
@cclauss Done.

**Comment by cclauss** [comment]
OPTIONAL: Create Node as a [dataclass](https://docs.python.org/3/library/dataclasses.html) which will automatically create `.__str__()`...

% __python3__
```python
>>> from __future__ import annotations
>>> from dataclasses import dataclass
>>> from typing import Any, Optional
>>> @dataclass
... class Node:
...     data: Any
...     prev: Optional[Node] = None
...     next: Optional[Node] = None
...
>>> Node("Data")
Node(data='Data', prev=None, next=None)
```

**Comment by shellhub** [comment]
> OPTIONAL: Create `Node` as a Python [dataclass](https://docs.python.org/3/library/dataclasses.html) which will automatically create `.__init__()` and `.__str__()`...
> 
> % **python3**
> 
> ```python
> >>> from __future__ import annotations
> >>> from dataclasses import dataclass
> >>> from typing import Any, Optional
> >>> @dataclass
> ... class Node:
> ...     data: Any
> ...     prev: Optional[Node] = None
> ...     next: Optional[Node] = None
> ...
> >>> Node("Data")
> Node(data='Data', prev=None, next=None)
> ```

I'am not familiar with this. I think current version is friendly to beginner. BTW. this PR can be merged ? :)

**Comment by cclauss** [comment]
More worried about merging than learning?

**Review by cclauss — APPROVED** [review]

**Comment by shellhub** [comment]
> More worried about merging than learning?

I will study in a few days. 👍 :)

**Pull request merged**
