### PR TITLE
Python 3.9

### PR DESCRIPTION
**Pull request by cclauss**
### **Describe your change:**

Migrate to Python 3.9 changing the file extensions of all files that require TensorFlow.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?
* [x] Upgrade infrastructure

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
`TensorFlow` will still take some time as they have a few dependencies as well. Also, `mypy` is not fully compatible with 3.9. So, I think we should wait for a bit. As for the typing errors, we should use the 3.9 with future import, and then once `mypy` is fully compatible and all our dependencies have upgraded to 3.9, then we will remove the future import and start running `mypy` and upgrade the CI to 3.9.

**Comment by cclauss** [comment]
My ___strong___ preference would be that this repo migrates to the current version of Python and leave the following files out of our test cycle because their dependencies do not yet support Python 3.9.  I would much rather ensure that our code is tested on and compatible with the current Python than to wait.

Note:  The following files do not have .py extensions because [TensorFlow does not yet support the current Python](https://github.com/tensorflow/tensorflow/issues/44485).
* dynamic_programming/k_means_clustering_tensorflow.py_tf
* machine_learning/lstm/lstm_prediction.py_tf
* neural_network/gan.py_tf
* neural_network/input_data.py_tf

**Comment by dhruvmanila** [comment]
I am a bit hesitant to do monkey patching on an entire repository as that might lead to an unforeseen situation in the future. Also, not everyone is going to have the latest Python installed on their machine let alone use it.

On a side note, any idea as to why the test is taking 18 minutes to download the dependecies?

**Comment by cclauss** [comment]
> monkey patching on an entire repository

I do not think that changing the file extension on four files constitutes _monkey patching on an entire repository_.

The build times are about the lack of wheels on some dependencies.  Does your build cache help us to resolve that issue or will we always have long builds?

**Comment by dhruvmanila** [comment]
Try pushing an empty commit and we will check but even without cache it shouldn't take this much time.

**Comment by dhruvmanila** [comment]
Closing and reopening the pull request to trigger workflow runs.

**Comment by cclauss** [comment]
Pip process is 3 minutes with caching...  I can live with that.

**Comment by dhruvmanila** [comment]
There's some problem with the wheels of `qiskit-aer`: https://github.com/TheAlgorithms/Python/pull/3926/checks?check_run_id=1447346191#step:5:150

**Comment by dhruvmanila** [comment]
Let's restrict `qiskit` to 3.8 as well.
Qiskit is yet to support 3.9: https://github.com/Qiskit/qiskit/blob/master/setup.py#L54
Issue: https://github.com/Qiskit/qiskit/issues/1111

**Comment by cclauss** [comment]
https://github.com/Qiskit/qiskit-aer/pull/1016

**Comment by dhruvmanila** [comment]
Well then we don't need to restrict `qiskit`. We will be fine with 3 minutes then.

**Comment by cclauss** [comment]
Running on Python 3.9 is different than having a wheel for Python 3.9.  The former means that it does not work.  The latter means that it works but the install time is long.  The tests for all of our quantum algorithms run and pass on Python 3.9.  The long install times are dealt with by your pip cache.

**Review by dhruvmanila — APPROVED** [review]

**Pull request merged**
