### PR TITLE
Fix #8715 Update the remove func of binary search tree.

### LINKED ISSUE #8715: Removing the root node in binary_search_tree.py removes the whole tree.
### Repository commit

73105145090f0ce972f6fa29cc5d71f012dd8c92

### Python version (python --version)

Python 3.10.6

### Dependencies version (pip freeze)

astroid==2.15.4
...

### Expected behavior

https://github.com/TheAlgorithms/Python/blob/master/data_structures/binary_tree/binary_search_tree.py

Removing the root node should not delete the whole tree, it should behave just like removing any other nodes. It works fine if we delete other nodes but I guess because of the [this line](https://github.com/TheAlgorithms/Python/blob/73105145090f0ce972f6fa29cc5d71f012dd8c92/data_structures/binary_tree/binary_search_tree.py#L43), it has problem when we remove the root node. There should be other checks as well.

### Actual behavior

```python
>>> t = BinarySearchTree()
>>> t.insert(1)
>>> t.insert(2)
>>> t.insert(3)
>>> t.remove(1)
>>> str(t)
'None'
>>> 
```

### PR DESCRIPTION
**Pull request by yabea**
### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by rohan472000 — CHANGES_REQUESTED** [review]
To resolve `ruff` issue, you need to modify the type annotations in lines 8 and 9 of the "maths/euclidean_distance.py" file. Instead of the current syntax, you should use the `X | Y` syntax.

**Comment by rohan472000** [comment]
Actually this error has been seen in a couple of PRs, even when there is no code written in that context, @cclauss plz look into it.

**Comment by yabea** [comment]
@rohan472000 I've fixed ruff error, but in fact, I also error when I pre-commit locally, maybe someone needs to check it out

**Comment by tianyizheng02** [comment]
@cclauss This should be closed now that #8752 has been merged and the issue has been fixed

**Pull request closed without merging**
