### PR TITLE
Hacktoberfest 2020: Add typehints and default argument for project_euler/problem_01

### PR DESCRIPTION
**Pull request by archaengel**
### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

Related: #2786

### CODE REVIEW

**Comment by archaengel** [comment]
This PR addresses the issues mentioned in [#2786(comment)](https://github.com/TheAlgorithms/Python/issues/2786#issuecomment-703365779) in the directory for Project Euler Problem 01

**Comment by CMeza99** [comment]
A default of a 1000 seems arbitrary and, to me, would be "unexpected" behavior, if the function was used in a program.

**Comment by archaengel** [comment]
@CMeza99 I definitely see how `1000` seems like an arbitrary default. Unless I misunderstand, the `project_euler` directory is meant to provide solutions to the corresponding problems from the Project Euler site. 

[Problem 1](https://projecteuler.net/problem=1) specifically mentions `1000` in the problem statement, and is in line with the implementation of the [validation script](https://github.com/TheAlgorithms/Python/blob/master/project_euler/validate_solutions.py) which tests against the expected values in [project_euler_answers.json](https://github.com/TheAlgorithms/Python/blob/master/project_euler/project_euler_answers.json), and the suggested improvements mentioned in [#2786(comment)](https://github.com/TheAlgorithms/Python/issues/2786#issuecomment-703365779). 

I think it makes sense to squash these commits.

**Review by dhruvmanila — APPROVED** [review]
This is perfect! Thank you for doing this.

**Comment by dhruvmanila** [comment]
Also @archaengel please don't squash your commits as it will be done by us when we merge them. It is unnecessary on your end to do it.

@CMeza99 Please refer #2786

**Comment by archaengel** [comment]
@dhruvmanila Gotcha, I'll keep that in mind. Thanks for the review!

**Pull request merged**
