### PR TITLE
Fix setting with copy warning

### PR DESCRIPTION
**Pull request by sjadlakha**
### **Describe your change:**
Solved issue #2282. SettingWithCopy warning in machine learning/k_means_clust.py. 
Have set the changed_assignment option in pandas.options.mode to None.

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by sjadlakha** [comment]
Hey, can you review my pull request?

**Comment by satorutakada** [comment]
この度は私の為に、ありがとうございます。私は正直な所なんとなーく雰囲気でしか分かりません。何もかもが初めてなので、事前に深く考えるのは辞めようと思います。いつも行き当たりばったりだったので。
私仕事がありますので、何とかして頑張りますので。これいつ来るとか分からないのですか？わからないですよね。

**Comment by satorutakada** [comment]
警告は無視してもいいということですね。
何年だろう。ずっと押し込められてた気がしててスッキリすることあまりなかったけど、やっと自由になれるのかなって期待してます。
現実は残酷で辛いこともありましたが、最後が良ければそれが一番です。

**Comment by cclauss** [comment]
@sjadlakha The goal is not to [turn off the warnings](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-evaluation-order).  The goal is to fix the code so that it does not generate any warnings.

**Comment by sjadlakha** [comment]
> @sjadlakha The goal is not to [turn off the warnings](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#indexing-evaluation-order). The goal is to fix the code so that it does not generate any warnings.

Sure, will fix it. Thanks

**Pull request closed without merging**
