### PR TITLE
Fix quicksort doc

### PR DESCRIPTION
**Pull request by varopxndx**
### **Describe your change:**
I fixed the quicksort documentation following the markdown best practices.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by chakeson** [comment]
This is the same as #4875 fyi

**Comment by varopxndx** [comment]
Hi @chakeson 
I just added another documentation to avoid problems with another partner.
I hope this works.
Thank you!

**Comment by varopxndx** [comment]
> The binary traversal document is literally taken from https://github.com/azl397985856/leetcode/blob/master/thinkings/binary-tree-traversal.en.md while its in the creative common it should probably be mentioned.

Yes, it's well explained, I used it to review docs from there.
I just added the link to the reference.
Sorry for omitted it.
I hope this works.
Thank you!

**Comment by varopxndx** [comment]
Hi @chakeson 
Will my contribution be accepted?

**Comment by chakeson** [comment]
I'm not a maintainer I just reviewed to help. They probably wont prioritise something with a spam looking pl.

**Pull request merged**
