### PR TITLE
[ADD]: Improved tests in power recursion!

### PR DESCRIPTION
**Pull request by imSanko**
### Describe your change:

[ADD]: New test cases for all_combinations !

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?
* [x] Add test cases

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new Python files are placed inside an existing directory.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #9943".

### CODE REVIEW

**Comment by imSanko** [comment]
@cclauss can you have a look

**Review by cclauss — CHANGES_REQUESTED** [review]
Pull requests should either add/improve tests or should change the code.  This PR changes both the tests and the code.  This makes the PR much more difficult to review.

Please revert the change to the algorithm and the change of the filename.  Let's have this pull request JUST focus on improving the testing.

@tianyizheng02 Perhaps we need to talk more in CONTRIBUTING.md about not changing both code and tests in a single PR.

**Comment by imSanko** [comment]
> Pull requests should either add/improve tests or should change the code. This PR changes both the tests and the code. This makes the PR much more difficult to review.
> 
> Please revert the change to the algorithm and the change of the filename. Let's have this pull request JUST focus on improving the testing.
> 
> @tianyizheng02 Perhaps we need to talk more in CONTRIBUTING.md about not changing both code and tests in a single PR.

can you describe what I want me to do now?

**Comment by imSanko** [comment]
@cclauss can you check the change, cause I've made the as per your choice.

**Review by cclauss — APPROVED** [review]

**Comment by imSanko** [comment]
@cclauss can you please add #hacktoberfest-accepted label.

**Pull request merged**
