### PR TITLE
Fix data_structures/disjoint_set/disjoint_set.py

### PR DESCRIPTION
**Pull request by Alperencode**
Fixes: #4764 

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Alperencode** [comment]
Its actually not a hard change, i just change the if statement to work more properly and close the issue-#4764

**Review by poyea — COMMENTED** [review]
Please fix the failing test. 
```
FAILED data_structures/disjoint_set/disjoint_set.py::data_structures.disjoint_set.disjoint_set.test_disjoint_set
```
I assume this change to be the correct one. Is there anything wrong in the current tests?

**Comment by Alperencode** [comment]
I did not test it and actually i dont know how to test. I just fixed the code to close issue #4768. And that was not that complex i just changed the a few lines that shouldn't cause any problem.

**Review by Kornphan — APPROVED** [review]

**Comment by poyea** [comment]
@Alperencode It says something wrong with https://github.com/TheAlgorithms/Python/blob/master/data_structures/disjoint_set/disjoint_set.py#L57. Take an overall look and see what's wrong with the test? or you may change those 2 functions (+`find_python_set`) into one better function.

**Pull request closed without merging**
