### PR TITLE
Fix fetch anime and play and mark as unbroken

### PR DESCRIPTION
**Pull request by CaedenPH**
### Describe your change:
Fixes `fetch_anime_and_play.py` and marks as unbroken. All changes tested and type errors fixed

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by CaedenPH** [comment]
@cclauss This pr fixes a broken file. Do you mind reviewing?

**Review by tianyizheng02 — APPROVED** [review]
I ran your fixed file locally and I can confirm that it all works. I thought this file was broken because of 403 HTTP errors though (#8762). Did that problem resolve itself? Or does this PR fix that problem?

**Comment by CaedenPH** [comment]
@tianyizheng02 I think it was probably the anime (I think it was demon_slayer?) that failed due to perhaps being made private. Hence the change to the naruto anime

**Comment by CaedenPH** [comment]
Closing because I just realised that this pr fixes two files in one (also fixes broken `get_amazon_product_data`)

**Comment by tianyizheng02** [comment]
> I think it was probably the anime (I think it was demon_slayer?) that failed due to perhaps being made private. Hence the change to the naruto anime

@CaedenPH I just tried running the current (broken) fetch_anime_and_play.py file locally again and now it seems to be working again?? So the 403 HTTP error just kinda resolved itself... Could you try running the current file locally and see if it's also fixed for you?

**Comment by CaedenPH** [comment]
@tianyizheng02 Yep seems to work for me as well. This pr just mainly fixes type errors

**Pull request closed without merging**
