### PR TITLE
Cleanup Project Euler Problem 01

### PR DESCRIPTION
**Pull request by CMeza99**
### **Describe your change:**
* clean up docstrs
* add type hints
* improve coding-style
&nbsp;
* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

Part of Issues: #2786, #2510

### CODE REVIEW

**Review by aanchal-adk — APPROVED** [review]

**Comment by dhruvmanila** [comment]
Due to #2891, this becomes unnecessary. Thanks for your contribution!

**Comment by CMeza99** [comment]
@dhruvmanila the type hints was just one commit. the code clean up in the other 4 commits are not desired? FYI, I dropped the type hints commit and rebased off of master if you want reopen and merge these change.

**Comment by dhruvmanila** [comment]
Sure thing, remove the type hints commit and it will be good to go.
Also, why are you disabling `flake8`?

I cannot reopen as you rebased it.

**Comment by CMeza99** [comment]
will create a new PR. that `noqa` was a mistake 🤦

**Pull request closed without merging**
