### PR TITLE
createWordBreakProblem.py

### PR DESCRIPTION
**Pull request by Nandhika2003**
### Describe your change:

* [x] Add an algorithm?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by tianyizheng02** [comment]
This PR is plagiarized from this [GeeksforGeeks article](https://www.geeksforgeeks.org/word-break-problem-using-backtracking/).

**Comment by tianyizheng02** [comment]
@cclauss First case of plagiarism and we're not even a single day into Hacktoberfest. Should I create a new "spam" label for plagiarism and similar spam? From [Hacktoberfest's website](https://hacktoberfest.com/participation/#spam):
> Maintainers: label spammy requests “spam” and close them. PR/MRs labeled “spam” won’t count toward Hacktoberfest. Contributors with 2+ spammy PR/MRs are disqualified.

**Comment by cclauss** [comment]
Yes.  Let’s use both labels in the month of October but let’s use the plagiarism label all year long.

**Comment by tianyizheng02** [comment]
@cclauss I've created the "hacktoberfest spam" label. I encourage you to use it on spam/plagiarized PRs at your discretion.

**Pull request closed without merging**
