### PR TITLE
Remove duplicate is_prime related functions

### PR DESCRIPTION
**Pull request by paulosgf**
Fixes (#5434)

* Update ciphers.rabin_miller.py
         maths.miller_rabin.py

### Describe your change:
Remove duplicate is_prime related functions

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by paulosgf** [comment]
Hi @Kush1101!
Can you verify my PR, please!

**Comment by paulosgf** [comment]
Hi @Kush1101!

Can you review my PR #5892, please?

**Review by paulosgf — COMMENTED** [review]
@poyea, I solved the pro-commit hook problem and I'm submitting the changes that you requested, for review now.

**Comment by paulosgf** [comment]
@poyea, I guess that we have the egg and chicken problem here... This pre-commit workflow is breaking on this definition `primes: list[int] = []` and returns this error:
```
pyupgrade................................................................Passed
flake8...................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

project_euler/problem_007/sol2.py:76: error: "list" is not subscriptable, use "typing.List" instead
Found 1 error in 1 file (checked 1 source file)

codespell................................................................Passed
Validate filenames......................................................Skipped
```
Then, when I change the code, the pyupgrade module revert it to the original and the flake8 module returns the same error:
```
pyupgrade................................................................Failed
- hook id: pyupgrade
- duration: 2.83s
- exit code: 1
- files were modified by this hook

Rewriting project_euler/problem_007/sol2.py

flake8...................................................................Failed
- hook id: flake8
- duration: 9.87s
- exit code: 1

project_euler/problem_007/sol2.py:14:1: F401 'typing.List' imported but unused

```
But I didn't even need to move this part. When I fixed the other files, this new problem has arisen.
What now?

**Comment by poyea** [comment]
@paulosgf Let's check if this works?

**Comment by paulosgf** [comment]
Yes,  @poyea! Now it's Ok to merge.
Awaiting approval!

**Review by poyea — APPROVED** [review]
Thank you for your pull request!🤩

**Pull request merged**
