### PR TITLE
Added node count and leaf count

### PR DESCRIPTION
**Pull request by gupta2140**

### CODE REVIEW

**Comment by gupta2140** [comment]
Can someone why last 2 tests have failed?

**Comment by H-Darji** [comment]
@gupta2140 Check out the Travis CI logs.

**Comment by gupta2140** [comment]
The main error its showing is this:
E   ImportError: 

E   Importing the multiarray numpy extension module failed.  Most

E   likely you are trying to import a failed build of numpy.

E   If you're working with a numpy git repo, try `git clean -xdf` (removes all

E   files not under version control).  Otherwise reinstall numpy.

E   

E   Original error was: /home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/numpy/core/multiarray.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyTraceMalloc_Untrack


But i'm not getting it. Can you help me with it?

**Comment by frmatias** [comment]
Travis config was wrong i already fixed, try again, its because travis try download python 3.7, but travis can't find Python 3.7... try again

**Pull request closed without merging**
