### PR TITLE
simple_neural_network.py: Fewer forward propogations to speed tests

### LINKED ISSUE #9718: Speedup our eight slowest pytests (one at a time please)
### Feature description

At the end of our GitHub Actions `build` jobs, there is a list of the slowest ones.

Are there ways to speed up these tests without reducing our functionality or our code coverage?

Please only fix one algorithm per pull request.
* [ ] 16.64s call     neural_network/simple_neural_network.py::neural_network.simple_neural_network.forward_propagation
* [x] 6.15s call     backtracking/word_search.py::backtracking.word_search.word_exists
* [x] 4.61s call     digital_image_processing/test_digital_image_processing.py::test_local_binary_pattern
* [x] 2.59s call     backtracking/power_sum.py::backtracking.power_sum.backtrack
* [x] 2.19s call     machine_learning/xgboost_regressor.py::machine_learning.xgboost_regressor.main
* [x] 1.73s call     maths/prime_numbers.py::maths.prime_numbers.slow_primes
* [x] 1.43s call     backtracking/power_sum.py::backtracking.power_sum.solve
* [x] 1.00s call     other/dijkstra_bankers_algorithm.py::other.dijkstra_bankers_algorithm.BankersAlgorithm.main
================= 1506 passed, 25 warnings in 71.23s (0:01:11) =================

Also, those **25 pytest warnings** are worth fixing!!!

### PR DESCRIPTION
**Pull request by cclauss**
Closes #9718

### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by tianyizheng02** [comment]
At one point I tried to decrease the number of iterations like you did, but it didn't work. 100k iterations isn't even enough for the model to converge within 1 of the true value:
```
=================================== FAILURES ===================================
______ [doctest] neural_network.simple_neural_network.forward_propagation ______
029 Return the value found after the forward propagation training.
030 
031     >>> res = forward_propagation(32, 100_000)  # Was 10_000_000
032     >>> res > 31 and res < 33
Expected:
    True
Got:
    False
```
Like I've been saying, this implementation is _really_ suboptimal and should be rewritten.

**Comment by quant12345** [comment]
@cclauss make 1 million and the tests will pass. I tried to measure the time (not in dock tests) and it was 9 times faster.
`res = forward_propagation(32, 1_000_000)`
performance code:
```
if __name__ == "__main__":
    import doctest

    doctest.testmod()

    import datetime

    now = datetime.datetime.now()
    forward_propagation(32, 10000000)
    old = datetime.datetime.now() - now

    print('old_time', old)

    now = datetime.datetime.now()
    forward_propagation(32, 1000000)
    new = datetime.datetime.now() - now

    print('new_time', new)

    print('old/new', old/new)
```
Output:
```
old_time 0:00:07.447717
new_time 0:00:00.735285
old/new 10.129020719856927
```

**Comment by quant12345** [comment]
@cclauss I just checked 200_000, it also worked. I apologize for not checking it right away.

**Comment by cclauss** [comment]
Thanks, @quant12345 please keep trying to make it faster without becoming a flaky test.

`forward_propagation(32, 500_000) # Was 10_000_000` # puts the tests are < 1sec.
```
============================= slowest 10 durations =============================
1.32s call     web_programming/get_imdbtop.py::web_programming.get_imdbtop.get_imdb_top_movies
1.21s call     web_programming/fetch_anime_and_play.py::web_programming.fetch_anime_and_play.search_anime_episode_list
1.00s call     web_programming/fetch_anime_and_play.py::web_programming.fetch_anime_and_play.search_scraper
0.90s call     neural_network/simple_neural_network.py::neural_network.simple_neural_network.forward_propagation
0.85s call     web_programming/fetch_anime_and_play.py::web_programming.fetch_anime_and_play.get_anime_episode
0.83s call     dynamic_programming/integer_partition.py::dynamic_programming.integer_partition.partition
0.72s call     graphs/bidirectional_a_star.py::graphs.bidirectional_a_star.AStar
0.50s call     matrix/count_negative_numbers_in_sorted_matrix.py::matrix.count_negative_numbers_in_sorted_matrix.generate_large_matrix
0.37s call     matrix/count_negative_numbers_in_sorted_matrix.py::matrix.count_negative_numbers_in_sorted_matrix.count_negatives_brute_force
0.37s call     dynamic_programming/matrix_chain_multiplication.py::dynamic_programming.matrix_chain_multiplication.matrix_chain_order
================== 1749 passed, 1 warning in 72.96s (0:01:12) ==================
```

**Comment by cclauss** [comment]
@tianyizheng02 For the `web_programming` jobs, should we consider replacing requests with the plug-compatible [`httpx`](https://pypi.org/project/httpx) and encouraging contributors to use asyncio for web interactions?  I doubt it would speed up the tests but it would continue to push contributors to learn new skills.  We currently have 35 files that `import requests`.

**Comment by quant12345** [comment]
> Thanks, @quant12345 please keep trying to make it faster without becoming a flaky test.
> 
> `forward_propagation(32, 500_000) # Was 10_000_000` # puts the tests are < 1sec in 4th slowest.
> 
Now I tried 400_000 by calling the function 100 times, sometimes the tests fail. At 500_000 I tried 1000, all tests passed(that is, I also think 500_000 is close to the optimal number).
```
if __name__ == "__main__":
    import doctest

    doctest.testmod()

    for i in range(100):
        doctest.run_docstring_examples(forward_propagation, globals())
```

**Comment by cclauss** [comment]
Nice! Could you please try `450_000` before I merge this?

**Comment by cclauss** [comment]
LGTM.  @tianyizheng02

**Pull request closed without merging**
