### PR TITLE
add reverse_bits.py

### PR DESCRIPTION
**Pull request by ayushbisht2001**
### **Describe your change:**
I have added an algorithm which reversed the bits of any 32 bit interger . 

* [x] Add an algorithm?
 

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by ayushbisht2001** [comment]
@algorithms-keeper review-all

**Comment by ayushbisht2001** [comment]
@algorithms-keeper review

**Comment by ayushbisht2001** [comment]
@algorithms-keeper review

**Comment by ayushbisht2001** [comment]
Why some of the checks  are failing?? ..  I didn't get, why is it happening..

**Comment by ayushbisht2001** [comment]
@algorithms-keeper review-all

**Comment by ayushbisht2001** [comment]
@xcodz-dot  , hey can u please help me ..... what's wrong with my PR. Will u please review it .

**Comment by xcodz-dot** [comment]
spelling mistakes
```
bit_manipulation/reverse_bits.py:3: interger ==> integer
bit_manipulation/reverse_bits.py:73: shif ==> shift
```

code format (run the below commands at root of repo after fixing the spelling mistakes)
```
pip install pre-commit
pre-commit run -a (This might show that it has error but this has fixed all the format issues, you can rerun it for your convenience)
```

then upload the changes

**Comment by xcodz-dot** [comment]
> @algorithms-keeper review

this progress is automatic and runs on every commit or changes you make so you do not need to run this command again and again.

**Comment by ayushbisht2001** [comment]
Capture

@xcodz-dot , I have tried everything which u suggest me , but withal some checks are still failing. Kindly please help me,... how to resolve all these errors.

**Comment by xcodz-dot** [comment]
> Capture
> 
> @xcodz-dot , I have tried everything which u suggest me , but withal some checks are still failing. Kindly please help me,... how to resolve all these errors.

do not worry about those errors, just commit and upload the local changes made by that

**Comment by xcodz-dot** [comment]
Ok let me do this here, i will fix all the errors in a while now

**Comment by ayushbisht2001** [comment]
Thank you  @xcodz-dot

**Comment by xcodz-dot** [comment]
Oh and you will have to remove one of the files as only 1 file per PR is allowed, to submit the second file create a new PR after this one gets accepted. Until then keep the second file somewhere on your local machine

**Comment by ayushbisht2001** [comment]
@xcodz-dot , Now, is it good to go?

**Comment by xcodz-dot** [comment]
yes, please wait for now

**Comment by xcodz-dot** [comment]
https://github.com/ayushbisht2001/Python/pull/1

**Comment by ayushbisht2001** [comment]
@xcodz-dot,  please review my PR. Is everything alright in this PR, have I not made this upto  code standard??

**Review by xcodz-dot — APPROVED** [review]
I am not a maintainer here so my review doesn't do much. i will leave the merging part for @dhruvmanila and @cclauss

**Review by AnupKumarPanwar — APPROVED** [review]

**Pull request merged**
