### PR TITLE
refactor: move import pytest line of blockchain algs under "main" section.

### PR DESCRIPTION
**Pull request by Jay9z**
### **Describe your change:**
pytest package is not used by these algorithms. it is helpful when there is a need for testing.
it is reasonable to move these "import pytest" line of blockchain algs under "main" section.

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
For the commit message, please study how markdown check boxes work
https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/

**Comment by Jay9z** [comment]
I did not check the fouth item of checklist, because there are multiple files with same improvement. Is it the reason why it failed?  I don't understand the details of 'Travis CI - Pull Request checks' quite well.

**Comment by Jay9z** [comment]
I got you point. I used the wrong mark to check the box. It has been revised.

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/Travis_CI_tests_are_failing.md

**Pull request merged**
