### PR TITLE
Add FFT

### PR DESCRIPTION
**Pull request by nhuzaa**
### Describe your change:
Fast Fourier Transform (FFT) Implementation in Python

This Python script provides a basic demonstration of the Fast Fourier Transform (FFT) algorithm without the use of external libraries like NumPy. The FFT is a mathematical algorithm used to transform a signal from the time domain to the frequency domain, revealing its frequency components.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by Shreya123714** [comment]
Hey i can help you...

**Comment by nhuzaa** [comment]
@Shreya123714  Added you as collaborator in my fork

**Comment by Shreya123714** [comment]
hey i am not able to find you fast-fourier-transform.py?? where is it

**Comment by Shreya123714** [comment]
@nhuzaa hey please see this , 2 checks have been passed, build failed due to zero division error, please help identify that...in for loop maybe

**Comment by Shreya123714** [comment]
@nhuzaa  all check passed.

**Comment by cclauss** [comment]
https://github.com/search?q=repo%3ATheAlgorithms%2FPython%20Fourier&type=code

**Comment by cclauss** [comment]
Closing require_type_hints PRs to prepare for Hacktoberfest 2024

**Pull request closed without merging**
