### PR TITLE
New and easy quicksort Algo

### PR DESCRIPTION
**Pull request by Deepak14Jain**
### Describe your change:

Hello, I am new to open source..have added a new and easy quick sort algorithm

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by imSanko — CHANGES_REQUESTED** [review]
Try Running `pre commit's `

**Comment by Deepak14Jain** [comment]
> Try Running `pre commit's `

Hey! new to this and to be frank dont know what u talking about

**Review by imSanko — CHANGES_REQUESTED** [review]
Try reading `CONTRIBUTING.md` then after follow the mentioned instructions:

1.  `python3 -m pip install pre-commit  # only required the first time
pre-commit install`

2. `pre-commit run --all-files --show-diff-on-failure`

While, Don't forget to All submissions will need to pass the test ruff . before they will be accepted so if possible, try this test locally on your Python file(s) before submitting your pull request.

`python3 -m pip install ruff  # only required the first time
ruff`

Also, Please consider running [psf/black](https://github.com/python/black) on your Python file(s) before submitting your pull request. This is not yet a requirement but it does make your code more readable and automatically aligns it with much of [PEP 8](https://www.python.org/dev/peps/pep-0008/). There are other code formatters (autopep8, yapf) but the black formatter is now hosted by the Python Software Foundation. To use it,

`python3 -m pip install black  # only required the first time
black`

**Comment by tianyizheng02** [comment]
As already stated, please read `CONTRIBUTING.md` before you contribute. This was made clear in your own PR description and in the repo's README.

In addition, please make sure that the algorithm that you're contributing isn't already in the repo. We already have multiple implementations of quick sort: https://github.com/search?q=repo%3ATheAlgorithms%2FPython%20quick_sort&type=code

Your implementation seems to be an implementation of 3-way quick sort, which we already have [here](https://github.com/TheAlgorithms/Python/blob/e3fa014a5ab4887f93aae7bb193b152bb155323a/sorts/quick_sort_3_partition.py).

**Pull request closed without merging**
