### PR TITLE
Sorting in python

### PR DESCRIPTION
**Pull request by hkp27299**
Added recursive bubble sort for dynamic inputs

### CODE REVIEW

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/Travis_CI_tests_are_failing.md

**Comment by hkp27299** [comment]
Check again removed input()

**Comment by hkp27299** [comment]
Now build is running well

**Comment by hkp27299** [comment]
Done all checks.Please review it. Thank You

**Pull request closed without merging**
