### PR TITLE
Update LICENSE.md with correct year

### PR DESCRIPTION
**Pull request by 4pt1y**
Changed year to 2023 on the license--I'm new to github and the open source community as a whole so I know this is a simple change but thought it would be an appropriate place for me to start.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by 4pt1y** [comment]
Hmm, it failed one of the checks but I'm not sure how that is possible...all I changed was the license year. Let me know what I can do to resolve this. Thanks for the opportunity to contribute!

**Comment by tianyizheng02** [comment]
Hi @4pt1y, thanks for your contribution! The build failure comes from a failing unit test in another file, and this is a known ongoing issue. We can accept and merge your PR once we that's dealt with.

**Comment by 4pt1y** [comment]
@tianyizheng02 Thanks so much!

**Comment by cclauss** [comment]
https://opensource.stackexchange.com/questions/6389/how-do-the-years-specified-in-a-copyright-statement-work

**Comment by 4pt1y** [comment]
Thanks for the explanation @cclauss , I'll look for other ways to contribute. Just to be sure, you are okay with the license saying 2016-2022 for the copyright, correct? I'm quoting the link you sent me to: 

> It is a common convention that the notice lists all years where new versions were published. This reflects that different parts of the project were published at different times. Since the list of years can get rather long, it is common to collapse consecutive years to a range: “2016, 2017, 2018” is often written as “2016–2018”. **If in doubt, always use the most recent year.** So “2018” would also be correct.

Thanks for your work and taking the time to do what you do.

**Comment by cclauss** [comment]
Yes.  I think we are good as is with `2016-2022` but we look forward to future contributions from you.  Thanks!

**Comment by 4pt1y** [comment]
@cclauss sounds good. Thanks!

**Pull request closed without merging**
