### PR TITLE
add project euler problem 85

### PR DESCRIPTION
**Pull request by osoba**
Adds Project Euler problem 85 solution in Python  #2695.

### CODE REVIEW

**Comment by osoba** [comment]
I have no idea why that test failed or how to fix it sorry.

**Comment by peteryao7** [comment]
There may be some formatting issues. Try running the commands under coding style from the [contributing guidelines](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) and fixing any errors there.

**Comment by osoba** [comment]
That was it (format change from double spaces to tabs), thanks.

**Review by dhruvmanila — COMMENTED** [review]
### Announcement:

@osoba

*This message is sent to all pull requests which are **OPEN, NOT MERGED, not containing 'wontfix' label and contains 'Project Euler' or 'Project' or 'Euler' (case doesn't matter) in their title**. If this message doesn't apply to your pull request, please ignore this.*

### Message:

This is to notify all the users submitting a pull request for the Project Euler solution that the [README.md](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) file has been updated with all the style requirements necessary for the directory and solution files. ***Please read through it and make all the necessary changes required to your submission.***

**Pull request closed without merging**
