### PR TITLE
new folders, tree algorithms and sol11.py of project_euler

### PR DESCRIPTION
**Pull request by itsvinayak**

### CODE REVIEW

**Comment by cclauss** [comment]
This PR is trying to do too many unrelated things across multiple directories and adds a filename that fails our validity tests.
https://travis-ci.org/TheAlgorithms/Python/jobs/568913710#L587

To ease the review process, can this PR be split into multiple PRs that each only touch a single directory?

**Comment by cclauss** [comment]
Please rebase this PR on the current master.  This PR currently adds 1,238 lines of code and much of that looks like it is duplicate to code already in the repo but it is impossible to tell for sure without a rebase.

**Comment by itsvinayak** [comment]
> Please rebase this PR on the current master. This PR currently adds 1,238 lines of code and much of that looks like it is duplicate to code already in the repo but it is impossible to tell for sure without a rebase.

I am new to git can you help me with this rebase thing I use git rebase on master and then commit it. it shows nothing to commit, is it ok or I should do something else.

**Comment by cclauss** [comment]
I do the seven commands at
https://devguide.python.org/gitbootcamp/#syncing-with-upstream

**Pull request closed without merging**
