### PR TITLE
Added censor code

### PR DESCRIPTION
**Pull request by meg-1**
### **Describe your change:**

Added code which censors a word from a string of text

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by onlinejudge95** [comment]
@meg-1 the file is empty, are you sure you didn't miss anything

**Review by onlinejudge95 — CHANGES_REQUESTED** [review]
@meg-1 the file seems to be empty. Are you sure you didn't miss anything?

**Comment by meg-1** [comment]
> @meg-1 the file seems to be empty. Are you sure you didn't miss anything?

Oh, sorry, yes, I think I might have missed something while commiting it, I was sure the code was there. I will check it out as soon as I can and do another commit. Thank you for notifiying me on this!

**Review by onlinejudge95 — CHANGES_REQUESTED** [review]
This code can not be accepted as we expect you to encapsulate the implementation of the algorithm in a unified API, meaning we expect you to implement a function that given some arguments does something.

**Comment by meg-1** [comment]
> ent a function that given some arguments does something.

Understood, thank you for your feedback, I will edit the code, put it into a function, and then do another commit as soon as I can.

**Comment by dhruvmanila** [comment]
For testing purposes...

**Comment by dhruvmanila** [comment]
Did anyone approve the workflow runs or were they actually approved by our GitHub action? I can't seem to find any way to know this lol

**Comment by onlinejudge95** [comment]
> Did anyone approve the workflow runs or were they actually approved by our GitHub action? I can't seem to find any way to know this lol

I did for this PR

**Review by 9harshit — COMMENTED** [review]
instead of looping txt_lst to recreate the sentence use :

`txt = " "`
`txt = txt.join(txt_lst)`

**Comment by onlinejudge95** [comment]
> instead of looping txt_lst to recreate the sentence use :
> 
> `txt = " "`
> `txt = txt.join(txt_lst)`

`txt = " ".join(txt_lst)`

**Comment by dhruvmanila** [comment]
Please read the Contributing guidelines before opening a PR. Thank you for your cooperation.

**Pull request closed without merging**
