### PR TITLE
writing test for min cost string conversion

### LINKED ISSUE #2128: Dev sprint ideas: More tests, type hints and less complexity
currently, some of the programs use static type checking like this [program](https://github.com/TheAlgorithms/Python/blob/master/dynamic_programming/fast_fibonacci.py) but some of the programs did not use static typing.

it's a good practice to use static typing as it makes code more clear and readable, should we make it a standard for this repository.we can use [mypy](http://mypy-lang.org/) for testing code 

[more on static typing](https://medium.com/@ageitgey/learn-how-to-use-static-type-checking-in-python-3-6-in-10-minutes-12c86d72677b)
 
thank you

### Dev sprint ideas:
* [ ] [Add tests to Python files with <10% test coverage.](https://github.com/TheAlgorithms/Python/issues/2128#issuecomment-645231020)
* [ ] [Add static typing to functions and methods.](https://github.com/TheAlgorithms/Python/issues/2128)
* [ ] [Set `flake8 --max-complexity=15`](https://github.com/TheAlgorithms/Python/issues/2128#issuecomment-645190839) (Ensure files have strong tests ___before___ refactoring).  Test results from #2139...
    * [ ] ./boolean_algebra/quine_mc_cluskey.py:82:1: C901 'selection' is too complex (17)
    * [ ] ./digital_image_processing/edge_detection/canny.py:20:1: C901 'canny' is too complex (17) @lighttxu
    * [ ] ./graphs/minimum_spanning_tree_prims.py:5:1: C901 'PrimsAlgorithm' is too complex (21)
        * [ ] Add doctests aligned with https://en.wikipedia.org/wiki/Prim%27s_algorithm
        * [ ] In a ___separate___ PR reduce the McCabe complexity
    * [ ] ./linear_algebra/src/polynom-for-points.py:1:1: C901 'points_to_polynomial' is too complex (23) @nic-dern
    * [ ] ./machine_learning/linear_discriminant_analysis.py:251:1: C901 'main' is too complex (25)
    * [x] ./hashes/hamming_code.py:71:1: C901 'emitterConverter' is too complex (16) #2140
    * [x] ./hashes/hamming_code.py:153:1: C901 'receptorConverter' is too complex (20) #2140
    * [x] ./project_euler/problem_551/sol1.py:20:1: C901 'next_term' is too complex (16) #2141

### PR DESCRIPTION
**Pull request by meysam81**
also modified the main script to be testable

I also had to change the line that handled `delete` section

Fixes #2128

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by meysam81** [comment]
@cclauss 
Will you consider this PR please?

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/issues/2510#issuecomment-701540969

**Comment by meysam81** [comment]
@poyea 
Hi there :sweat_smile:

**Comment by poyea** [comment]
Thanks. Could you also add some type hints for these functions?

**Comment by meysam81** [comment]
@poyea 
I only merged the master into the code :neutral_face: 
It has been a long time since I opened this pull request and its obvious that a lot has changed since.
Could you please reopen it?

**Comment by dhruvmanila** [comment]
This pull request should not be reopened. Also, you should rebase instead of merging, as you can see you have added 436 files in this pull request. So, whatever you were trying to submit, please open a new pull request for it after branching off from the latest master.

**Pull request closed without merging**
