### PR TITLE
Fix: Corrected test. List in test must be ordered.

### PR DESCRIPTION
**Pull request by NumberPiOso**
What the title says.

### **Describe your change:**

* [ ] Add an algorithm?
* [X] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [ X All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Awesome! Thanks for pointing this out. Can you add a few more random tests by using `range` and different `step` values? Maybe we can use `sorted(random.choices(range(-n, +n), k=100))` to select 100 pseudo-random numbers from a list of 1000 numbers ranging from negative to positive.

**Comment by NumberPiOso** [comment]
@poyea are you working in this one? or should I propose the next commit ?

**Comment by poyea** [comment]
You may consider adding the test cases suggested. I'll review it once you've done.

**Comment by NumberPiOso** [comment]
@dhruvmanila could you please elaborate a little more that idea?
In particular,  how do I know in advance if the number is in the list.

```
>>> n = 500
>>> print(binary_search(sorted(random.choices(range(-n, +n), k=100)), 100))
>>> ?
```

**Comment by dhruvmanila** [comment]
Ah, did not see that. Sorry about that. A better option would be to just use `random(range(-100, 100, <step_value>))` or something like that. Put whichever step value you think would be good enough.

**Review by dhruvmanila — APPROVED** [review]
Looks good! Thank you for your contribution!

**Pull request merged**
