### PR TITLE
Added minimum cost path algorithm

### PR DESCRIPTION
**Pull request by ruppysuppy**
### **Describe your change:**

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
What is the use case for this algorithm?  What would be the real world value of solving this problem?

**Comment by ruppysuppy** [comment]
I encountered it a long time back as a problem stating something like: "There is a gold digger travelling from the top left of the grid to the bottom right, help him maximize the gold he encounters on the path". Another variant of the problem can be considered quite useful, __minimum path sum for matrix__ (can be done by changing the max of the top and left to the min of the two). If we, consider the path of a traveler in a N x M grid, the value for in the matrix can be considered accommodation cost and we are trying to minimize it.

**Comment by ruppysuppy** [comment]
Let me know if its not worth adding. I'll close it. Planning to LRU Cache, but I can't understand where (which folder) I should add it in. Could you please tell me @cclauss ?

**Comment by itsvinayak** [comment]
> Let me know if its not worth adding. I'll close it. Planning to LRU Cache, but I can't understand where (which folder) I should add it in. Could you please tell me @cclauss ?

@ruppysuppy  please add a description for this algorithm 
if I am not wrong this problem is the same as[ this](https://www.geeksforgeeks.org/min-cost-path-dp-6/)

**Comment by ruppysuppy** [comment]
@itsvinayak should I change it to minimum cost path from maximum cost path? I'll add the description for the problem

**Pull request merged**
