### PR TITLE
Update rod_cutting.py

### PR DESCRIPTION
**Pull request by SandersLin**
A hopefully clearer implementation without dependence on global variables.

### CODE REVIEW

**Comment by cclauss** [comment]
Nice!  Please consider adding a doctest.

**Comment by SandersLin** [comment]
Thanks! Added doctests.

**Comment by cclauss** [comment]
Doctests for length = -1, length = 3.2, prices = []

**Comment by SandersLin** [comment]
Modified doctests and type hints. 
I wonder when doing input validation is too much though.  For example, when the type hint and documentation clearly states  prices should be List[int], but some bloke passed in list of strings, the author shouldn't be responsible.

**Pull request merged**
