### PR TITLE
added Eulerian path and circuit for undirected graph

### PR DESCRIPTION
**Pull request by Reshad-Hasan**

### CODE REVIEW

**Comment by Reshad-Hasan** [comment]
Do you want me to add the complexity in the code as comments?

**Comment by Reshad-Hasan** [comment]
> Please add time complexity and space complexity, else LGTM.

Do you want me to add the complexity in the code as comments?

**Comment by anksont** [comment]
you can make this changes 
def check_circuit_or_path(graph, max_node):
    odd_degree = 0
    odd_node = 1 # 
    for i in range(max_node):
        if i not in graph.keys():
            continue
        if len(graph[i]) % 2 == 1:
            odd_degree += 1
            odd_node = i
    if odd_degree == 0:
        return 1, odd_node
    if odd_degree == 2:
        return 2, odd_node
    return 3, odd_node

**Comment by Reshad-Hasan** [comment]
> you can make this changes
> def check_circuit_or_path(graph, max_node):
> odd_degree = 0
> odd_node = 1 #
> for i in range(max_node):
> if i not in graph.keys():
> continue
> if len(graph[i]) % 2 == 1:
> odd_degree += 1
> odd_node = i
> if odd_degree == 0:
> return 1, odd_node
> if odd_degree == 2:
> return 2, odd_node
> return 3, odd_node

yes this will reduce some checks, thank you

**Pull request closed without merging**
