### PR TITLE
Hacktoberfest 2020: Added new solution for Project Euler Problem 16 & other minor changes

### PR DESCRIPTION
**Pull request by Melvin-Abraham**
### **Describe your change:**

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**

* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Melvin-Abraham** [comment]
Any status on this PR?

**Review by dhruvmanila — COMMENTED** [review]
### Announcement:

@Melvin-Abraham

*This message is sent to all pull requests which are **OPEN, NOT MERGED, not containing 'wontfix' label and contains 'Project Euler' or 'Project' or 'Euler' (case doesn't matter) in their title**. If this message doesn't apply to your pull request, please ignore this.*

### Message:

This is to notify all the users submitting a pull request for the Project Euler solution that the [README.md](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) file has been updated with all the style requirements necessary for the directory and solution files. ***Please read through it and make all the necessary changes required to your submission.***

**Comment by Melvin-Abraham** [comment]
@dhruvmanila I read the new contribution guidelines for "Project Euler" and proposed following change(s) as per this PR:

- Added default value for positional argument of the function `solution()`

### Checklist

- [x] Please maintain consistency in project directory and solution file names
- [x] Please provide a link to the problem and other references, if used, in the module-level docstring
- [x] All imports should come after the module-level docstring **(Didn't require)**
- [x] When the `solution` function is called without any arguments like so: `solution()`, it should return the answer to the problem **(Proposed Change)**
- [x] ...the main solution function, should have `doctest` in the function docstring along with a brief statement mentioning what the function is about

**Comment by dhruvmanila** [comment]
Thank you for your contribution but we are only accepting solutions to problems which do not exist in this repository.

**Comment by dhruvmanila** [comment]
The solution to this problem already exist in this repository, so closing the PR.

**Pull request closed without merging**
