### PR TITLE
A divide and conquer method in finding the maximum difference pair

### PR DESCRIPTION
**Pull request by choyiny**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by xcodz-dot** [comment]
@dhruvmanila @poyea @Kush1101, Please check this (Ready to be merged)

**Review by xcodz-dot — APPROVED** [review]
Good Work

**Review by poyea — COMMENTED** [review]
Please add a main function:
```python
if __name__ == "__main__":
   import doctest
  
   doctest.testmod()
   main()

**Comment by xcodz-dot** [comment]
@poyea check this out (Changes made)

**Comment by choyiny** [comment]
See if this is sufficient for merge, thanks.

**Review by poyea — APPROVED** [review]
I think the value the function returns is a pair of 2 array values, right? You may modify the comment if that's the case. Thank you for your pull request!🤩

**Comment by choyiny** [comment]
> I think the value the function returns is a pair of 2 array values, right? You may modify the comment if that's the case. Thank you for your pull request!🤩

The return is a 2-tuple of integers, actually.

**Comment by poyea** [comment]
> > I think the value the function returns is a pair of 2 array values, right? You may modify the comment if that's the case. Thank you for your pull request!🤩
> 
> The return is a 2-tuple of integers, actually, which is the comment.

Yeah I misread something.

**Pull request merged**
