### PR TITLE
add rsa implementation

### PR DESCRIPTION
**Pull request by eternalflow**
warning: it is not secure. created it for educational purposes only
did it about a year ago. 
it uses:
- Blub Blub Shub pseudo-random number generator (tools.py:31)
https://en.wikipedia.org/wiki/Blum_Blum_Shub
- prime number generation on top of Miller Rabin Test (tools.py:185)
https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test

tested with help of http://asymcryptwebservice.appspot.com (i used requests library for GET requests, do "pip install requests" if you don't have it)

### CODE REVIEW

**Comment by dynamitechetan** [comment]
Please make sure that all CI checks are passed

**Comment by eternalflow** [comment]
@dynamitechetan sorry, I use python 2.7, could you help me make it portable?

**Comment by AnupKumarPanwar** [comment]
you can 2to3 to portyour 2.x code to 3.x code 
https://docs.python.org/2/library/2to3.html

**Comment by H-Darji** [comment]
@eternalflow do pull request again after applying required changes that are necessary to pass CI build.

**Pull request closed without merging**
