### PR TITLE
Fermat's little theorem

### PR DESCRIPTION
**Pull request by Erfaniaa**

### CODE REVIEW

**Comment by poyea** [comment]
LGTM. But could you provide a reference to the theorem (the corollary)?

**Comment by sarthak77** [comment]
Time complexity is for binary exponentiation vs normal exponentiation so can be removed from top and can be written as a note below

**Comment by Erfaniaa** [comment]
Should I put this URL in the code?

https://en.wikipedia.org/wiki/Fermat%27s_little_theorem

**Comment by Erfaniaa** [comment]
Please see the new changes that I've made.

**Comment by sarthak77** [comment]
Looks good

**Comment by poyea** [comment]
Thank you for your pull request!🤩

**Pull request merged**
