### PR TITLE
Add tests and type hints to hill cipher

### PR DESCRIPTION
**Pull request by bharath5412**
### **Describe your change:**
Added doctests to the hill cipher algorithm and added type hints. This addresses the issue the #1788 . 

There was a previous attemp #1862 to fix the issue but it wasn't merged.

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
@bharath5412 I did not notice this before but these changes raise [a ton of pytest warnings](https://travis-ci.com/github/TheAlgorithms/Python/builds/166624938#L720-L764).  Would you be willing to create a new pull request that eliminates these warnings?  Given how little of numpy is actually used, would it be easy to remove the dependency on numpy?  Thanks.

**Comment by cclauss** [comment]
@poyea fixed the warning in https://github.com/TheAlgorithms/Python/pull/1997/commits/36c01f965b3e877d5707887f2008dd5a12005843 but I still wonder if it would be useful to remove the dependency on numpy?

**Comment by bharath5412** [comment]
I can work on removing the dependency on numpy. But the code uses matrix operations such as determinant and inversion of a matrix. They themselves are slightly complex piece of codes. @cclauss  do you think that the dependency should be removed? I can make a PR to remove the numpy dependency.

**Comment by cclauss** [comment]
If you believe that we are using sufficient functionality then we can just leave things as they are.

**Comment by bharath5412** [comment]
Cool. I'll check how complex the methods are. If they are not complex, I'll implement and do a PR.

**Pull request merged**
