### PR TITLE
Added algorithm for binary tree right view

### PR DESCRIPTION
**Pull request by susmith98**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by susmith98** [comment]
Hey @cclauss / @poyea :). Can you please review and merge this PR? Please let me know if any changes are to be made.

**Comment by poyea** [comment]
How about combine this with #2757 and #2733?

**Comment by susmith98** [comment]
It is recommended to have different PR's for different Algorithms in contribution guidelines. Even though this is similar to those Algorithms, still this need to be a separate file right?

**Comment by susmith98** [comment]
Hey @cclauss @poyea, Any remarks regarding the [above](https://github.com/TheAlgorithms/Python/pull/2760#issuecomment-703497893) comment?

**Comment by poyea** [comment]
But I find these three are very similar... I'll wait for other's comments ATM.

**Comment by susmith98** [comment]
@cclauss Can you please review and merge this?

**Comment by cclauss** [comment]
@poyea is correct. One file with 3 related functions.

**Comment by cclauss** [comment]
Please do not @mention maintainers.  This repo has almost 300 open PRs.

**Pull request closed without merging**
