### PR TITLE
lorenz -> lorentz

### PR DESCRIPTION
**Pull request by rohanr18**
### Describe your change:

correct spelling according to: https://en.wikipedia.org/wiki/Lorentz_transformation

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by cclauss — APPROVED** [review]

**Comment by cclauss** [comment]
Please add the URL https://en.wikipedia.org/wiki/Lorentz_transformation to the docstring in a separate PR.

**Comment by rohanr18** [comment]
It's already there, somewhere at the bottom.

**Comment by cclauss** [comment]
I was thinking that they could not spell it wrong if they included the wiki URL.

**Comment by rohanr18** [comment]
fair enough

**Comment by rohanr18** [comment]
while I have you, do you mind having a quick look at #6441 and #6442?

**Pull request merged**
