### PR TITLE
Update basic_graphs.py

### PR DESCRIPTION
**Pull request by karthikeyansa**
missing return statement line no:223.

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by itsvinayak** [comment]
@poyea is this seems ok 
now it returns the map with the path values

**Comment by cclauss** [comment]
> Prim's algorithm should return a tree.

**Comment by cclauss** [comment]
@poyea Please re-review.

**Comment by poyea** [comment]
@karthikeyansa @cclauss @itsvinayak I think we can add some test graphs to this file, as it is quite difficult to see the expected output. An input graph for `prim` should be of the form 
```
{ "a" : [["d",1]], "b" : [["c",2], ["e",2]],"c" : [["a",1], ["b",2], ["d",3], ["e",2]],"d" : [["c",2]],"e" : [["c",1], ["b",3]],"f" : []}
```
However, `Dictionary of edges` underspecifies the requirement of this argument.

**Pull request merged**
