### PR TITLE
Converted tests into doctests

### PR DESCRIPTION
**Pull request by AksharGoyal**
### Describe your change:

Turned tests into doctests in the Boolean Algebra section for consistency and as an improved way of testing.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?
* [x] Changed code

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by tianyizheng02 — CHANGES_REQUESTED** [review]
Could you delete the code instead of just commenting it out?

**Comment by AksharGoyal** [comment]
Absolutely! I commented the code in case they would be needed in future.

**Comment by AksharGoyal** [comment]
@tianyizheng02 Hi, would you recommend creating another pull request or should I delete the currently forked repo and fork again to make changes?

**Review by tianyizheng02 — APPROVED** [review]

**Comment by cclauss** [comment]
I don't particularly appreciate removing code without good reason.
```python
def test_and_gate() -> None:
    """
    Tests the and_gate function
    """
    assert and_gate(0, 0) == 0
    assert and_gate(0, 1) == 0
    assert and_gate(1, 0) == 0
    assert and_gate(1, 1) == 1
```
can be run by our GitHub Actions build step just by adding one line...
```python
def test_and_gate() -> None:
    """
    Tests the and_gate function
    >>> test_and_gate() 
    """
    assert and_gate(0, 0) == 0
    assert and_gate(0, 1) == 0
    assert and_gate(1, 0) == 0
    assert and_gate(1, 1) == 1
```

**Pull request merged**
