### PR TITLE
feat: Add mypy configuration file

### PR DESCRIPTION
**Pull request by dhruvmanila**
### **Describe your change:**

* [x] New feature
* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by cclauss — COMMENTED** [review]
If we only run mypy in our GitHub Action then I would be opposed to storing configuration in two separate files.  However if we add mypy to https://github.com/TheAlgorithms/Python/blob/master/.pre-commit-config.yaml then I would be for this change.

**Comment by dhruvmanila** [comment]
For now, we are only using `ignore-missing-imports` flag which is available for the CLI `mypy` but some flags are not available and as we get more stricter in the future we would need to have additional flags and I would prefer it to be added in its own configuration file.

Also, when we test `mypy` locally we would not need to pass any flags and directly run `mypy` as: `$ mypy .` which is better and shorter to type than `$ mypy --ignore-missing-imports --warn-unused-imports --disallow-untyped-defs ...`

**Comment by dhruvmanila** [comment]
Hmm, weird. It seems that all of the builds are stuck from my last commit to master: https://github.com/TheAlgorithms/Python/actions

**Comment by cclauss** [comment]
Something strange is happening...

**Comment by dhruvmanila** [comment]
I have reported to GitHub. Lets see what's going on.

**Review by cclauss — APPROVED** [review]
LGTM

**Pull request merged**
