### PR TITLE
Fixes for ruff rule RUF012

### PR DESCRIPTION
**Pull request by cclauss**
### Describe your change:
% `ruff rule RUF012`
# mutable-class-default (RUF012)

Derived from the **Ruff-specific rules** linter.

## What it does
Checks for mutable default values in class attributes.

## Why is this bad?
Mutable default values share state across all instances of the class,
while not being obvious. This can lead to bugs when the attributes are
changed in one instance, as those changes will unexpectedly affect all
other instances.

When mutable value are intended, they should be annotated with
`typing.ClassVar`.

## Examples
```python
class A:
    mutable_default: list[int] = []
```

Use instead:
```python
from typing import ClassVar


class A:
    mutable_default: ClassVar[list[int]] = []
```

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
I think we should wait. We've received a few issues with the latest changes to this rule.

**Comment by cclauss** [comment]
All new PRs are failing.  Should we ignore RUF012 in pyproject.tml?

**Comment by dhruvmanila** [comment]
> All new PRs are failing. Should we ignore RUF012 in pyproject.tml?

Yeah, that's fine for now.

**Comment by cclauss** [comment]
Closing in favor of #8802

**Pull request closed without merging**
