### PR TITLE
Fix broken links to Gitter community

### PR DESCRIPTION
**Pull request by ChVeen**
### Describe your change:
The link <https://gitter.im/TheAlgorithms> as used in the `README.md` and `CONTRIBUTING.md` files is invalid and returns the error `404 Not Found`.
I fixed the link to the working version <https://gitter.im/TheAlgorithms/community>.

This PR fixes issue #8197

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by CaedenPH — APPROVED** [review]
Good spot

**Comment by ChVeen** [comment]
Hi @CaedenPH, thanks. Unfortunately, ruff produced errors and I did not touch even a single Python file, just markdown files. What to do about this? My master was already synced while branching.

**Comment by CaedenPH** [comment]
> Hi @CaedenPH, thanks. Unfortunately, ruff produced errors and I did not touch even a single Python file, just markdown files. What to do about this? My master was already synced while branching.

Yep not a problem, must be a problem with the workflows

**Comment by ChVeen** [comment]
Dear @cclaus, I solved this issue 17h ago and KaixLina "copied" this 10h ago. Well...

**Review by cclauss — APPROVED** [review]
This PR uses a better URL so I have reopened and I will merge it when all tests pass.

**Comment by cclauss** [comment]
Thanks @ChVeen

**Pull request merged**
