### PR TITLE
Remove the `scripts/project_euler_answers.json` file from the Git history.

### PR DESCRIPTION
**Pull request by Panquesito7**
### **Describe your change:**

- Remove the `scripts/project_euler_answers.json` file from the Git history using [BFG](https://github.com/rtyley/bfg-repo-cleaner).
  - This has re-written some of the commits since this file was added.

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* ~[ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.~
* ~[ ] All new Python files are placed inside an existing directory.~
* ~[ ] All filenames are in all lowercase characters with no spaces or dashes.~
* ~[ ] All functions and variable names follow Python naming conventions.~
* ~[ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).~
* ~[ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.~
* ~[ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.~
* ~[ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.~

### CODE REVIEW

**Comment by Panquesito7** [comment]
Can anybody help by re-opening this PR? @dhruvmanila, @cclauss.

**Comment by cclauss** [comment]
@algorithms-keeper is correct that any pull request that modifies 675 files is invalid and is impossible to review.

**Comment by Panquesito7** [comment]
Because the Git history is modified, it looks like it "changed" 675 files, but it just removed the `project_euler_answers.json` file from the Git history. All those 675 files have the `project_euler_answers.json` file in the Git history. This PR fixes that.

**Comment by Panquesito7** [comment]
> Please unsubscribe me from these modifications to your fork. This creates a lot of notification spam.

You are the only one who can unsubscribe. I didn't subscribe you to my fork anyways, and sorry for disturbing you.

**Comment by cclauss** [comment]
I am getting spammed on every PR modified that @mentions me.  I tried unsubscribing from you fork but it does not work.

Let’s halt this effort.  We have already done what was requested so please stop messing with this repo.  This PR asks maintainers to trust that 675 files are modified but they are not modified.  That is not a risk that we should  take given all the hard work of so many contributors.

**Comment by Panquesito7** [comment]
The Project Euler team asked us **kindly** if we could remove it from the Git history...but that's OK, I guess. 🤷‍♂️

**Comment by dhruvmanila** [comment]
I agree with Christian that modifying a lot of files without checking them up is a big risk for the repo in the current state. I don't expect you to go through every one of them. 

Also, if these changes are to be made then it should also be updated in every branch and that will be a big headache to resolve. I also propose to pause this for now.

Thanks for all the effort you went through :)

**Pull request closed without merging**
