### PR TITLE
added algorithm for reversing a doubly linked list

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
`###` **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
https://travis-ci.com/github/TheAlgorithms/Python/builds/182267992#L313

**Comment by Randyhubbard0** [comment]
{Push_Pull)

**Comment by NEERAJAP2001** [comment]
@cclauss, 
sir could you help me out why is my code not accepted.

**Comment by cclauss** [comment]
https://travis-ci.com/github/TheAlgorithms/Python/builds/182267992#L313

The easiest way to fix these is:
```
python3 -m pip install black
black reverse_doubly_linked_list.py
```
We don't accept Python filenames that contain uppercase characters.

**Comment by NEERAJAP2001** [comment]
Thank you, sir.

**Pull request closed without merging**
