### PR TITLE
Add breadth first search

### PR DESCRIPTION
**Pull request by Rolv-Apneseth**
Added a .py file in the searches folder for breadth-first search algorithm with a pathfind visualisation to show the result. 

Included doctests and have already run black, mypy and doctests locally.

In relation to #3260

### CODE REVIEW

**Comment by Rolv-Apneseth** [comment]
Ok I'm sorry I'll leave this here anyway but those first two commits are from a different pull request(#3454). I don't know why the commits from that one are here as well, I made different branches for both. Help would be appreciated. (The failed tests are from those 2 commits, that's a different problem on that other pull request)

**Comment by kadhirash** [comment]
Hello @Rolv-Apneseth,

I'm thinking they both ended up counting as commits because you pushed commits from (#3454) earlier, regardless of what branch you are on currently. To get rid of the old branch changes, you have to [delete](https://www.freecodecamp.org/news/how-to-delete-a-git-branch-both-locally-and-remotely/) them locally and remotely I believe, or [stash](https://stackoverflow.com/questions/22620393/various-ways-to-remove-local-git-changes) them in case you would want to come back to it. 

Essentially you want to remove your Git changes.

Anyway, after this, the old branch commits wouldn't be part of your commits I'm thinking.

**Comment by poyea** [comment]
Please run `black .` and `isort` for your code. https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md

**Comment by poyea** [comment]
I think you can enable the github actions in your setting of the fork too.

**Comment by poyea** [comment]
You may open a new branch for those changes, and file a new PR. When you've done, you can close this PR.

**Comment by Rolv-Apneseth** [comment]
@popyea I did open a new branch for these changes just I don't know very well how branches work. I will try to file a new pr. @kadhirash thank you I will try that

**Pull request closed without merging**
