### PR TITLE
Add solution for Project Euler problem 211

### PR DESCRIPTION
**Pull request by ksr1122**
Name: Divisor Square Sum

For a positive integer n, let σ2(n) be the sum of the squares of its divisors.
For example, σ2(10) = 1 + 4 + 25 + 100 = 130.

Find the sum of all n, 0 < n < 64,000,000 such that σ2(n) is a perfect square.

reference: #2695

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
Dude, this script took 8 minutes 41 seconds to run! Testing the entire repository takes less than half of that time lol. You need to take a look at that.

```console
$ time python sol1.py
1922364685

real    8m46.871s
user    8m41.278s
sys     0m3.170s
```

**Comment by ksr1122** [comment]
> Dude, this script took 8 minutes 41 seconds to run! Testing the entire repository takes less than half of that time lol. You need to take a look at that.
> 
> ```
> $ time python sol1.py
> 1922364685
> 
> real    8m46.871s
> user    8m41.278s
> sys     0m3.170s
> ```

Ya I am afraid that's the best I could get so far. If that's a problem. We can hold it. I will see if I could find a better way. If not we can close it no problem.

**Review by dhruvmanila — COMMENTED** [review]
### Announcement:

@ksr1122

*This message is sent to all pull requests which are **OPEN, NOT MERGED, not containing 'wontfix' label and contains 'Project Euler' or 'Project' or 'Euler' (case doesn't matter) in their title**. If this message doesn't apply to your pull request, please ignore this.*

### Message:

This is to notify all the users submitting a pull request for the Project Euler solution that the [README.md](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) file has been updated with all the style requirements necessary for the directory and solution files. ***Please read through it and make all the necessary changes required to your submission.***

**Comment by dhruvmanila** [comment]
Hey, @ksr1122 are you working on this? If not then please close this PR. Thank you for your cooperation.

**Pull request closed without merging**
