### PR TITLE
Update temperature_conversions.py

### PR DESCRIPTION
**Pull request by SabariGanesh-K**
Added Reaumur scale unit conversions.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by SabariGanesh-K** [comment]
Its working now and I have fixed it.All 3 checks have been verified.
I am adding a new temperature unit called Reaumur.
Kindly verify it.

**Comment by dhruvmanila** [comment]
This is looking good! Awesome work! 
It seems you can do the conversion in a reverse way as well. If you wish to add the functions for that, you can do so and if not then it's fine. Inform me about your decision so that I can review your PR.

```
Celsius -> Réaumur
kelvin -> Réaumur
...
```

**Comment by SabariGanesh-K** [comment]
Thanks for the appreciation. I am leaving the reverse way as an chance for  other people so that they can fill it if they find  that it is missing. And let me know if you want the reverse way as well, so that  I can commit it too. If my decision of giving others a chance  is fine , you may merge it.

**Review by dhruvmanila — APPROVED** [review]
Alright, no problem. It's your decision.
- [x] Formulas are correct
- [x] Includes doctest
- [x] Passing all automated tests

Congratulation on your first commit! 🎉 😁

**Comment by SabariGanesh-K** [comment]
Thanks once again😀

**Pull request merged**
