### PR TITLE
#315 Renamed all .py files to snake_case

### PR DESCRIPTION
**Pull request by Alfro**
#491 and #362 seemed to tackle this as well but seemed to currently have conflicts with the main branch

Used a simple python script to turn all names into snake_case (done for clarity, not efficiency)
```
import os
import re

path = '.'

def snake_it(filename):
    newfilename = filename.replace('-','_')
    newfilename = re.sub(r'([a-z])([A-Z])', r'\1_\2' , newfilename)
    return newfilename.lower()

for root, subdirs, files in os.walk(path):
    for filename in files:
        if filename.endswith('.py'):
            fullpath = root + '/' + filename
            newfullpath = snake_it(fullpath)
            print( fullpath + ' -> ' + newfullpath)
            os.rename(fullpath, newfullpath)
```

### CODE REVIEW

**Comment by Alfro** [comment]
I broke all __init__ files :sweat_smile:

**Comment by cclauss** [comment]
Maybe you should add https://pypi.org/project/flake8-filename to __.travis.yml__ to enforce this change on all future pull requests.

**Comment by cclauss** [comment]
There are four conflicts... Do you know how to resolve them?

**Comment by Alfro** [comment]
Done. Wow, faster moves fast, doesn't it? :)

**Comment by cclauss** [comment]
Nice!

**Pull request merged**
