### PR TITLE
update volumes with type hints + some refactoring

### PR DESCRIPTION
**Pull request by yuriimchg**

### CODE REVIEW

**Comment by cclauss** [comment]
This is awesome but some doctests would be a welcome addition.  See CONTRIBUTING.md for details.

**Comment by yuriimchg** [comment]
@cclauss 
updated volumes with doctests

**Comment by yuriimchg** [comment]
sorry for the delay

**Comment by cclauss** [comment]
Float vs. int... https://travis-ci.com/TheAlgorithms/Python/builds/135019488#L610

**Pull request merged**
