### PR TITLE
Adding a program for swap nodes in linkedlist

### PR DESCRIPTION
**Pull request by jithendrabsy**
I am adding a program to swap two nodes in a Linked list

### CODE REVIEW

**Comment by jithendrabsy** [comment]
Yeah! I will look into it

**Comment by jithendrabsy** [comment]
Now you can swap nodes which contain head too

**Comment by jithendrabsy** [comment]
screenshot 9 _li

**Comment by yanglbme** [comment]
@jithendrabsy okay

**Pull request merged**
