### PR TITLE
monte_carlo.py

### PR DESCRIPTION
**Pull request by yash-saini**
Here the code implementing the Monte Carlo method

### CODE REVIEW

**Comment by cclauss** [comment]
Please read CONTRIBUTING.md

**Comment by cclauss** [comment]
Are you the author of this code?  https://www.mlq.ai/python-for-finance-portfolio-optimization

**Comment by yash-saini** [comment]
> Please read CONTRIBUTING.md

No i didn't author that. However, I authored the file I wrote.

**Comment by cclauss** [comment]
READING a file has nothing to do with AUTHORING a file.

**Comment by cclauss** [comment]
Closing because plagiarized Is not honest.
http://bennymachinelearning.blogspot.com/2017/08/python-finance-fundamentals.html
http://bennymachinelearning.blogspot.com/2017/08/
https://www.scribd.com/document/421534259/01-Portfolio-Allocation-and-Sharpe-Ratio

**Comment by Panado16** [comment]
Hi

**Pull request closed without merging**
