### PR TITLE
pr2

### PR DESCRIPTION
**Pull request by Deekshaesha**
changes done

### CODE REVIEW

**Comment by cclauss** [comment]
Removing the function and its doctest is not a good idea.

**Comment by cclauss** [comment]
https://travis-ci.com/TheAlgorithms/Python/builds/133767828#L348

**Comment by Deekshaesha** [comment]
changes are done

**Comment by Deekshaesha** [comment]
done

**Comment by cclauss** [comment]
First:
Travis CI fail 1
And then:
Travis CI fail 2

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/Travis_CI_tests_are_failing.md

**Pull request closed without merging**
