### PR TITLE
doubly_linked_list.py: Add doctests

### PR DESCRIPTION
**Pull request by cclauss**
### **Describe your change:**

* [ ] Add an algorithm?
* [x] Add tests to an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
@WilliamHYZhang @AlexDvorak 
Could you please look at why these tests are failing?  Am I doing something wrong?

**Comment by TheSuperNoob** [comment]
> Could you please look at why these tests are failing? Am I doing something wrong?

@cclauss 
I believe the problem here is with the code, not the tests. `line 44: self.head.previous = None` 
The problem here is that on `line 41: self.head = self.head.next` will be `None`, since there is only one element left in the list, head no longer has a next element.

Similarly the problem is also there in `deleteTail` on line 58 and 59, but this time tail will have no previous element.

**Comment by cclauss** [comment]
https://travis-ci.com/github/TheAlgorithms/Python/builds/168928811#L754 is even worse than that.  It is saying that `self.head` is None.

**Comment by TheSuperNoob** [comment]
> https://travis-ci.com/github/TheAlgorithms/Python/builds/168928811#L754 is even worse than that. It is saying that `self.head` is None.

Yes, because on line 41 `self.head` is set to `self.head.next` which would be `None` in this case, since there is no next node.

**Comment by cclauss** [comment]
So,  Can you suggest a fix that allows the tests to pass?

**Comment by TheSuperNoob** [comment]
You can make the tests pass by not trying to use `deleteHead` or `deleteTail` on the final element in the list, however I'd recommend fixing the algorithm so this is possible. I can open a PR later today that fixes this.

**Pull request closed without merging**
