### PR TITLE
Created problem_34 in project_euler

### PR DESCRIPTION
**Pull request by Kush1101**
### **Describe your change:**
Created the solution for problem 34 in project_euler.

 
* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/blob/master/Travis_CI_tests_are_failing.md

**Comment by Kush1101** [comment]
How do I run these tests on my computer? So the next time I open a PR I can be sure it will pass the tests.

**Comment by cclauss** [comment]
```
python3 -m pip install black
black my_file.py
```
That should autofix all these issues as discussed in CONTRIBUTING.md.

**Comment by Kush1101** [comment]
Sir, I tried running this command after installing black using pip. 
But it is showing error. Can you please explain in detail how do I do these or provide a reference. I have looked by Black's documentation as well but I couldn't get any help.

**Comment by cclauss** [comment]
What error is it showing?  Usually it is a Python syntax error and a line number.

**Pull request closed without merging**
