### PR TITLE
Create area_triangle.py

### PR DESCRIPTION
**Pull request by kasa10**
Calculates the area of a triangle on three sides

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Ankuraxz** [comment]
Black and Flake 8 issues

"""calculates the area of a triangle on three sides. a,b,c - sides triangle""" --> Use #
    p=(a+b+c)/2 --> Correct Indentation
Correct White Spaces
Call the function by passing some values.

**Comment by Ankuraxz** [comment]
Travis CI error
IndentationError: unindent does not match any outer indentation level
Correct the indentation for Semi-perimeter calculation p=(a+b+c)/2

**Comment by Ankuraxz** [comment]
please also correct other errors

**Comment by Ankuraxz** [comment]
Remove White space issues
-#S= √ (p * (p - a)*(p - b)*(p - c))
-#p=(a+b+c)/2;
-#a,b,c - sides triangle
-#calculates the area of a triangle on three sides. a,b,c - sides triangle
-
-def treug(a,b,c):
-	p=(a+b+c)/2
-	S=(p * (p - a)*(p - b)*(p - c))**(1/2)
-	return(S)
-	
-
-print(treug(5,5,5))
+# S= √ (p * (p - a)*(p - b)*(p - c))
+# p=(a+b+c)/2;
+# a,b,c - sides triangle
+# calculates the area of a triangle on three sides. a,b,c - sides triangle
+
+
+def treug(a, b, c):
+    p = (a + b + c) / 2
+    S = (p * (p - a) * (p - b) * (p - c)) ** (1 / 2)
+    return S
+
+
+print(treug(5, 5, 5))

**Comment by kasa10** [comment]
I correct all. Why it not work??? I dont understand, what I should fix?

**Comment by kasa10** [comment]
Error: Process completed with exit code 1.  What it means?

**Comment by Ankuraxz** [comment]
# S=√(p*(p-a)*(p-b)*(p-c))
# p=(a+b+c)/2
# a,b,c-sidestriangle
# calculatestheareaofatriangleonthreesides.a,b,c-sidestriangle
def treug(a, b, c):
    p = (a + b + c) / 2 #Semi-Perimeter
    S = (p * (p - a) * (p - b) * (p - c)) ** (1 / 2) #Area by Heron's Formula
    return S


print(treug(5, 5, 5))

**Pull request closed without merging**
