### PR TITLE
Adopt Python >= 3.8 assignment expressions using auto-walrus

### PR DESCRIPTION
**Pull request by cclauss**
### Describe your change:

Adopt Python >= 3.8 [assignment expressions](https://docs.python.org/3/whatsnew/3.8.html) using https://pypi.org/project/auto-walrus/

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?
* [x] Fix continuous integration tests

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by CaedenPH — APPROVED** [review]
Nice addition.
Whats with the diff in `machine_learning/sequential_minimum_optimization.py`?

**Comment by cclauss** [comment]
No idea.  Probably line endings or tabs, etc.

**Comment by MarcoGorelli** [comment]
> No idea. Probably line endings or tabs, etc.

Yeah I think it's just the line endings:
```
 file machine_learning/sequential_minimum_optimization.py 
machine_learning/sequential_minimum_optimization.py: Python script, ASCII text executable, with CRLF line terminators
```

**Review by dhruvmanila — APPROVED** [review]
Go for walrus! ;)

**Pull request merged**
