### PR TITLE
First commit for add_prefix_conversion

### PR DESCRIPTION
**Pull request by manueldilullo**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by poyea** [comment]
I think we already have one? : https://github.com/TheAlgorithms/Python/blob/master/conversions/prefix_conversions.py

**Comment by manueldilullo** [comment]
@poyea I was inspired by this https://github.com/TheAlgorithms/Python/blob/master/conversions/prefix_conversions.py, but it works slightly differently. If I understand how it operates, _prefix_conversions.py_ wants a known_prefix as an input to the function, so if we have a number written in his full form we can't convert it. My code works without a known_prefix, it takes the number and write it using a “notation with prefix”. 
Would you suggest I open an issue and fix this directly in _prefix_conversions.py_ instead of creating a new file?

**Comment by manueldilullo** [comment]
> 
> 
> > @poyea I was inspired by this https://github.com/TheAlgorithms/Python/blob/master/conversions/prefix_conversions.py, but it works slightly differently. If I understand how it operates, _prefix_conversions.py_ wants a known_prefix as an input to the function, so if we have a number written in his full form we can't convert it. My code works without a known_prefix, it takes the number and write it using a “notation with prefix”. Would you suggest I open an issue and fix this directly in _prefix_conversions.py_ instead of creating a new file?
> 
> So it is to add a prefix to a number

Yes, it is

**Review by poyea — APPROVED** [review]
Thank you for your pull request!🤩

**Pull request merged**
