### PR TITLE
Add stone unit of measuring weight

### PR DESCRIPTION
**Pull request by mrbrianevans**
### Describe your change:
I have added a new unit of measurement to the weight conversion algorithm. The new unit is "stone". 

I've added some tests in the docs using an external calculator. Not sure if they pass.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by mrbrianevans** [comment]
Okay I've fixed the tests and they are passing on my machine, so please could you run them on the automated system for ci. Thanks

**Comment by mrbrianevans** [comment]
As far as I can tell, the failing build is not due to anything related to my pull request; please could you give me more details.

When I run mypy locally on the file I changed, I get:
```
mypy --ignore-missing-imports conversions\weight_conversion.py
Success: no issues found in 1 source file
```

And the failing file in the github action is:
```
strings\check_anagrams.py:32: error: Need type annotation for "count"
```
which is unrelated to the changes I've made.

Please could you let me know what I can do to get the build passing. Thanks

**Comment by cclauss** [comment]
Do you know how to rebase the pull request?

**Comment by mrbrianevans** [comment]
Yes I think so, will try tomorrow. I'll let you know if I need some help. Has a fix for this build issue been pushed to the master branch?

**Review by cclauss — APPROVED** [review]

**Pull request merged**
