### PR TITLE
Add a naive recursive implementation of 0-1 Knapsack Problem

### PR DESCRIPTION
**Pull request by tbsschroeder**
### **Describe your change:**

Add a naive recursive implementation of 0-1 Knapsack Problem

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by poyea** [comment]
Did you take a look at `dynamic_programming`? Are there any existing implementation for this?

**Comment by tbsschroeder** [comment]
@poyea yes I did, also did this during a job interview, but I did not want to "overdo" the solution in the first place ;-)

**Comment by poyea** [comment]
I mean, this should go into `dynamic_programming`. Do you agree?

**Comment by tbsschroeder** [comment]
@poyea Sorry but no. This is a simple and recursive solution, the dynamic one looks different.

**Comment by poyea** [comment]
Yeah. It seems that a new folder might be the right place.

**Comment by poyea** [comment]
Would you mind adding a README.md in the folder? Just add something like this: https://en.wikipedia.org/wiki/Knapsack_problem

Example: https://github.com/TheAlgorithms/Python/tree/master/linear_algebra

**Comment by tbsschroeder** [comment]
@poyea  added a Readme, also tests :-)

**Comment by tbsschroeder** [comment]
@poyea everything should be complete right now.

**Review by poyea — APPROVED** [review]
Thank you for your pull request!🤩

**Pull request merged**
