### PR TITLE
Changed filename, added non-preemptive SJF

### PR DESCRIPTION
**Pull request by sangin-lee**
### Describe your change:
Changed filename of previous [shortest_job_fisrt.py] to [shortest_remaining_time_first.py] because it comes under to
URL : https://en.wikipedia.org/wiki/Shortest_remaining_time

Added new [shortest_job_first.py] which is non-preemptive shortest job first. It comes under to
URL : https://en.wikipedia.org/wiki/Shortest_job_next

+Added Wikipedia URL in each comments

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by sangin-lee** [comment]
@cclauss Can you review my work?

**Comment by sangin-lee** [comment]
@cclauss  @dhruvmanila Could you please review my work?

**Comment by sangin-lee** [comment]
Fixed doctest results
ex) 5.0 -> 5.00000

**Comment by cclauss** [comment]
As a user, I would find it very distracting to see `5.00000` instead of `5.0`.  All these extra zeros create unnecessary cognitive load for the reader so I would much prefer the clear and simple `5.0` instead

**Comment by sangin-lee** [comment]
Would it be better to modify codes to print out only first digit of the decimal point?

**Comment by cclauss** [comment]
5.12345 is OK if there are actual values there to the right of the decimal point but 5.00000 must be shortened to 5.0

**Comment by sangin-lee** [comment]
> 5.12345 is OK if there are actual values there to the right of the decimal point but 5.00000 must be shortened to 5.0

Fixed formatting. Thanks for commenting!!

**Comment by sangin-lee** [comment]
@cclauss What should I do to merge this PR?

**Comment by JiHyunSong** [comment]
@cclauss can you follow it?

**Pull request closed without merging**
