### PR TITLE
Data Transformations

### PR DESCRIPTION
**Pull request by danmurphy1217**
### **Describe your change:**

* [x ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ x ] This pull request is all my own work -- I have not plagiarized.
* [ x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x ] All new Python files are placed inside an existing directory.
* [ x ] All filenames are in all lowercase characters with no spaces or dashes.
* [ x ] All functions and variable names follow Python naming conventions.
* [ x ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ x ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ x ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ x ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by danmurphy1217** [comment]
Looks like my old commits are getting grouped into this pull request- sorry about that. Should I close this and open a new one for just the data_transformations.py file?

**Comment by cclauss** [comment]
In the markdown checklist above, adding spaces on either side of the `x` breaks the markdown syntax.
* [x] check
* [x ] not check

On the code, could we get the mean and standard deviation from https://docs.python.org/3/library/statistics.html and _not_ round them? Rounding multiple times an a single calculation worries me.

**Comment by danmurphy1217** [comment]
> In the markdown checklist above, adding spaces on either side of the `x` breaks the markdown syntax.
> 
> * [x]  check
> * [x ] not check
> 
> On the code, could we get the mean and standard deviation from https://docs.python.org/3/library/statistics.html and _not_ round them? Rounding multiple times an a single calculation worries me.

Yes, I can change that. I am going to close this pull request and open a new one with the current version of the Python Algorithms repository (to avoid conflicts with my previous commits). That ok?

**Comment by cclauss** [comment]
Sure.  If you cannot rebase then close and open a new PR.  Just add Replaces #2191 So we can follow the thread of comments.

**Pull request closed without merging**
