### PR TITLE
Lucas Kanade Method

### PR DESCRIPTION
**Pull request by Bhazkar**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Bhazkar** [comment]
Added Lucas Kanade Algorithm. The Lucas-Kanade optical flow algorithm is a simple technique which can provide an estimate of the movement of interesting features in successive images of a scene. It assumes the flow is essentially constant in a local neighbourhood of the pixel under consideration, and solves the basic optical flow equations for all the pixels in that neighbourhood, by the least square criterion.

**Comment by Bhazkar** [comment]
Can someone please review and merge my PR.

**Review by mateuszz0000 — CHANGES_REQUESTED** [review]
Please add type hints and doctests. Then we can review.

**Comment by Bhazkar** [comment]
@mateuszz0000 I have made the changes, please review my PR.

**Review by purple1979 — COMMENTED** [review]
Do not approve this is what is to believed my account with Bof A

**Comment by Bhazkar** [comment]
@purple1979 why not to approve what is the problem?

**Comment by purple1979** [comment]
Because It was brought to my attention that there's someone hacking my personal Information on this site

**Comment by Bhazkar** [comment]
@purple1979 Sorry I didn't get you, what does it have to do with my PR? Are there any problems in my code, any suggestions? If everything is fine when can I expect my PR to get merged?

**Comment by mateuszz0000** [comment]
Where are fixew I mentioned?? Please make it then I will review your code... Dont spam in comments and just add these type hints and tests. How could i review something without unit test? Be profesional ;)

**Comment by Bhazkar** [comment]
@mateuszz0000 my program is based on optical flow which takes live input through your webcam to detect motion. I have explained my code in details by providing several type hints other than that I have also gone through some files in this directory "Computer Vision" for some insights. What could be any possible unit tests that could be written down for my algorithm as it is all dependent on visual verification. Please suggest some possible changes in my file. Your suggestions will be highly appreciated.

**Comment by mateuszz0000** [comment]
Did you read my comments? I've suggested you multiple times...

**Comment by Bhazkar** [comment]
@mateuszz0000, I am new to this platform and don't have much experience here. I have read your comments carefully but I am not sure what changes you are asking for. It would be great if you guide me through this.

**Comment by Bhazkar** [comment]
@mateuszz0000 please tell me what to change in my code.

**Pull request closed without merging**
