### PR TITLE
added add algorithm

### PR DESCRIPTION
**Pull request by Shrutikabansal**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
```
==================================== ERRORS ====================================
________________ ERROR collecting scripts/validate_filenames.py ________________
scripts/validate_filenames.py:29: in <module>
    sys.exit(bad_files)
E   SystemExit: 1
------------------------------- Captured stdout --------------------------------
1 files are not in a directory:
add.py
```

**Comment by Shrutikabansal** [comment]
Didn't get it

**Comment by cclauss** [comment]
In the checklist above, it says __All new Python files are placed inside an existing directory.__ and we have a test that enforces (part of) that.

Also, [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md) already contains the function `sum_ab()` that contains doctests and type hints.

**Comment by Shrutikabansal** [comment]
Got it thank you so much

**Pull request closed without merging**
