### PR TITLE
Added Linear regression

### PR DESCRIPTION
**Pull request by yashLadha**

### CODE REVIEW

**Comment by yashLadha** [comment]
Hey Numpy and request are som popular libraries to be used in ML. Please correct the tests in .travis.yml

**Comment by yashLadha** [comment]
Anyone from the community, please merge the PR.

**Comment by 0oo0** [comment]
Can you please update travis.yml too?

**Comment by yashLadha** [comment]
I can send a different PR for that as well.

**Comment by 0oo0** [comment]
Thank you. Looking forward to have more contributions from you. 🎉

**Pull request merged**
