### PR TITLE
Solving the `Top k most frequent words` problem using a max-heap

### PR DESCRIPTION
**Pull request by aparibocci**
### Describe your change:
This PR aims to add an algorithm to identify the top `k` most frequent strings given a provided string list of elements.
To do this, the algorithm is using a max-heap implementation already existing in this repository (a generic type was introduced to allow the usage).

Time complexity is `O(n)`, where `n` is the number of words:
- `O(n)` for building the max-heap
- `k*O(logn)` for extracting the `k` most frequent strings

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by CaedenPH — APPROVED** [review]
Very well written algorithm, great stuff!

**Comment by aparibocci** [comment]
Hello @cclauss, I'm tagging you as I saw your involvement in several PRs.
Do you know who can I ask to for a review? Is there anything I should still change in the PR?
Thank you!

**Comment by cclauss** [comment]
All of this seems like it could be done in a few lines with only a `collections.Counter` so what are the advantages of this approach?

**Comment by aparibocci** [comment]
> All of this seems like it could be done in just a few lines using only a `collections.Counter` so what are the advantages of this approach?

Thanks for the feedback.
I had a look to `collections.Counter` and noticed that, indeed, `most_common` solves exactly this problem: https://github.com/python/cpython/blob/3.11/Lib/collections/__init__.py#L608

This is using `heapq.nlargest` behind the scenes: https://github.com/python/cpython/blob/3.11/Lib/heapq.py#L523

There is already a `Heap` class in this repository, I imagined it would be useful to show a typical usage of heaps (i.e. finding out order statistics). Do you think I should close this PR entirely, or do you have other suggestions?

Thank you

**Comment by cclauss** [comment]
```python
from collections import Counter
def top_k_frequent_words(words, k_value):
    return [x[0] for x in Counter(words).most_common(k_value)]
```

**Comment by cclauss** [comment]
Please put the text of our last two messages in the file’s docstring and then we can merge this.   That will show why this work was done and that there also that the Python standard library provides a far more straightforward  way to solve the same problem.

**Comment by aparibocci** [comment]
> Please put the text of our last two messages into the file’s docstring and then we can merge this. That will show why this work was done and that there also that the Python standard library provides a far more straightforward way to solve the same problem.

Thanks for the feedback.
I have updated the docstring mentioning the (preferable) Python standard library solution.

**Review by cclauss — APPROVED** [review]
Nice!

**Pull request closed without merging**
