### PR TITLE
added decimal to hexadecimal conversion

### PR DESCRIPTION
**Pull request by jasper256**
I didn't update the directory because I noticed that the other conversion algorithms were not listed

### CODE REVIEW

**Comment by PatOnTheBack** [comment]
If I add this line `print("999098 in hexadecimal is", decimal_to_hexadecimal(999098))` to the `main()` function, I get an error. Does your program not support large numbers?

```
('5 in hexadecimal is', '5')
('15 in hexadecimal is', 'f')
('37 in hexadecimal is', '25')
('255 in hexadecimal is', 'ff')
('4096 in hexadecimal is', '100')
Traceback (most recent call last):
  File "decimal_to_hex.py", line 45, in <module>
    main()
  File "decimal_to_hex.py", line 42, in main
    print("999098 in hexadecimal is", decimal_to_hexadecimal(999098))
  File "decimal_to_hex.py", line 30, in decimal_to_hexadecimal
    hexadecimal = values[remainder] + hexadecimal
KeyError: 235
```

**Comment by jasper256** [comment]
Thank you for bringing this to my attention. After combing through the algorithm again I believe I have found the error that would cause the key to go out of bounds as the number of digits necessary increase. I will fix this as soon as I get home.

**Comment by jasper256** [comment]
The program has now been revised.  I used 999,098 as a test and checked the results with a calculator, which came back as successful.

**Comment by jasper256** [comment]
I honestly don't know much about automated testing, but it's something I'd be happy to look into in the future. I'm currently about to head to the airport for a trip I'm taking, and I won't be able to sit down in front of a computer for a couple weeks. I won't even have internet access through my phone in a few days, so if anyone posts comments just know that I'll get to them when I can in about two weeks.

**Comment by cclauss** [comment]
Cool.  Let's land this one now and you can pick up tests when you return.  Read thru the doctest page on your flight because it is simple but really helpful to have tests on your code.  Safe travels.

**Pull request merged**
