### PR TITLE
ref: refactor `KnightTour` implementation

### PR DESCRIPTION
**Pull request by TruongNhanNguyen**
### Describe your change:
---
In this refactored version:
*   I've organized the code into a `KnightTour` class to encapsulate related functions.
*   Each method now belongs to the `KnightTour` class and operates on the class attributes.
*   I've renamed some variables and methods for clarity.
*   Magic numbers have been replaced with named constants.
*   Error handling has been improved to raise more informative errors.
*   The `solve_knight_tour` function now directly modifies the `board` rather than returning it, enhancing readability.
*   I've added a check to ensure the board size is at least 1.
*   The doctests remain intact and are still executed when running the script.
---

* [x] Refactor in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by TruongNhanNguyen** [comment]
Please have a look at this PR, @imSanko, @cclauss, @MaximSmolskiy

**Review by imSanko — APPROVED** [review]
seems good.

**Comment by TruongNhanNguyen** [comment]
Can you help me ask for reviews from other code maintainers @imSanko.

**Comment by TruongNhanNguyen** [comment]
Requesting review: @cclauss, @MaximSmolskiy, and @imSanko.

**Pull request closed without merging**
