### PR TITLE
Remove inaccessible URL in computer_vision/README.md

### LINKED ISSUE #12382: [Fix] Remove inaccessible URL in computer_vision/README.md Line 11
### Repository commit

10aa789c3e4531558526e2e964673d537a09e249

### Python version (python --version)

not important

### Dependencies version (pip freeze)

not important

### Expected behavior

Remove inaccessible URL.

### Actual behavior

There is a inaccessible URL in line 11.

### PR DESCRIPTION
**Pull request by setbit123**
Remove inaccessible URL.

### Describe your change:

Remove an inaccessible URL in computer_vision/README.md Line 11.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes issue number".

Fixes #12382

### CODE REVIEW

**Comment by setbit123** [comment]
Additionally, I have attempted to search for the article using a similar title in DataRobot but did not retrieve any information.

**Comment by setbit123** [comment]
@TheAlgorithms/python_maintainers You reviews, please.

**Review by anandfresh — APPROVED** [review]

**Comment by setbit123** [comment]
Thank you for your approval. I notice that the PR has not been merged yet, and I would like to know if there is anything else I need to do to facilitate the merging of the PR.

cc @anandfresh

**Review by anandfresh — APPROVED** [review]

**Review by tianyizheng02 — APPROVED** [review]
Can confirm that the URL is dead. Thanks for the catch!

**Pull request merged**
