### PR TITLE
Handling Imbalanced Data

### PR DESCRIPTION
**Pull request by AjaySinghPanwar**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by spamegg1** [comment]
`pre-commit` says:
> 1 files contain hyphen characters:
machine_learning/handling-imbalanced-data.ipynb
Error: Process completed with exit code 1.

`Travis CI` says:
>________________ ERROR collecting scripts/validate_filenames.py ________________
scripts/validate_filenames.py:37: in <module>
    sys.exit(bad_files)
E   SystemExit: 1
------------------------------- Captured stdout --------------------------------
1 files contain hyphen characters:
machine_learning/handling-imbalanced-data.ipynb

Renaming your file should fix the issue. Remove `-` and replace with `_`

**Review by poyea — COMMENTED** [review]
Can you provide a screenshot to the changes?

**Comment by AjaySinghPanwar** [comment]
> Can you provide a screenshot to the changes? I see you changed the `handling_imbalanced_data.py` but later `.ipynb`

> Can't send because I have deleted that pull request because .py was not interactive. So  I added new pull request to add .ipynb file

**Review by 53jk1 — APPROVED** [review]

**Comment by poyea** [comment]
Can you include some references to this, like links?

**Comment by cozek** [comment]
There are many well-cited papers that have dealt with this problem. Perhaps, you can cite them in your script.
Plus, you can contribute .ipynb  https://github.com/TheAlgorithms/Jupyter
For contributing here, I would suggest that you create 1 .py script per algorithm, for example, 1 script for minority oversampling, 1 for SMOTE, etc.

**Comment by dhruvmanila** [comment]
This repository only accepts Python algorithms. If you want to submit a notebook file, please open a pull request in  https://github.com/TheAlgorithms/Jupyter

@algorithms-keeper review

**Pull request closed without merging**
