### PR TITLE
faster sudoku solver

### PR DESCRIPTION
**Pull request by crypticsy**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by spamegg1** [comment]
@crypticsy `pre-commit` will fail if there is no empty line at the end of the file.

Also you should provide proof that this solver is faster than `sudoku.py` by testing and timing it with Python's `timeit` module.

**Comment by crypticsy** [comment]
> @crypticsy Good luck on your first PR here!
> 
> `pre-commit` will fail if there is no empty line at the end of the file.
> 
> Also you should provide proof that this solver is faster than `sudoku.py` by testing and timing it with Python's `timeit` module.

Oh, thanks for the heads up @spamegg1. Also, I did time it, and kept the runtime inside a comment, if the merge gets denied, I will try to create a better submission that passes the guidelines completely.

**Comment by spamegg1** [comment]
> if the merge gets denied, I will try to create a better submission that passes the guidelines completely.

This probably won't get reviewed or merged until all checks pass. 
First let's make sure to pass all the checks.
You can continue to add more commits to this submission. 
You don't have to create another submission from scratch.
Add an empty line at the end of the file and commit/push again.
Then it will have a chance to get reviewed.

**Comment by crypticsy** [comment]
@spamegg1 as you told me, I created a new pull request with an empty line at the end of the file and commit/push again. But the new one failed the pre-commit again.
I also tested and added the run time. The previous solution can take up to 1.37 seconds while mine usually takes 0,17seconds.

**Pull request closed without merging**
