### PR TITLE
Format 9 ill-formatted files

### PR DESCRIPTION
**Pull request by jacobchrismarsh**
Ran black on the directory, found 9 ill-formatted files. The contribution guide states that code should be formatted with black, so this is a good change.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
Please read about https://github.com/psf/black/blob/master/README.md in CONTRIBUTING.md.

**Comment by jacobchrismarsh** [comment]
Hey @cclauss, thanks for commenting. The contributing guide says:
> Please consider running psf/black on your Python file(s) before submitting your pull request. This is not yet a requirement but it does make your code more readable and automatically aligns it with much of PEP 8.

Did you close this because of the "not yet a requirement" clause? If not, I don't understand why this was closed.

**Comment by cclauss** [comment]
When a maintainer (someone who has write permission to this repo) creates or modifies a pull request, the GitHub Action https://github.com/TheAlgorithms/Python/blob/master/.github/workflows/autoblack.yml gets run and the code is reformatted by psf/black.  This means that pull requests that break black formatting merely create unnecessary churn that will get automatically undone.

**Comment by jacobchrismarsh** [comment]
Gotcha, that makes sense. I see how the autoblack runs on every push, thanks for showing me! I still don't see why this PR can be said to "break black formatting". Doesn't it do the very opposite – enforce black in places that weren't enforced?

Interestingly enough, that autoblack was created on Oct 31, 2019, yet many of these files have commits more recent than that. Why did autoblack miss them?

**Comment by cclauss** [comment]
What version of black are you running?  Using the current black (version 20.8b1) none files in this repo are reformatted.

**Pull request closed without merging**
