### PR TITLE
Fix get amazon product data erroring due to whitespace in headers

### PR DESCRIPTION
**Pull request by CaedenPH**
### Describe your change:
This PR fixes this error:
```
Traceback (most recent call last):
  File "C:\Users\caeden\Github\python\web_programming\get_amazon_product_data.py", line 100, in <module>
    get_amazon_product_data(product).to_csv(f"Amazon Product Data for {product}.csv")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caeden\Github\python\web_programming\get_amazon_product_data.py", line 26, in get_amazon_product_data
    soup = BeautifulSoup(requests.get(url, headers=header).text)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caeden\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caeden\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caeden\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\caeden\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\caeden\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 369, in prepare
    self.prepare_headers(headers)
  File "C:\Users\caeden\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 491, in prepare_headers
    check_header_validity(header)
  File "C:\Users\caeden\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 1040, in check_header_validity
    _validate_header_part(header, value, 1)
  File "C:\Users\caeden\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\utils.py", line 1056, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36\n        (KHTML, like Gecko)Chrome/44.0.2403.157 Safari/537.36'
```
As well as some type changes and warnings (setting the featuresto `lxml`)

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by CaedenPH** [comment]
Broken bot 😢

**Comment by 50-Course** [comment]
ouch, is that bot for real though?

**Comment by tianyizheng02** [comment]
> Broken bot 😢

@CaedenPH Last time it stopped you once [you exceeded 5 PRs](https://github.com/TheAlgorithms/Python/pull/8988), this time it's 3. What exactly is the PR limit, @dhruvmanila?

**Review by 50-Course — CHANGES_REQUESTED** [review]
This looks good to some extent. 

Can you review #L65-L77? Here are a few suggestions:

* float is a poor way of representing currency. First it introduces a lot of inefficient way when manipulating the money, I think its good you did first, multiply by 100 to take it to interger and even at that, i would have to do some round off, manupulate in integer form and convert back. Here's a typical example:

```
I got $2.99 and need to pay tax of .05 cents,

by working with floats, I would be doing 2.99*100 = 299, and .05*100=5,

money_less_tax = (299 - 5) / 100 = $2.94, in a fintech application with minute charges up 0.005 or so, could be worse with fractions and implicit manipulations, hence you should check out the decimal module
```

Refs:
(How to calculate money in python)[https://learnpython.com/blog/count-money-python/]
(Python Doc on why Decimal is better than float)[https://docs.python.org/3/library/decimal.html]

**Comment by CaedenPH** [comment]
@50-Course This is a change with the algorithm itself. All this pr does is fix a bug and type errors in the algorithm, not refactor the code.
If you think the algorithm could do with a refactoring in terms of the way that money is handled, feel free to implement a pull request for this

**Comment by dhruvmanila** [comment]
> > Broken bot 😢
> 
> @CaedenPH Last time it stopped you once [you exceeded 5 PRs](https://github.com/TheAlgorithms/Python/pull/8988), this time it's 3. What exactly is the PR limit, @dhruvmanila?

It is 3 although it could happen that the event was posted late or there might've been some kind of latency issues or the request failed. I would just remove the limit actually, so if anyone's interested they can open a PR and set this variable to 0: https://github.com/TheAlgorithms/algorithms-keeper/blob/6d535abd7e5344606b979498ed68a756508792c5/algorithms_keeper/event/pull_request.py#L42-L43

**Review by tianyizheng02 — APPROVED** [review]

**Pull request merged**
