### PR TITLE
Create is_power_of_four_logarithm.py

### LINKED ISSUE #9331: Want to Add Power of Four logic using Logarithm
### Feature description
Want to Add DSA Solution of this problem - Power of Four - using Logarithm

**Problem Statement - 
Given an integer n, return true if it is a power of four. Otherwise, return false.
An integer n is a power of four, if there exists an integer x such that n == 4x.**

Example 1:
Input: n = 16
Output: true

### PR DESCRIPTION
**Pull request by DevAgrawal04**
Fixes #9331

### Describe your change:
The file defines a Python function is_power_of_four_logarithm that checks whether a given positive integer is a power of 4 using logarithms.

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [X] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by crocmons — CHANGES_REQUESTED** [review]
this issue already created by me take a look - https://github.com/TheAlgorithms/Python/issues/9331 @DevAgrawal04

**Review by crocmons — CHANGES_REQUESTED** [review]
kindly remove this pr I'm already work on this issue @DevAgrawal04

**Comment by tianyizheng02** [comment]
@crocmons Don't ask someone else to delete their PR just because you're working on an issue. We don't assign issues in this repo, didn't you read the contributing guidelines? If you wanted to contribute the algorithm yourself, then just open a PR and don't open an issue for it.

**Comment by crocmons** [comment]
> @crocmons Don't ask someone else to delete their PR just because you're working on an issue. We don't assign issues in this repo, didn't you read the contributing guidelines? If you wanted to contribute the algorithm yourself, then just open a PR and don't open an issue for it.

@tianyizheng02 ok, Thank you for your message and clarification regarding the contribution guidelines. I appreciate your guidance. I have already submitted the pull request for the problem I am working on, following the established process. Please feel free to review it at your convenience. Once again, thank you for your time and patience.

**Pull request closed without merging**
