### PR TITLE
Create 1.py

### PR DESCRIPTION
**Pull request by Yukti-09**
Add Leetcode questions solved in Python.

### CODE REVIEW

**Comment by cclauss** [comment]
https://travis-ci.com/github/TheAlgorithms/Python/builds/179856519#L252

**Comment by Yukti-09** [comment]
I have formatted the code by running black.

**Comment by cclauss** [comment]
Sorry but I am not a fan of this PR.  There are tons of repos that focus on leetcode problems and this is not one of them.  Outside of the `project_euler` directory, this repo is focused on algorithms sorted by category and leetcode is not that.

**Comment by Yukti-09** [comment]
This https://github.com/TheAlgorithms/C/tree/master/leetcode has leetcode questions in C and so it would be great if we could add the same in python as well.
@cclauss

**Comment by cclauss** [comment]
https://github.com/TheAlgorithms/Python/pull/2316#issuecomment-674485084

**Pull request closed without merging**
