### PR TITLE
added tox to handle virtual environment automatically

### PR DESCRIPTION
**Pull request by meysam81**
### **Describe your change:**

I have modified travis config a little bit to avoid unnecessary installing of libraries and instead added [tox](https://tox.readthedocs.io/) with a clean configuration that calculates coverage as well.

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by meysam81** [comment]
This PR is related to #2128

**Comment by meysam81** [comment]
I would also like to integrate coveralls or codecov to the project.

**Comment by cclauss** [comment]
NO!

**Comment by cclauss** [comment]
Sorry but I _hate_ tox as an extra layer of indirection and confusion that we do not need for this project.

The coverage report is run by Travis on each pull request.
* https://travis-ci.com/github/TheAlgorithms/Python/builds/182054210#L900

**Pull request closed without merging**
