### PR TITLE
minor changes in docstring (knapsack_dp)

### PR DESCRIPTION
**Pull request by Aterolite24**
### Describe your change:

Added changes to docstrings from [11406](https://github.com/TheAlgorithms/Python/pull/11406)

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ✔️ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [✔️  ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [✔️  ] I know that pull requests will not be merged if they fail the automated tests.
* [✔️  ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ✔️ ] All new Python files are placed inside an existing directory.
* [ ✔️ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ✔️ ] All functions and variable names follow Python naming conventions.
* [ ✔️ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ✔️ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ✔️ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ✔️ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by imSanko — APPROVED** [review]
Nice

**Review by Aterolite24 — COMMENTED** [review]
All checks have been passed. If any changes are required, please let me know.

Thanks :)

**Comment by tianyizheng02** [comment]
I'm closing this issue because we actually already have an implementation of this algorithm in [`dynamic_programming/knapsack.py`](https://github.com/TheAlgorithms/Python/blob/723cf9c42839c47e9e6fb83362a7391177355505/dynamic_programming/knapsack.py). The author of #11406 didn't do the due diligence of checking the repo beforehand, so by extension your PR is unfortunately a duplicate as well. However, we'd very much welcome a PR that improves upon our existing implementation.

**Comment by Aterolite24** [comment]
Okay .. sure ..

**Pull request closed without merging**
