### PR TITLE
Deleted sorts/random_pivot_quick_sort.py. Fixes #9124

### LINKED ISSUE #9124: sorts/random_normal_distribution_quicksort.py has no tests
### Repository commit

3

### Python version (python --version)

Python 3.11.5

### Dependencies version (pip freeze)

Numpy

### Expected behavior

Tests.

### Actual behavior

No tests.

### PR DESCRIPTION
**Pull request by aryan1165**
### Describe your change:

Fixes #9124.
Deleted sorts/random_pivot_quick_sort.py 

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by tianyizheng02 — APPROVED** [review]

**Comment by tianyizheng02** [comment]
Thanks for your contribution!

**Comment by tianyizheng02** [comment]
Just realized that the implementation in `sorts/random_pivot_quick_sort.py` was better than the one in `random_normal_distribution_quicksort.py`, so we should've probably kept that one instead... I'll open a new PR to replace the implementation in `random_normal_distribution_quicksort.py` with this deleted implementation

**Comment by aryan1165** [comment]
Oh! My bad i didn't notice it.

**Comment by tianyizheng02** [comment]
I'll open the PR. The deleted implementation needs much fixing anyway (no tests, no type hints, etc)

**Comment by tianyizheng02** [comment]
Wait... I just took a look at the original `quick_sort.py` and it already uses a random pivot... which means that _both_ `random_pivot_quick_sort.py` and `random_normal_distribution_quicksort.py` are duplicates??

**Comment by aryan1165** [comment]
Oh! Thats surprising. Opening another PR doing the same. I think i should take a look and report all those similar implementations in entire codebase as issues. As hacktoberfest has started some new comers will try to fix that issue as their ```good-first issue```.  Thoughts?

**Comment by tianyizheng02** [comment]
I just opened a PR deleting the other file. We actually already have an issue addressing duplicate algorithms (#8098), and I just added the "good first issue" tag to the issue. Thanks for the suggestion

**Comment by aryan1165** [comment]
I just saw that you also opened a PR regarding same. Sorry i didn't see it earlier. Thanks for considering my suggestion.

**Pull request merged**
