### PR TITLE
Update run.py in machine_learning/forecasting

### PR DESCRIPTION
**Pull request by p1utoze**
…tion

### Describe your change:
Fixes [#7305]

I have modified the run.py and it runs without any errors locally. 

-  Removed headers argument from `read_csv` as it caused errors in Normalization.
-  Renamed the train and test column variables as it wasn't easily comprehensible
- Added a Type check condition in case of passing wrong type as arguments in `data_safety_checker` function.

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by tianyizheng02** [comment]
Your PR doesn't actually fix #7305 because the Pytest warnings are still present in the build logs:
```
machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
    warn('Too few observations to estimate starting parameters%s.'

machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for seasonal ARMA. All parameters except for variances will be set to zeros.
    warn('Too few observations to estimate starting parameters%s.'

machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3747: RuntimeWarning: Degrees of freedom <= 0 for slice
    return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/numpy/core/_methods.py:226: RuntimeWarning: invalid value encountered in divide
    arrmean = um.true_divide(arrmean, div, out=arrmean,

machine_learning/forecasting/run.py::machine_learning.forecasting.run.sarimax_predictor
  /opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/numpy/core/_methods.py:261: RuntimeWarning: invalid value encountered in scalar divide
    ret = ret.dtype.type(ret / rcount)
```

However, your changes are still good, so we can merge this PR anyway after some minor tweaks

**Review by tianyizheng02 — CHANGES_REQUESTED** [review]
Nice fixes, just need to clean up the old code and it should be good

**Comment by p1utoze** [comment]
Sure, I'll update the code formatting. 
Regarding the Pytest Warnings, I looked into the source of the error and it might be due to ARIMA deprecation.
Two approaches from mine would be to either transform the data passed to SARIMAX model for estimation or supress the warnings should be well enough.

**Comment by tianyizheng02** [comment]
> Sure, I'll update the code formatting. Regarding the Pytest Warnings, I looked into the source of the error and it might be due to ARIMA deprecation. Two approaches from mine would be to either transform the data passed to SARIMAX model for estimation or supress the warnings should be well enough.

@p1utoze At first glance, it looks to me like some of the errors are caused by the small number of observations (which makes sense, the ARIMA models probably need way more observations to work well). Maybe reworking this file to use a different CSV file (one with much more data) might fix some if not all of the warnings.

**Comment by p1utoze** [comment]
Hey! I finally fixed the warnings. The numpy Runtime warning was due to the `0` in `seasonal_order` tuple and regarding the ARIMA models. Yes you are right, it needs more observations to work well and the User Warning are raised because of the sample test `>>> sarimax_predictor([4,2,6,8], [3,1,2,4], [2])` used by doctests. Supressing it should be fine enough. Shall I create another PR then?

**Comment by tianyizheng02** [comment]
Yeah, that'd be great, thanks!

**Pull request merged**
