### PR TITLE
[Project Euler] Fix code style in Problem 41

### PR DESCRIPTION
**Pull request by JoanRosell**
### **Describe your change:**
Addresses #2786 
 * Improved the problem description with a link
 * Added solution function that calls the old function.
 * Fixed some doctests, their use was inconsistent with the functions they tested

I have some questions @dhruvmanila :
 1. Is it correct to use an assignment inside an f-string? PyCharm is complaining and I can't execute the tests with the current solution call, but I'm leaving it as I found it in the original file.
 2. There is one test case (with n = 7) that is cumbersome to put in a doctest, as the call generates a huge list that wraps around many lines, I have left it out and tested directly the solution output, which passes the test case. Should I leave it as it was and undo the changes?
----
* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by dhruvmanila** [comment]
`print(f"{max(compute_pandigital_primes(7)) = }")`

If you're referring to this then this is not an assignment statement. The `=` sign in an f-string means that it will produce an output where the expression will be mentioned first then ` = ` and then the output of the expression.

Example:
```python
>>> print(f"{1 + 2 = }")
1 + 2 = 3
```

For 2: leave it as it was

**Review by moveax3 — APPROVED** [review]
Good increase of pythonicity and code documentation.

**Comment by JoanRosell** [comment]
Alright, I removed the extra function I added and left the old code as it was.

**Comment by dhruvmanila** [comment]
The answer is actually the maximum value in the list but the function returns a list, we just need the value. Please make the necessary changes as required.

**Review by dhruvmanila — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
