### PR TITLE
Fix #12408 Bug fix for empty strings in join.py

### LINKED ISSUE #12408: strings/join.py is incorrect
### Repository commit

3b1b70bf0e60dddb14917dd7cad34a41d429df01

### Python version (python --version)

Python 3.10

### Dependencies version (pip freeze)

n/a

### Expected behavior

s = ["", "", ""]
join(",", s) == ",".join(s)
# ',,' == ',,'

### Actual behavior

s = ["", "", ""]
join(",", s) == ",".join(s)
# '' != ',,'

### PR DESCRIPTION
**Pull request by aarthipv**
### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #12408 ".

### CODE REVIEW

**Comment by osman-haider** [comment]
@aarthipv your code still have same issue

image


if we gave input like this

join(",", ["", "", ""])

then we are expecting output like follows

',,'

But your code still returning empty string

**Comment by MaximSmolskiy** [comment]
@aarthipv Point of this repository is to learn how to implement algorithms and built-in functions yourself, so I can't accept implementation of `join` function using built-in Python `join` method

**Review by MaximSmolskiy — CHANGES_REQUESTED** [review]
Please fix my comment above

**Comment by MaximSmolskiy** [comment]
Closed in favor of #12434

**Pull request closed without merging**
