### PR TITLE
Update merge_insertion_sort.py

### LINKED ISSUE #5774: Merge insertion sort doesn't work
```
>>> merge_insertion_sort([0, 1, 2, 3, 4])
[0, 2, 1, 3, 4]
```

Cc @ulwlu #2211 [`sorts/merge_insertion_sort.py`](../blob/master/sorts/merge_insertion_sort.py)

### PR DESCRIPTION
**Pull request by yellowsto**
Fixes #5774

merge_insertion_sort

Co-Authored-By: AilisOsswald <44617437+AilisOsswald@users.noreply.github.com>

### Describe your change:
We fixed the Issue of Merge-insertion-Sort not sorting correctly.

We have seen that there is already a PR but we would like to present our fix since it is a little bit different: https://github.com/reidstrieker/Python/commit/2ab90dfa03a9b14400eaf82ed52bb518dc2bd835

We have left all Code as it was before, except line 163
original:
 if result[i] == collection[-i]:
corrected: 
 if result[i] == collection[-1]:

because as the flag name states we want to check if the current item in result is the last item of our input list.  (which would be collection[-1] not [-i]

We think that both solutions should work, but the solution with checking (as described above) should perform a tiny bit better. 
Normally we do this, since we know everything left to the current value is smaller than the value we will have to sort in: 
 result = result[: i + 1] + binary_search_insertion(result[i + 1 :], pivot)

If we find the last_odd_item in our result list, we know the same thing like above and we know that there is one additional value, which is already sorted - the last_odd_item. And with that knowlegde we can make the list we have to search through smaller and the list we don't have to look at larger by one each:
 result = result[: i + 1 +1] + binary_search_insertion(result[i + 1 :], pivot)

Keeping this flag in the code should make it a bit quicker, since in some cases the list to be searched through is one element smaller.

Our next step would be writing more tests as suggested in this issue #5774. Should this be done in the same issue or in a new one?

* [ ] Add an algorithm?
* [X] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by MaximSmolskiy — CHANGES_REQUESTED** [review]
Unfortunately, https://github.com/TheAlgorithms/Python/pull/5832 looks more correctly. I tested both solutions on all permutations of `range(n)` up to `n` equal to `10`. https://github.com/TheAlgorithms/Python/pull/5832 passes them all. But this doesn't pass. For example, `merge_insertion_sort([2, 3, 1, 0]) = [0, 2, 1, 3]`, but the correct answer is `[0, 1, 2, 3]`

**Comment by yellowsto** [comment]
Thank you for the hint! We found out why our solution didn't work properly and we have updated it:

Now we check if the length of the input is an odd number, so that the if only triggers if that is the case. 

Furthermore we have tested this on all permutations from range(0,10).

**Review by MaximSmolskiy — APPROVED** [review]
Yes, now it passes these tests

**Review by Rohanrbharadwaj — APPROVED** [review]

**Comment by Rohanrbharadwaj** [comment]
Looks good, don't mind adding a `doctest.testmod()` towards the end.

**Comment by yellowsto** [comment]
Could any one have a look please? We would appreciate if we could have a feedback :)

**Review by poyea — APPROVED** [review]

**Comment by poyea** [comment]
Let's use `all` if you don't mind. Otherwise, I'll merge this later. Thank you for your pull request!🤩

**Review by poyea — APPROVED** [review]

**Pull request merged**
