### PR TITLE
Feat: Add solution to Euler Problem 6 

### PR DESCRIPTION
**Pull request by domix80**
### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by tianyizheng02** [comment]
This is the same problem as [problem 5 from Project Euler](https://github.com/TheAlgorithms/Python/tree/master/project_euler/problem_005), so perhaps this would better serve as an alternate solution to that problem?

**Comment by domix80** [comment]
Please remove smallest_multiple.py and keep sol3.py

**Comment by tianyizheng02** [comment]
Make sure you follow the [guidelines](https://github.com/TheAlgorithms/Python/blob/master/project_euler/README.md) for submitting a Project Euler solution

**Comment by domix80** [comment]
Fix TCs for sol3.py.
Please discard smallest_multiple.py in math folder.

**Comment by dhruvmanila** [comment]
Thank you for taking the time to contribute but I'm sorry to say that we're not accepting solutions to already solved problems currently. You can try submitting solution for any unsolved problems :)

**Pull request closed without merging**
