### PR TITLE
PR on added uniform cost search algorithm

### PR DESCRIPTION
**Pull request by Miltonbhowmick**
### Describe your change:
Hi, I have added uniform cost search algorithm with fresh pull request. 

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by tianyizheng02 — COMMENTED** [review]
Thanks for your contribution, but please implement this algorithm using a graph data structure. UCS is a graph algorithm and you're contributing to the `graphs/` directory, so you should be using a common graph representation such as adjacency matrices or adjacency lists—see the other files in the `graphs/` directory for examples of this. Your implementation should work on any graph, not just 2-D grids.

**Comment by Miltonbhowmick** [comment]
> Thanks for your contribution, but please implement this algorithm using a graph data structure. UCS is a graph algorithm and you're contributing to the `graphs/` directory, so you should be using a common graph representation such as adjacency matrices or adjacency lists—see the other files in the `graphs/` directory for examples of this. Your implementation should work on any graph, not just 2-D grids.

Yeah, the file, i have uploaded in `graphs/` folder is grid based structure. But i will also contribute the same algorithm with graph based data structure in next time.

**Comment by tianyizheng02** [comment]
> A star algorithm is grid based environment in this `graphs/` directory.

I just noticed that, and you're right. We should definitely have the A* algorithm re-implemented using an actual graph structure too.

**Comment by Miltonbhowmick** [comment]
> > A star algorithm is grid based environment in this `graphs/` directory.
> 
> I just noticed that, and you're right. We should definitely have the A* algorithm re-implemented using an actual graph structure too.
Thank you for noticing.
So, should we have different a folder for grid environment based graph algorithms in python repository? Or We can add `filename_grid` as file name for grid environment based graph algorithms so that all graph algorithms will be in one folder with grid/graph based environment.

**Comment by tianyizheng02** [comment]
I don't think that's necessary for two reasons:
1) In theory, the graph data structures used by graph algorithm implementations should be general enough that 2-D grids are also supported—they are still graphs, after all.
2) Implementing graph algorithms using grids is unnecessarily restrictive, because those algorithms are (presumably) designed to work for _all_ graphs, not just those that can be represented by a 2-D grid.

**Pull request closed without merging**
