### PR TITLE
Add negative int support to 3n+1

### PR DESCRIPTION
**Pull request by Rudxain**
### Describe your change:
Now the `n31` algorithm has been extended to support negative integers, and has protection against infinite looping by checking for 0. The algorithm is still simple enough, so it's still useful for educational purposes

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Rudxain** [comment]
What went wrong? It seems it's the formatting, but where?

**Comment by Rudxain** [comment]
I fixed the long lines, and grouped short lines. I guess it should be valid now

**Comment by Rudxain** [comment]
For some reason, it seems like I accidentally deleted some digits from the file while editing. It should be fixed now

**Comment by cclauss** [comment]
In preparation for that denial-of-service attack that is [Hacktoberfest](https://hacktoberfest.com), I am closing all pull requests that have failing tests.

**Comment by Rudxain** [comment]
What? But (AFAIK) the (new) failing tests were not my fault, it was from upstream. I don't understand

**Comment by Rudxain** [comment]
@cclauss can I (and should I) open a new PR?

**Pull request closed without merging**
