### PR TITLE
Add molecular_chemistry.py

### PR DESCRIPTION
**Pull request by prakhargurunani**
### **Describe your change:**

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by prakhargurunani** [comment]
@cclauss @poyea Please see this. #2765 is merged but I am still getting a `pre-commit` error. All tests have passed.

**Comment by cclauss** [comment]
There are 200+ open pull requests on this repo.  Please do not @mention maintainers on your pull request because you believe that it is more important than the other.  We have our hands full with the silliness of Hacktoberfest and this is not something that we are paid to do.

**Comment by prakhargurunani** [comment]
@poyea All checks and actions have passed. Please merge.

**Comment by prakhargurunani** [comment]
I think this looks good @dhruvmanila . Can you give a review about it ?

**Review by cclauss — CHANGES_REQUESTED** [review]
Is this submission plagiarism like https://github.com/TheAlgorithms/Python/pull/2983#issuecomment-705078500 was?

**Comment by prakhargurunani** [comment]
No...this is my own code @cclauss

**Comment by NicholasACTran** [comment]
Ignoring whether this is plagiarism or not, does this count as an "algorithm" in the computer science theoretic sense?

**Comment by prakhargurunani** [comment]
> Ignoring whether this is plagiarism or not, does this count as an "algorithm" in the computer science theoretic sense?

@NicholasACTran There are also temperature conversion in `conversions`. This PR also belongs to the same category. And this is NOT plagiarised.

**Comment by cclauss** [comment]
@NicholasACTran Our barrier is purposefully low on evaluating if contributions count as an ___algorithm in the computer science theoretic sense___ because that line is difficult to draw and because we are attempting to attract contributions from people who are not (yet) computer science experts.

**Comment by NicholasACTran** [comment]
@cclauss Thanks for the clarification.

**Comment by prakhargurunani** [comment]
@cclauss So will you merge this ?

**Comment by dhruvmanila** [comment]
As mentioned **please don't @mention maintainers**. We already have hundreds of PRs to go through so have patience and we will take a look at it.

**Comment by prakhargurunani** [comment]
Any update?

**Comment by prakhargurunani** [comment]
@cclauss @dhruvmanila Please tell whether this PR will be merged or not. It was marked stale.

**Review by cclauss — APPROVED** [review]
Thanks for your contribution

**Pull request merged**
