### PR TITLE
refactor: use abs() and inplace operation

### PR DESCRIPTION
**Pull request by Luk-ESC**
n = -n if n < 0 else n --> n = abs(n)
n = n // 10 --> n //= 10

### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
Did the `timeit()` benchmarks improve or not?

**Review by dhruvmanila — COMMENTED** [review]
These changes are fine, are there similar code elsewhere which can be refactored as well?

**Comment by cclauss** [comment]
I would like to avoid this issue https://github.com/TheAlgorithms/Python/pull/7190#issuecomment-1279545707. I think we are ok on this pr.

I still want to make sure that the timeit test show that the proposed solution is faster than the current one.

**Comment by dhruvmanila** [comment]
> I would like to avoid this issue [#7190 (comment)](https://github.com/TheAlgorithms/Python/pull/7190#issuecomment-1279545707). I think we are ok on this pr.

I do understand where you're coming from, but this is not an optimization, rather a refactor.

> I still want to make sure that the timeit test show that the proposed solution is faster than the current one.

There won't be any difference.

**Comment by cclauss** [comment]
> There won't be any difference.

Prove it.

**Review by CaedenPH — APPROVED** [review]
@cclauss Looks good

**Review by cclauss — APPROVED** [review]

**Pull request merged**
