### PR TITLE
Chrun Rate yet again

### PR DESCRIPTION
**Pull request by IBR-41379**
### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by IBR-41379** [comment]
Finally my all tests have passes

**Comment by cclauss** [comment]
I feel uncomfortable with this... https://en.wikipedia.org/wiki/Churn_rate describes the churn rate as a percentage over a given period such as 25% per year.  This calculation is truncating the output for unspecified reasons and also does not deliver a percentage over a given period.  The datafile is 10k lines which is quite substantial compared to other algorithms while the code delivers an output that is a bit baffling.

@tianyizheng02 @ChrisO345 Are you seeing something that I am not?

**Comment by IBR-41379** [comment]
Well for me, churn rate is the turnover rate of the customer from a company. This is a sample dataset I acquired from IBM skillset. Initially my program was simple with much more info. But due to various failing test(ruff, build) I had to modify quite a lot of thing, remove quite a lot of things to make it compatible. If this repo accepted jupyter notebooks, I could have shown in much more great detail. And the main purpose of the program is to show how decision tree classifier predicts.

**Comment by IBR-41379** [comment]
Well, my first first pull request is yet to be accepted. Let's see how it goes. Be sure to let me know what changes should I make.

**Comment by cclauss** [comment]
Please submit the original on https://github.com/TheAlgorithms/Jupyter and @mention me on that submission so perhaps we can land it there.  They have much easier requirements.

**Pull request closed without merging**
