### PR TITLE
Corrected the directory of Fractional Knapsack algorithm

### PR DESCRIPTION
**Pull request by SudhanshuSuman**
### Describe your change:
* Fractional knapsack uses a greedy approach and, hence, comes under greedy_methods and not under dynamic_programming.
* Moved the two fractional knapsack algorithm files to greedy_methods.

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by CaedenPH — CHANGES_REQUESTED** [review]
Please can you update these changes in `DIRECTORY.md`

**Comment by SudhanshuSuman** [comment]
> Please can you update these changes in `DIRECTORY.md`

Hey, @CaedenPH I noticed in contributing guidelines that we do not require updating the `DIRECTORY.md` file as GitHub Actions periodically autogenerates it. However, I have updated it now. Should I revert it back?

**Comment by CaedenPH** [comment]
> > Please can you update these changes in `DIRECTORY.md`
> 
> 
> 
> Hey, @CaedenPH I noticed in contributing guidelines that we do not require updating the `DIRECTORY.md` file as GitHub Actions periodically autogenerates it. However, I have updated it now. Should I revert it back?

Oh, I wasn't aware that there was a Github Action for this, I would assume that means you don't need to update DIRECTORY.md, however i assume that it wont make a difference now that you have updated it

**Comment by SudhanshuSuman** [comment]
> > > Please can you update these changes in `DIRECTORY.md`
> > 
> > 
> > Hey, @CaedenPH I noticed in contributing guidelines that we do not require updating the `DIRECTORY.md` file as GitHub Actions periodically autogenerates it. However, I have updated it now. Should I revert it back?
> 
> Oh, I wasn't aware that there was a Github Action for this, I would assume that means you don't need to update DIRECTORY.md, however i assume that it wont make a difference now that you have updated it

Yes.
Can you review the pull request? It seems @Kush1101 was requested but he is not active.

**Review by CaedenPH — APPROVED** [review]

**Comment by CaedenPH** [comment]
@cclauss Can you review? Looks good to me

**Comment by cclauss** [comment]
There is a git conflict below?  Are the algorithms being modified or just moved?

**Comment by SudhanshuSuman** [comment]
> There is a git conflict below? Are the algorithms being modified or just moved?

I have fixed the conflict, my branch was not up to date.
The algorithms are just moved.

**Review by cclauss — APPROVED** [review]

**Pull request merged**
