### PR TITLE
Add new algorithm for Fibonacci numbers

### PR DESCRIPTION
**Pull request by AndersonTorres**
### **Describe your change:**

A new algorithm for calculate Fibonacci numbers, using a method similar to fast exponentiation.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by appgurueu** [comment]
Isn't this one of the worst algorithms for computing the fibonacci numbers? There exists a closed form. I did a quick test for the 100th number:

```python3
calls = 0

def binary_recursive_fibonacci(n: int) -> int:	
    """
    Returns the nth Fibonacci number.
    This function is based on the formulas:
    - F(2k+1) = F(k)**2 + F(k+1)**2
    - F(n+2) = F(n+1) + F(n)
    >>> [binary_recursive_fibonacci(i) for i in range(20)]
    [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]
    """
    global calls
    calls += 1
    if n == 0 or n == 1:
        return n
    k, rem = divmod(n, 2)
    if rem == 1:
        return (
            binary_recursive_fibonacci(k) ** 2 + binary_recursive_fibonacci(k + 1) ** 2
        )
    return binary_recursive_fibonacci(n - 1) + binary_recursive_fibonacci(n - 2)

print("Result: " + str(binary_recursive_fibonacci(100)))
print("Calls: " + str(calls))
```
These were the results:

```
Result: 354224848179261915075
Calls: 69561
```

Instead of the 100 steps an iterative algorithm would need, this requires ~70k function calls. Please include a warning that this algorithm constitutes a negative example.

**Comment by AndersonTorres** [comment]
Now I noticed. Some nodes are duplicated. I will redo this with a novel idea.

**Comment by appgurueu** [comment]
> Now I noticed. Some nodes are duplicated - the even case **merely** splits in two instead of split in half.
> I will redo this with a novel idea.
> 
> But the idea is to use recursive calls, indeed.

(emphasis mine)

This is not to be taken lightly. Splitting in half means logarithmic complexity, "splitting in two" as you call it most likely leads to exponential complexity.

**Comment by AndersonTorres** [comment]
Why is the bot not requiring descriptive names anymore?

**Pull request closed without merging**
