### PR TITLE
Changed how the Visited nodes are tracked

### PR DESCRIPTION
**Pull request by akashgkrishnan**
Updated the code to track visited Nodes with Set data structure instead of Lists to bring down the lookup time in visited  from O(N) to O(1)
as doing O(N) lookup each time in the visited List will become significantly slow when the graph grows

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by poyea — APPROVED** [review]
Thank you for your pull request!🤩

**Comment by dhruvmanila** [comment]
Can you show us some data regarding the change? Data might include the difference in time in running the same algorithm on the same input with same configuration, if any.

**Comment by dhruvmanila** [comment]
I don't see the difference you mentioned `O(n) -> O(1)`:
```console
$ time python graphs/bfs_shortest_path.py  # with set
['G', 'C', 'A', 'B', 'D']
4

real    0m0.094s
user    0m0.044s
sys     0m0.036s


$ time python graphs/bfs_shortest_path.py  # with list
['G', 'C', 'A', 'B', 'D']
4

real    0m0.097s
user    0m0.046s
sys     0m0.036s
```

**Comment by akashgkrishnan** [comment]
@dhruvmanila running on smaller inputs will yield similar results. the speed will be significantly faster if the graph has a 10^5 nodes

As you know the lookup time in an array is O(N) if we are using the **in** keyword.
```
4 in [1,2,3,4] 
```
will be O(N). getting items based on an index is O(1) other than that it is O(N) if we are using the **in** keyword

sets
```
4 in {1,2,3,4} 
```
will be O(1) as sets use hash function and store the items for fast lookups the only caveat being that all items need to be unique but here in this implementation that would be the same case even if we use the list ds

https://wiki.python.org/moin/TimeComplexity
the same is specified here.
you can check the time complexity of the in for both array and sets here

**Comment by dhruvmanila** [comment]
If possible can you show us with some practical examples? 
Also, please restore all the newlines.

**Review by theroyakash — APPROVED** [review]
looks okay

**Pull request merged**
