### PR TITLE
Graph algorithms

### PR DESCRIPTION
**Pull request by FarhanKasmani**
# Graph Algorithms:
1. All Pair Shortest Path
-- Can be used to find whether a graph contains negative cycle or not.
2. Breadth First Search
-- Finding topological ordering of Directed Acyclic Graph using BFS (Kahn's Algorithm)
-- Finding longest distance in Directed Acyclic Graph using Kahn's Algorithm
-- Check whether Graph is Bipartite or Not using BFS
3. Depth First Search
-- Detect cycle for Undirected Graph
-- Detect cycle for Directed Graph
-- Finding Strongly connected components (Kosaraju's Algorithm)
-- Finding Bridges in Undirected Graph (Tarjan's Algorithm)
-- Finding Articulation points in Undirected Graph
-- Finding Topological ordering of Directed Acyclic Graph using DFS
4. Minimum Spanning Tree
-- Prims Algorithm [ O(nlogn) ]
-- Krushkal's Algorithm [ O(nlogn) ]
5. Single Source Shortest Path
-- Dijkstra's Algorithm
-- Bellmann Ford Algorithm
6. Union Find Disjoint Set

### CODE REVIEW

**Comment by hktkqj** [comment]
Kruskal's Algorithm run in O(E log E) time complexity as I know (O(E log E) for Edge quick sort, then add safe Edge by using merge–find set)

**Comment by AnshulMalik** [comment]
Hey @FarhanKasmani , theses are a lot of changes for a single PR, can you please split them across PRs, each with one change?

**Comment by FarhanKasmani** [comment]
@AnshulMalik actually I wanted you to merge these algorithms in your Graph folder

**Comment by AnshulMalik** [comment]
Yep @FarhanKasmani, to do that, can you please create a separate PR for each of the algos that you have implemented? It's hard to review when there are so many changes.

**Comment by FarhanKasmani** [comment]
@AnshulMalik Yaa no problem

**Pull request closed without merging**
