### PR TITLE
Minimization of while loop in Armstrong Numbers

### PR DESCRIPTION
**Pull request by dwarka-9504**
The while loop is removed and simple length calculation is used so the task of minimization of while loop is achieved

### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER". #9968

### CODE REVIEW

**Review by haxkd — APPROVED** [review]

**Review by dwarka-9504 — COMMENTED** [review]
This code changes fixes all the problem explained that is the minimization of while loop by replacing it by length calculation  in armstrong number and so it is all fit to pass  review and merge.

**Review by dwarka-9504 — COMMENTED** [review]
as the code is approved please merge it

**Comment by haxkd** [comment]
the write access reviewer will merge it soon.

**Comment by tianyizheng02** [comment]
@lohith-lalam This PR calculates the number of digits using `len(str(n))` instead of `log10(n) + 1`. Do you prefer your original method? Or do you prefer this one?

**Comment by dwarka-9504** [comment]
i prefer my original changed code as it is simple to process and no unnecessary complications

**Review by haxkd — APPROVED** [review]

**Comment by dwarka-9504** [comment]
the reviewers have not yet merged my code ...please take this in consideration as soon as possible

**Review by tianyizheng02 — APPROVED** [review]
I prefer this over the log10 method because the latter can be incorrect if n is too large (due to the limitations of floating-point numbers)

**Pull request merged**
