### PR TITLE
Fixes #9943 Added Doctests to binary_exponentiation_3.py

### PR DESCRIPTION
**Pull request by vipinkarthic**
### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by vipinkarthic** [comment]
Can any maintainer please check my pull request, Ty!

**Comment by vipinkarthic** [comment]
@tianyizheng02 , Is the number of commits the PR shows is fine? It is showing all the commits of the previous PR as well as the commits for the current PR. Thanks in advance for taking a look into my doubt and PR

**Comment by tianyizheng02** [comment]
The number of commits doesn;'t matter. In this repo, we use "squash and merge", which means that all the commits for a single PR are combined into a single commit when the PR is merged.

**Comment by tianyizheng02** [comment]
Also, we can't merge this because there are merge conflicts. I renamed `binary_exponentiation_3.py` to `binary_exponentiation_2.py` in a previous PR (#9656), so you should rename the file here as well in order to resolve the conflict.

**Comment by vipinkarthic** [comment]
> The number of commits doesn;'t matter. In this repo, we use "squash and merge", which means that all the commits for a single PR are combined into a single commit when the PR is merged.

Also, if a PR is already open and not merged yet, should I wait till it's merged to create a new PR for another issue?

**Comment by vipinkarthic** [comment]
> Also, we can't merge this because there are merge conflicts. I renamed `binary_exponentiation_3.py` to `binary_exponentiation_2.py` in a previous PR (#9656), so you should rename the file here as well in order to resolve the conflict.

I have renamed the file, but it still says there is some error, can you help me with it , Thank You !

**Review by tianyizheng02 — APPROVED** [review]

**Pull request merged**
