### PR TITLE
Added page-rank algorithm implementation

### PR DESCRIPTION
**Pull request by bhushan-borole**

### CODE REVIEW

**Comment by bhushan-borole** [comment]
Can somebody help me with the pull request issue

**Comment by poyea** [comment]
Will merge this soon.

**Comment by bhushan-borole** [comment]
That would be great @poyea

**Comment by poyea** [comment]
We can improve the code by stating input requirement and description as comments.

**Comment by bhushan-borole** [comment]
Sure will do that

**Pull request merged**
