### PR TITLE
Add Qiskit Quantum NOT Gate Example Code

### PR DESCRIPTION
**Pull request by abhishekjiitr**
### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by abhishekjiitr** [comment]
@cclauss can you review?

**Comment by abhishekjiitr** [comment]
@cclauss thanks for reminding. I overlooked the changes you finally added before merging.
The new commit adds changes requested similar to the one in the previous code.

**Review by cclauss — APPROVED** [review]
OK..  Let's land this one eventhough it just looks like a how-to-use example rather than a real algorithmic function.  The two files we have so far do not help the reader to understand how quantum is better than convention computing.  So far, they are just data goes in and data comes out kind of functions with no story about what the data is and how the answer that comes out 1. makes the world a better place and 2. is obtained faster or with more accuracy than conventional computers can achieve.

**Comment by dhruvmanila** [comment]
Um, is there any reason why you are merging failed commits?

**Comment by cclauss** [comment]
The commit failed because we autodelete branches once they are merged.  This means that the branch may already be gone before Travis and GH Actions have the time to clone them in.

**Comment by cclauss** [comment]
Ooops... Now I see the problem.  Sorry for moving too quickly.

**Pull request merged**
