### PR TITLE
create amicable_number.py

### PR DESCRIPTION
**Pull request by iamnambiar**
### **Describe your change:**
Created a file named amicable_numbers.py which takes two number and check whether the pair is amicable or not.

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
Is this somehow better than https://github.com/TheAlgorithms/Python/blob/master/project_euler/problem_21/sol1.py

**Comment by iamnambiar** [comment]
@cclauss Sorry, I havent seen that one before. But my code is to check whether the number is amicable or not. That code just finds the sum of proper divisor.

**Comment by iamnambiar** [comment]
The algorithm to find the sum of divisor is similar.

**Comment by iamnambiar** [comment]
Sorry, I havent seen that one. I'll close this pull request. @cclauss

**Pull request closed without merging**
