### PR TITLE
Edit_Distance algorithm for genetic string matching

### PR DESCRIPTION
**Pull request by anshul-2010**
### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by tianyizheng02** [comment]
You checked this checkbox, so you acknowledged this:
> - [x] All new Python files are placed inside an existing directory.

**Comment by tianyizheng02** [comment]
My mistake, I had forgotten that we had a separate directory for genetic algorithms. However, edit distance is still definitely not a genetic algorithm. We also already have multiple implementations of edit distance (using dynamic programming). Since your implementation doesn't use DP, you're welcome to add it to one of the existing files instead of creating a separate file.

**Comment by anshul-2010** [comment]
I added it to the genetic algorithms considering that edit distance would be used for genome matching scenarios.
But sure, I will add it to some other existing file if you say so.

**Comment by tianyizheng02** [comment]
Superseded by #10571

**Pull request closed without merging**
