### PR TITLE
Add tests to maths/binary_exponentiation.py

### PR DESCRIPTION
**Pull request by MaximSmolskiy**
### Describe your change:

Increase test coverage from
```
maths/binary_exponentiation.py                                               15     13    13%   9-17, 21-28
```
to
```
maths/binary_exponentiation.py                                               15      7    53%   25-32
```

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by CaedenPH — CHANGES_REQUESTED** [review]
Could you add more tests, at least to this file?

**Comment by MaximSmolskiy** [comment]
> Could you add more tests, at least to this file?

This one test covers all branches (cases)

**Comment by cclauss** [comment]
> This one test covers all branches (cases), so I think it will be enough

Does it cover negative numbers, zero, large numbers, floating point numbers, large negative floating point numbers, letters?  As discussed in CONTRIBUTING.md, tests should demonstrate how the algorithm works and also how it deals with bad input.

**Comment by cclauss** [comment]
Please do not open new pull requests in this repo until November 1st. 2022.

**Pull request closed without merging**
