### PR TITLE
Create kinetic_energy.py

### PR DESCRIPTION
**Pull request by SparshRastogi**
Finding the kinetic energy of an object,by taking its mass and velocity as input

### Describe your change:

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by cclauss — APPROVED** [review]

**Comment by matteomessmer** [comment]
@cclauss there are many older PRs waiting for reviews, could they be merged?

**Comment by cclauss** [comment]
It takes time to review and I am not paid for this and have limited time.

**Comment by cclauss** [comment]
If you recommend some PRs that you think are good to go, I could prioritize reviewing them first.

**Comment by matteomessmer** [comment]
Hi @cclauss, I'm trying to participate in hacktoberfest and I would need a merged PR, if you could review #6879 it would be nice 😄 Thanks

**Pull request merged**
