### PR TITLE
Bump actions/checkout to v3 (#4133)

### PR DESCRIPTION
**Pull request by madhead**
### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?
* [x] CI scripts fix

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by cclauss — CHANGES_REQUESTED** [review]
The comment is on this line because accepting this change would break the `Update DIRECTORY.md` job step.  V1 allows repo maintainers to write changes back to a pull request while later versions do not.

The best solution would be to move `Update DIRECTORY.md` to [pre-commit](https://pre-commit.com) as a _local_ job and once we are confident that works, we can remove the job step here and upgrade the Action.

**Comment by madhead** [comment]
I see. I tested it in my fork and it pushed the change, but I didn't see similar changes pushed by the bot.

What do you mean by "allows repo maintainers to write changes back to a pull request while later versions do not". Do you want this workflow to update the PRs automatically with the updated MD file. I mean, when someone pushes a new algorithm, do you want this workflow to update (add commits) to the same PR?

**Comment by cclauss** [comment]
> I didn't see similar changes pushed by the bot.

Are you a **maintainer** on this repo?

https://github.com/TheAlgorithms/Python/blob/master/scripts/build_directory_md.py Writes a new file.

>  when someone pushes a new algorithm, do you want this workflow to update (add commits) to the same PR?

When a **project maintainer** makes a modification, a new markdown file is generated and added to the same PR.

Pre-commit was designed to do this so the best solution would be to move `build_directory_md.py` to pre-commit.

**Comment by dhruvmanila** [comment]
I don't think pre-commit is the right place to put it as most of the contributors won't install it. It's possible to do the auto-commit on PR or maybe after merging the PR. Let me take a closer look at it as I've seen it done on other projects.

This PR can be closed as of now as this requires a bit of discussion into how we want to do this.

**Comment by cclauss** [comment]
> most of the contributors won't install it

They do not have to because we run https://results.pre-commit.ci/repo/github/63476337 on every pull request.  Have you noticed that if you submit a PR that is not black formatted or isort sorted not pyupgrade compatible, pre-commit.ci is laying a commit on top that fixes all these issues.  This is saving us tons of grief.

**Comment by dhruvmanila** [comment]
Yes, I'm aware of that but does it work on local hooks? Another alternative would be to keep this script in a separate repo which will define the hook and thus allowing us to use it across all our repositories. I don't know if this works or not, don't have details regarding how the script works, but I guess if the structure is similar then it should work.

**Comment by cclauss** [comment]
I will submit a solution in a few hours unless @madhead wants to give it a whirl.

**Pull request closed without merging**
