### PR TITLE
Optimized O(N) -> O(1) for a __contains__ check inside linked_list/has_loop.py

### PR DESCRIPTION
**Pull request by yordangrigorov97**
### **Describe your change:**
data_structures/linked_list/has_loop.py: class Node: __iter__:
Previous implementation used lists for keeping track of visited nodes. The corrected version uses sets. See
[https://wiki.python.org/moin/TimeComplexity](https://wiki.python.org/moin/TimeComplexity
)

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by algobytewise** [comment]
I think your comment in line 17 needs one more space before the #-sign if I read the error message correctly.

**Comment by yordangrigorov97** [comment]
@algobytewise You are right. I also accidentally pushed a separate PR into this one. I'll revert that and make it PEP8 conformant.

**Comment by cclauss** [comment]
What would be supercool is to have both approaches in a single file with a [`timeit`](https://github.com/TheAlgorithms/Python/search?q=timeit) (or similar) benchmark that quatifies the performance improvement.

**Comment by yordangrigorov97** [comment]
@cclauss That's a great idea. Thanks for bringing it up.

**Pull request closed without merging**
