### PR TITLE
Travis CI: Simplify the testing

### PR DESCRIPTION
**Pull request by cclauss**
```yaml
language: python
install: pip install flake8
script: flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics
```

### CODE REVIEW

**Comment by poyea** [comment]
I think the repository only enables LGTM and maybe there's no need to use Travis anyone.

**Comment by cclauss** [comment]
The problems are that:
1. [LGTM does not want us running flake8 on their infrstructure](https://discuss.lgtm.com/t/can-i-get-lgtm-to-run-flake8-tests/1445/6) and
2. when we do, it [does not work as expected](https://discuss.lgtm.com/t/tests-are-not-automatically-run-when-lgtm-yml-is-modified/1446/4).

This can be seen in #882 which _failed_ the LGTM tests even though it fixed the syntax error.  It was only _after_ #882 was merged that the LGTM tests started to pass.  We want the test runner to test the code the current pull request but LGTM always tests the __master__ branch.  Travis CI or CircleCI (#888) will test the current pull request and tell us if the code in that pull request should be accepted or not.

**Comment by poyea** [comment]
I'll leave this to the owners. @AnupKumarPanwar

**Comment by cclauss** [comment]
@AnupKumarPanwar Can we please get https://travis-ci.org/TheAlgorithms/Python re-enabled?

**Comment by AnupKumarPanwar** [comment]
@cclauss It's already enabled.

**Comment by cclauss** [comment]
Great!  Thanks.

**Comment by AnupKumarPanwar** [comment]
@cclauss @poyea I don't suggest using multiple CI tools. We can discuss which one to use.

**Comment by cclauss** [comment]
Can we please get this PR reviewed and merged?  Now that Travis CI has been enabled [all of our new PRs are failing](https://github.com/TheAlgorithms/Python/pulls) which slows down the contribution and review process.  This PR should get them working again.

I have no problem running multiple CI tools (_many_ projects do so) but once this PR has landed, we can disable LGTM if desired.  Travis CI is clearly more flexible than LGTM.

**Pull request merged**
