### PR TITLE
Add Single Shot MultiBox Detector

### PR DESCRIPTION
**Pull request by siddharthjain1611**
### Added object detection algorithm with SSD**

Fixes: #1791

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{}`.

### CODE REVIEW

**Comment by cclauss** [comment]
This repo does not accept `.ipynb` files.

Please move this submission to https://github.com/TheAlgorithms/Jupyter

**Comment by cclauss** [comment]
./Object_Detection_With_SSD/Module_2_Object_Detection_With_SSD.ipynb:77: occurences  ==> occurrences
  file = builtins.open(filename, mode, buffering)
./Object_Detection_With_SSD/Module_2_Object_Detection_With_SSD.ipynb:84: occurance  ==> occurrence
./Object_Detection_With_SSD/Module_2_Object_Detection_With_SSD.ipynb:86: occurance  ==> occurrence
./Object_Detection_With_SSD/layers/box_utils.py:74: mathing  ==> matching
./Object_Detection_With_SSD/data/voc0712.py:37: Initilized  ==> Initialized

**Comment by siddharthjain1611** [comment]
@cclauss I'll do that plus i'll change notebook to .py file and update the PR.

**Comment by cclauss** [comment]
Below, Travis CI says:
```
16    F401 '.voc0712.VOCDetection' imported but unused
4     F403 'from .config import *' used; unable to detect undefined names
3     F405 'PriorBox' may be undefined, or defined from star imports: layers
23
```
And codespell finds typos.

**Pull request closed without merging**
