### PR TITLE
Flake8: Drop ignore of issue A003

### PR DESCRIPTION
**Pull request by cclauss**
### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by CaedenPH — CHANGES_REQUESTED** [review]
Personally, I prefer attributes such as `next` and `prev` to `next_` and `prev_`
Especially when it comes to `set` and `put`, because they are different concepts.
I don't see a problem with globally ignoring `A003`

**Review by poyea — APPROVED** [review]

**Comment by dhruvmanila** [comment]
I agree with @CaedenPH on this and was [discussed earlier](https://github.com/TheAlgorithms/Python/pull/7105) as well. `A003` is a false positive and is supposedly going to be disabled by default in the plugin itself. I suggest to revert this change.

**Comment by cclauss** [comment]
@gilforcada Your sense of this pull request?  Does `A003` generate false positives?  Should we revert?

**Comment by dhruvmanila** [comment]
@cclauss there's no such user

**Comment by gforcada** [comment]
If my opinion is asked, here is is given 😄 : I very much prefer to keep `A003` enabled on the plugin itself, and let each user decide if it's useful or not. For my projects I very much prefer not to use builtins even on `A003` cases, that my personal preference. Fortunately `flake8` has a powerful configuration system and you probably are already configuring some bits of it anyway. I will not get offended if someone ignores `A003` 😃

**Pull request merged**
