### PR TITLE
Add smooth algorithm

### PR DESCRIPTION
**Pull request by mohmmadAyesh**
### Describe your change:

* [x ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ x] This pull request is all my own work -- I have not plagiarized.
* [x ] I know that pull requests will not be merged if they fail the automated tests.
* [ x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x] All new Python files are placed inside an existing directory.
* [ x] All filenames are in all lowercase characters with no spaces or dashes.
* [ x] All functions and variable names follow Python naming conventions.
* [ x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [ ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Comment by mohmmadAyesh** [comment]
@cclauss Hi can you review this PR or any of maintainer and merge if it has not required any further suggested changes?

**Comment by tianyizheng02** [comment]
I found this [GeeksforGeeks](https://www.geeksforgeeks.org/introduction-to-smooth-sort/) article with nearly identical code. The only differences appear to be comments and some function and variable names. I'm not flagging this as plagiarism right out of the gate because I can't definitively prove that the article was written before this PR was made, though this PR is still suspect.

@cclauss, thoughts on whether this should be flagged as plagiarism? If so, we can just close this PR. If not, I think we can let it pass with the caveat that the code must be refactored/rewritten and more thoroughly documented.

**Comment by mohmmadAyesh** [comment]
I will delete the PR but can you remove this tag cause it will harm my account in future @tianyizheng02

**Comment by tianyizheng02** [comment]
You haven't provided any evidence that this PR was your own work, especially in light of that GeeksforGeeks article. If you did actually plagiarize this PR, then why should we remove the plagiarism label? If your reputation is stained because people see that you plagiarized in the past, would those people be mistaken? If I've made a mistake here and you truly wrote this code yourself (and it's GeeksforGeeks who plagiarized from you), then please explain your situation to us and convince us with evidence. If you can do that, then I'll gladly remove the label.

In any case, I had deferred to @cclauss for the final decision since he's a much more senior maintainer of this repo than I am. @cclauss, since you closed the PR, it'd be nice if you could weigh in on this as well. My personal stance is that the plagiarism label stays.

**Comment by mohmmadAyesh** [comment]
Dear [@tianyizheng02 ],

Thank you for taking the time to review my pull request and for providing valuable feedback.

I acknowledge that the content in the PR was derived from a GeeksforGeeks article and that proper attribution was not provided. Given the plagiarism concerns and to maintain the integrity of the project, I would like to respectfully request that the entire pull request be deleted.

I understand the importance of original contributions and proper attribution, and I will ensure to adhere to these principles in my future contributions.

Thank you for your understanding and consideration. I appreciate the opportunity to contribute and learn from this experience.

Sincerely,
[mohmmad Ayesh]

**Comment by 99991** [comment]
> Dear @tianyizheng02 ,
> 
> Thank you for taking the time to review my pull request and for providing valuable feedback.
> 
> I acknowledge that the content in the PR was derived from a GeeksforGeeks article and that proper attribution was not provided. Given the plagiarism concerns and to maintain the integrity of the project, I would like to respectfully request that the entire pull request be deleted.
> 
> I understand the importance of original contributions and proper attribution, and I will ensure to adhere to these principles in my future contributions.
> 
> Thank you for your understanding and consideration. I appreciate the opportunity to contribute and learn from this experience.
> 
> Sincerely, mohmmad Ayesh

Did you also plagiarize this apology? (ChatGPT)

**Comment by mohmmadAyesh** [comment]
No, I did not plagiarize my apology. Then, I really realized that I had made a mistake with the algorithm that I had learned from GeeksforGeeks and afterwards really apologized for having made it. I really do not understand why anybody thinks an apology itself can be plagiarized-my objective was to be truly apologetic.

Sometimes, I use some assistance from tools like ChatGPT to help me express myself in English because it's not my native language. In making this apology, I wanted my words and intentions to be mine, but I have used the tool to double-check that the message is as clear and polite as possible. My intention was to honestly express my feelings and acknowledge my mistake. One should never think that if a tool helps someone clearly articulate their thoughts, then their words or intentions are less forthright.

**Pull request closed without merging**
