### PR TITLE
[mypy] Added/fixed type annotations for "crawl_google_results.py" & "crawl_google_scholar_citation.py"

### PR DESCRIPTION
**Pull request by algobytewise**
### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
[mypy --ignore-missing-imports](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-ignore-missing-imports)

**Comment by algobytewise** [comment]
The errors don't arise in the original files when running mypy with the parameter "--ignore-missing-imports". Should files with this type of error be fixed nonetheless or can they be ignored?

**Comment by algobytewise** [comment]
The advantage would be that we have to fix less files. But I'm not sure whether it's in our interest to ignore all missing import errors instead of selecting which one's to ignore.

**Comment by algobytewise** [comment]
Could someone have a look at this contribution?

**Comment by cclauss** [comment]
Instead, please run `mypy --ignore-missing-imports` and find and fix mypy issues in our code (not the issues in our imports) so that we can uncomment these tests.  https://github.com/TheAlgorithms/Python/blob/master/.pre-commit-config.yaml#L33

**Pull request closed without merging**
