### PR TITLE
Added tests for validate_sudoku_board.py

### PR DESCRIPTION
**Pull request by AksharGoyal**
### Describe your change:

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Add or change doctests? -- Note: Please avoid changing both code and tests in a single pull request.
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue):

### CODE REVIEW

**Comment by cclauss** [comment]
Closing.  This pull request modifies eight different files.

**Comment by AksharGoyal** [comment]
Hi @cclauss , I am not sure how writing tests for Sudoku affected other files. Can I get some more information on how it happened so that if I open another PR it doesn't affect them?

**Comment by cclauss** [comment]
The trick is to _always_ create pull requests on a branch other than `master`.
1. Go to `https://github.com/AksharGoyal/Python` and click the `Sync fork` button so your `master` is up-to-date
2. Go to https://github.com/AksharGoyal/Python/branches and click the `New branch` button at the upper-right and give the branch a name that makes it clear what the intended change is.

If 1. is not done before 2. the previous edits can creep in.

**Comment by AksharGoyal** [comment]
I did create a branch this time for adding tests for sudoku but looks like the PR from last time affected this one. I will re-fork and create a branch so this time nothing is affected. Thank you.

**Pull request closed without merging**
