### PR TITLE
replace base64_cipher.py with an easy to understand version

### PR DESCRIPTION
**Pull request by hfz1337**
### **Describe your change:**
This PR changes the existing `base64_cipher.py` with an easy to understand script that explains how the Base64 algorithm works under the hood. The solution is not necessarily faster, but I believe it will help people understand how the algorithm works and why it is possible to use Base64 in Steganography to conceal the existence of a piece of data.
Further more, I believe the `base64_cipher.py` name can be misleading as Base64 is considered an encoding, and not a cipher.

* [ ] Add an algorithm?
* [X] Improve an existing solution.
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [X] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by hfz1337** [comment]
Thanks for your suggestions.
I made the necessary changes, however, I can't seem to reopen this pull request.
Should I make a new one?

**Comment by cclauss** [comment]
It is now reopened but conflicts need to be resolved.

**Comment by dhruvmanila** [comment]
It seems that the bot scanned the file which was deleted and added the `require:` labels for that. I will make the changes for that.

**Comment by hfz1337** [comment]
My bad, sorry. Should've used `git mv` and worked on the old implementation instead adding a new file and causing all these troubles.

**Comment by dhruvmanila** [comment]
You can still do that now :)

**Comment by hfz1337** [comment]
I'll open a new one, I think it will be easier.

**Comment by dhruvmanila** [comment]
Do not get demotivated by a challenge. Try to overcome the obstacle. Only then you will be able to learn :)

**Comment by hfz1337** [comment]
Thanks a lot for the advice and motivation.
I opened a new PR [here](https://github.com/TheAlgorithms/Python/pull/3925).
Also, I noticed something about `algortihms-keeper`, when I used an uppercase `X` to mark respected points in the PR description, it instantly closed the PR. Shouldn't it accept both uppercase and lowercase `X` as both `[x]` and `[X]` are valid in markdown?
It was a bit confusing :p

**Comment by dhruvmanila** [comment]
Oh, yes completely missed that. Thank you for pointing this out. Also, in the future, if you think the bot is doing something wrong, [please open an issue here](https://github.com/dhruvmanila/algorithms-keeper/issues) 😄 

P.S. If you want you can open this issue as well :)

**Comment by hfz1337** [comment]
Sounds cool, thanks! :d

**Pull request closed without merging**
