### PR TITLE
 Updated basic_binary_tree.py

### LINKED ISSUE #8865: Additional Features for Binary Tree Implementation
### Feature description

I would like to modify the basic_binary_tree.py file under **datastructures/binary_tree section**. I propse adding a new BinaryTree class which will serve as a main interface for creating and manipulating binary trees. Additionally i want all the utilities function of the present file to be the methods of the new class.

### PR DESCRIPTION
**Pull request by dasdebanna**
The BinaryTree class has been created with the root node as its only argument. The utility functions have been modified to be methods of the BinaryTree class. The display, depth_of_tree, and is_full_binary_tree functions now take self as their first argument. The main function has been modified to create a BinaryTree object and call its methods instead of calling the utility functions directly.

### Describe your change:

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://github.com/TheAlgorithms/Python/issues/8865): "Fixes #8865 ".

### CODE REVIEW

**Comment by dasdebanna** [comment]
Can any maintainer preview the updated code?

**Comment by dasdebanna** [comment]
Any maintainer please see the updated code and close this issue https://github.com/TheAlgorithms/Python/issues/8865

**Comment by dasdebanna** [comment]
> In PR description, `• []` should be replaced by `•[x]`

I have changed the PR description

**Comment by tianyizheng02** [comment]
Thank you for your contribution, but unfortunately we're not accepting new PRs at the moment. We're currently trying to clear our backlog of existing PRs in preparation for Hacktoberfest. If you want to contribute, please wait until after October 1 to do so. See [this discussion](https://github.com/TheAlgorithms/Python/discussions/8912#discussion-5458835) for more info.

**Comment by dasdebanna** [comment]
Hi there,

I understand the current situation and the preparations for Hacktoberfest.
However, I was wondering if you could make an exception and merge my PR. It
was my first time contributing to such a large project, and I genuinely put
in effort to select the issue, work on it, and pass the 3 checks. I would
really appreciate it if you could consider my request.

Thank you for your understanding.

Best regards,
Debanna Das

**Pull request closed without merging**
