### PR TITLE
Added Finding Exponent Program

### PR DESCRIPTION
**Pull request by Utsav1999**
### **Describe your change:**
Python recursion program for finding exponent.

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Python files are placed inside an existing directory.
* [X] All filenames are in all lowercase characters with no spaces or dashes.
* [X] All functions and variable names follow Python naming conventions.
* [X] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [X] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
I do not understand this algorithm.  We say that we are "finding the exponent" but we are emulating https://docs.python.org/3/library/functions.html#pow which returns ___base to the power exp___.  That is that exp is an _input_ to the function, not an output of it.  In my suggestions at https://github.com/TheAlgorithms/Python/pull/2236#discussion_r460506897 I added more self-documenting variable names and doctests.  Without these elements, the PR will not be merged.

**Comment by Utsav1999** [comment]
Then I can say it **power calculation program** instead of saying **Finding exponent program**.

**Comment by Utsav1999** [comment]
@cclauss 
Below are some inputs and outputs according to your test cases.
`Enter the base: 10
Enter the exponent: 10
10 to the power of 10: 10000000000`

`Enter the base: -9
Enter the exponent: 10
-9 to the power of 10: 3486784401`

`Enter the base: 8 
Enter the exponent: 6
8 to the power of 6: 262144`

**Comment by cclauss** [comment]
@TravisBuddy hates when we merge too fast.  There is nothing wrong here except that we merged the PR before Travis could finish.

**Pull request merged**
