### PR TITLE
Update bubble_sort.py

### PR DESCRIPTION
**Pull request by signorrayan**
Improved function and output time.

new function output time: 
0.06883952538999999

The average of the previous function time, for random numbers between -5000 to 21000:
0.07642653496999999

### **Describe your change:**

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
Please create a [timeit](https://github.com/TheAlgorithms/Python/search?q=timeit) benchmark to demonstrate the performance improvement.

**Comment by signorrayan** [comment]
@cclauss thanks, where i should create that? 
i used `time.process_time()` function. how i can share the output?

**Comment by cclauss** [comment]
Please see the other examples.  You need to have both functions in one file along with the timeit benchmark.  Both functions should have the same type hints and pass the same doctests.  Repeated benchmarks like timeit are better than running the functions just once.

**Comment by signorrayan** [comment]
ok i will test, but i ran this way:

```
import random


def bubble_sort1(arr):
    n = len(arr)
    for i in range(n):  # i : 1 -> n
        for j in range(0, n - i - 1):  # j -> n -i -1 , -1 for the j+1 comparison of last element
            if arr[j] > arr[j + 1]:  # if current is bigger than next
                arr[j], arr[j + 1] = arr[j + 1], arr[j]  # swap current and next
    return arr


def bubble_sort2(collection):
    length = len(collection)
    for i in range(length - 1):
        swapped = False
        for j in range(length - 1 - i):
            if collection[j] > collection[j + 1]:
                swapped = True
                collection[j], collection[j + 1] = collection[j + 1], collection[j]
        if not swapped:
            break  # Stop iteration if the collection is sorted.
    return collection

sort2 = []
sort1 = []
if __name__ == "__main__":
    import time

    # # for i in range(100):
    # arr = [random.randint(-5000, 21000) for x in range(1000)]
    # print(timeit("bubble_sort1(arr)", setup="from __main__ import bubble_sort1"))

    for i in range(100):
        user_input = [random.randint(-5000, 21000) for x in range(1000)]
        start = time.process_time()
        bubble_sort1(user_input)
        ends = time.process_time()
        sort1.append(ends - start)
    print("sort1: ", sum(sort1) / len(sort1))

    for i in range(100):
        user_input = [random.randint(-5000,21000) for x in range(1000)]
        start = time.process_time()
        bubble_sort2(user_input)
        ends = time.process_time()
        sort2.append(ends - start)
    print("sort2: ", sum(sort2)/len(sort2))
```

**Comment by cclauss** [comment]
https://travis-ci.com/github/TheAlgorithms/Python/builds/182271229#L313-L320

**Pull request closed without merging**
