### PR TITLE
Fixed Pytest warnings for machine_learning/forecasting

### PR DESCRIPTION
**Pull request by p1utoze**
### Describe your change:

Fixes [#7305] [#8780]
The numpy Runtime warning was due to the 0 in `seasonal_order` tuple and regarding the ARIMA models. For estimation, it needs more observations to work well and the User Warning are raised because of the sample test `>>> sarimax_predictor([4,2,6,8], [3,1,2,4], [2])` used by doctests. 

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [x] All functions and variable names follow Python naming conventions.
* [x] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".

### CODE REVIEW

**Review by tianyizheng02 — APPROVED** [review]
LGTM! The build logs no longer show the Pytest warnings, which is nice. However, this PR doesn't _completely_ fix #8780 as there are some deeper issues that still need to be addressed: where the code actually comes from, the use of existing ML models, and whether this code actually qualifies as an "algorithm". With that said, the more immediate issues seem to have been fixed, which is good.

**Comment by tianyizheng02** [comment]
@CaedenPH, thoughts?

**Review by CaedenPH — APPROVED** [review]
@tianyizheng02 
I would be inclined to merge this pull request but also have discussions on #8780 with what to do with this file and potentially rework later.
Therefore, I think it should close my issue (#7305) but not #8780

**Comment by tianyizheng02** [comment]
@p1utoze Thanks for your contributions!

**Comment by p1utoze** [comment]
@tianyizheng02 I agree. I looked into that aspect as well that the algorithms mentioned clearly don't explain about the forecasting. Well, fixing the existing errors was much needed I felt and glad to contribute.

**Pull request merged**
