### PR TITLE
Adding top 100 contributor in readme.md update

### LINKED ISSUE #10384: Top 100 contribur Picute in contributor section on readme.md file
### Feature description

I want to add top 100 contributor profile like added in following repo 
contribor

### PR DESCRIPTION
**Pull request by MuhammadNizamani**
### Describe your change:

* [x] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [x] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [x] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [x] All new algorithms include at least one URL that points to Wikipedia or another similar explanation.
* [x ] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a Closed #10384  Fixes #10384.

### CODE REVIEW

**Comment by cclauss** [comment]
Closing as a duplicate of #10461

**Comment by MuhammadNizamani** [comment]
@cclauss  the issue was created by me and I was working on this issue so why some else is allow to create PR on my issue ?

**Comment by cclauss** [comment]
Because according to CONTRIBUTING.md, you are not supposed to create an issue to add a new algorithm,

**Comment by MuhammadNizamani** [comment]
ok understand

**Pull request closed without merging**
