### PR TITLE
Unify primality checking

### LINKED ISSUE #5434: Deduplicate repeated `is_prime` functions
We have a lot of `is_prime` (or similar) functions: https://github.com/TheAlgorithms/Python/search?p=4&q=is_prime, https://github.com/TheAlgorithms/Python/search?q=isPrime, [data_structures/hashing/number_theory/prime_numbers](https://github.com/TheAlgorithms/Python/blob/master/data_structures/hashing/number_theory/prime_numbers.py), etc. Shall we use one common function for that exactly identical `is_prime` calculation (which takes `O(sqrt(n))`)?

Candidates include:
* [maths/prime_check](https://github.com/TheAlgorithms/Python/blob/master/maths/prime_check.py)
* [maths/primelib](https://github.com/TheAlgorithms/Python/blob/master/maths/primelib.py)

### PR DESCRIPTION
**Pull request by elpaxoudis**
### Describe your change:

I refactored some functions in order to fix #5434. More specifically,

1. I changed the name of some function in order to agree with naming conventions.
2. I changed the implementation of a primality checking function in order to have a `O(sqrt(n))` time complexity algorithm.

There are some more functions that are related to primality checking namely the [lucas_lehmer_primality_test.py](https://github.com/TheAlgorithms/Python/blob/master/maths/lucas_lehmer_primality_test.py) and [miller_rabin.py](https://github.com/TheAlgorithms/Python/blob/master/maths/miller_rabin.py) but I did not change these since they are specific algorithms.

I have searched for every mention of the word `prime` in all of the files and except from the [project_euler](https://github.com/TheAlgorithms/Python/tree/master/project_euler) I think that there are no other mentions on the primality testing subject.

* [ ] Add an algorithm?
* [x] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### Checklist:
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Python/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Python files are placed inside an existing directory.
* [ ] All filenames are in all lowercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Python naming conventions.
* [ ] All function parameters and return values are annotated with Python [type hints](https://docs.python.org/3/library/typing.html).
* [ ] All functions have [doctests](https://docs.python.org/3/library/doctest.html) that pass the automated testing.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by elpaxoudis** [comment]
I think I have done something wrong with my commit history... Is there a way of fixing this?

**Comment by elpaxoudis** [comment]
> I think I have done something wrong with my commit history... Is there a way of fixing this?

Nevermind, fixed it!

**Review by poyea — APPROVED** [review]
Thank you for your pull request!🤩

**Comment by poyea** [comment]
It would be great if we can check against also the [project_euler](https://github.com/TheAlgorithms/Python/tree/master/project_euler) files. Let's merge this and have the updates in #5434

**Pull request merged**
